import json
from pathlib import Path

BASE = Path(__file__).parent
PASTA = BASE / "dados" / "ingles"

# ============ 🏠 CASA E OBJETOS (90 itens) ============
casa = [
    # Ambientes
    {"pt": "casa",           "en": "house",           "pron": "ráus"},
    {"pt": "apartamento",    "en": "apartment",       "pron": "apártment"},
    {"pt": "quarto",         "en": "bedroom",         "pron": "bédrum"},
    {"pt": "sala de estar",  "en": "living room",     "pron": "líving rum"},
    {"pt": "sala de jantar", "en": "dining room",     "pron": "dáining rum"},
    {"pt": "cozinha",        "en": "kitchen",         "pron": "kítchen"},
    {"pt": "banheiro",       "en": "bathroom",        "pron": "béthrum"},
    {"pt": "garagem",        "en": "garage",          "pron": "garáj"},
    {"pt": "jardim",         "en": "garden",          "pron": "gárden"},
    {"pt": "quintal",        "en": "backyard",        "pron": "békiard"},
    {"pt": "varanda",        "en": "balcony",         "pron": "bélkoni"},
    {"pt": "porão",          "en": "basement",        "pron": "béismeint"},
    {"pt": "sótão",          "en": "attic",           "pron": "étik"},
    {"pt": "escritório",     "en": "office",          "pron": "ófis"},
    {"pt": "corredor",       "en": "hallway",         "pron": "róluei"},
    {"pt": "lavanderia",     "en": "laundry room",    "pron": "lóndri rum"},

    # Estrutura
    {"pt": "porta",          "en": "door",            "pron": "dór"},
    {"pt": "janela",         "en": "window",          "pron": "uíndou"},
    {"pt": "parede",         "en": "wall",            "pron": "uól"},
    {"pt": "chão",           "en": "floor",           "pron": "flór"},
    {"pt": "teto",           "en": "ceiling",         "pron": "síling"},
    {"pt": "telhado",        "en": "roof",            "pron": "rúf"},
    {"pt": "escada",         "en": "stairs",          "pron": "stérs"},
    {"pt": "elevador",       "en": "elevator",        "pron": "éleveitor"},
    {"pt": "campainha",      "en": "doorbell",        "pron": "dórbel"},
    {"pt": "fechadura",      "en": "lock",            "pron": "lók"},
    {"pt": "maçaneta",       "en": "doorknob",        "pron": "dórnob"},
    {"pt": "tomada",         "en": "outlet",          "pron": "áutlet"},
    {"pt": "interruptor",    "en": "switch",          "pron": "suích"},

    # Móveis
    {"pt": "cama",           "en": "bed",             "pron": "béd"},
    {"pt": "mesa",           "en": "table",           "pron": "téibol"},
    {"pt": "cadeira",        "en": "chair",           "pron": "chér"},
    {"pt": "sofá",           "en": "sofa",            "pron": "sóufa"},
    {"pt": "poltrona",       "en": "armchair",        "pron": "ármchér"},
    {"pt": "armário",        "en": "cabinet",         "pron": "kébinet"},
    {"pt": "guarda-roupa",   "en": "wardrobe",        "pron": "uórdroub"},
    {"pt": "estante",        "en": "shelf",           "pron": "shelf"},
    {"pt": "gaveta",         "en": "drawer",          "pron": "dróer"},
    {"pt": "escrivaninha",   "en": "desk",            "pron": "désk"},
    {"pt": "banco",          "en": "stool",           "pron": "stúl"},
    {"pt": "berço",          "en": "crib",            "pron": "kríb"},
    {"pt": "tapete",         "en": "carpet",          "pron": "kárpit"},
    {"pt": "cortina",        "en": "curtain",         "pron": "kérten"},
    {"pt": "quadro",         "en": "picture",         "pron": "píkcher"},
    {"pt": "espelho",        "en": "mirror",          "pron": "míror"},
    {"pt": "vaso",           "en": "vase",            "pron": "véis"},

    # Eletrodomésticos
    {"pt": "geladeira",      "en": "refrigerator",    "pron": "rifrídjareitor"},
    {"pt": "freezer",        "en": "freezer",         "pron": "frízer"},
    {"pt": "fogão",          "en": "stove",           "pron": "stôuv"},
    {"pt": "forno",          "en": "oven",            "pron": "áven"},
    {"pt": "micro-ondas",    "en": "microwave",       "pron": "máicro-uéiv"},
    {"pt": "máquina de lavar","en": "washing machine","pron": "uóshing mashín"},
    {"pt": "lava-louças",    "en": "dishwasher",      "pron": "díshuóshe"},
    {"pt": "aspirador",      "en": "vacuum cleaner",  "pron": "vékium klíner"},
    {"pt": "liquidificador", "en": "blender",         "pron": "blénder"},
    {"pt": "torradeira",     "en": "toaster",         "pron": "tôuster"},
    {"pt": "cafeteira",      "en": "coffee maker",    "pron": "cófi méiker"},

    # Banheiro
    {"pt": "pia",            "en": "sink",            "pron": "sínk"},
    {"pt": "chuveiro",       "en": "shower",          "pron": "sháuer"},
    {"pt": "banheira",       "en": "bathtub",         "pron": "béthtab"},
    {"pt": "vaso sanitário", "en": "toilet",          "pron": "tóilet"},
    {"pt": "toalha",         "en": "towel",           "pron": "táuel"},
    {"pt": "sabão",          "en": "soap",            "pron": "sôup"},
    {"pt": "shampoo",        "en": "shampoo",         "pron": "shémpu"},
    {"pt": "condicionador",  "en": "conditioner",     "pron": "kondíshoner"},
    {"pt": "escova de dente","en": "toothbrush",      "pron": "túthbrash"},
    {"pt": "pasta de dente", "en": "toothpaste",      "pron": "túthpeist"},
    {"pt": "papel higiênico","en": "toilet paper",    "pron": "tóilet péiper"},
    {"pt": "pente",          "en": "comb",            "pron": "kôum"},
    {"pt": "escova de cabelo","en": "hairbrush",      "pron": "rérbrash"},

    # Quarto
    {"pt": "travesseiro",    "en": "pillow",          "pron": "pílou"},
    {"pt": "lençol",         "en": "sheet",           "pron": "shít"},
    {"pt": "cobertor",       "en": "blanket",         "pron": "blénkit"},
    {"pt": "edredom",        "en": "duvet",           "pron": "duvéi"},
    {"pt": "colchão",        "en": "mattress",        "pron": "métres"},
    {"pt": "abajur",         "en": "lamp",            "pron": "lémp"},
    {"pt": "despertador",    "en": "alarm clock",     "pron": "alárm klók"},

    # Objetos
    {"pt": "lâmpada",        "en": "light bulb",      "pron": "láit balb"},
    {"pt": "luz",            "en": "light",           "pron": "láit"},
    {"pt": "ventilador",     "en": "fan",             "pron": "fén"},
    {"pt": "ar-condicionado","en": "air conditioner", "pron": "ér kondíshoner"},
    {"pt": "televisão",      "en": "television",      "pron": "télevíjan"},
    {"pt": "relógio",        "en": "clock",           "pron": "klók"},
    {"pt": "chave",          "en": "key",             "pron": "kí"},
    {"pt": "livro",          "en": "book",            "pron": "búk"},
    {"pt": "caneta",         "en": "pen",             "pron": "pén"},
    {"pt": "lápis",          "en": "pencil",          "pron": "pénsol"},
    {"pt": "papel",          "en": "paper",           "pron": "péiper"},
    {"pt": "celular",        "en": "cell phone",      "pron": "sél fôun"},
    {"pt": "computador",     "en": "computer",        "pron": "kompiúter"},
    {"pt": "lixo",           "en": "trash",           "pron": "trésh"},
    {"pt": "lixeira",        "en": "trash can",       "pron": "trésh kén"},
    {"pt": "vassoura",       "en": "broom",           "pron": "brúm"},
    {"pt": "rodo",           "en": "mop",             "pron": "móp"},
    {"pt": "balde",          "en": "bucket",          "pron": "bákit"},
    {"pt": "escada de mão",  "en": "ladder",          "pron": "léder"},
    {"pt": "ferramenta",     "en": "tool",            "pron": "túl"},
    {"pt": "martelo",        "en": "hammer",          "pron": "rémer"},
    {"pt": "chave de fenda", "en": "screwdriver",     "pron": "skrúdráiver"},
    {"pt": "parafuso",       "en": "screw",           "pron": "skrú"},
    {"pt": "prego",          "en": "nail",            "pron": "néil"},

    # Frases úteis
    {"pt": "estou em casa",     "en": "I'm at home",         "pron": "áim ét rôum"},
    {"pt": "vou pra casa",      "en": "I'm going home",      "pron": "áim góuing rôum"},
    {"pt": "abra a porta",      "en": "open the door",       "pron": "ôupen de dór"},
    {"pt": "feche a janela",    "en": "close the window",    "pron": "klôuz de uíndou"},
    {"pt": "apague a luz",      "en": "turn off the light",  "pron": "térn óf de láit"},
    {"pt": "acenda a luz",      "en": "turn on the light",   "pron": "térn ón de láit"},
    {"pt": "onde é o banheiro?","en": "where is the bathroom?","pron": "uér is de béthrum"},
    {"pt": "estou limpando",    "en": "I'm cleaning",        "pron": "áim klíning"},
    {"pt": "estou cozinhando",  "en": "I'm cooking",         "pron": "áim kúking"},
    {"pt": "estou dormindo",    "en": "I'm sleeping",        "pron": "áim slíping"},
]

# ============ 👕 ROUPAS (80 itens) ============
roupas = [
    # Parte de cima
    {"pt": "camisa",         "en": "shirt",          "pron": "shért"},
    {"pt": "camiseta",       "en": "t-shirt",        "pron": "tíshért"},
    {"pt": "camisa social",  "en": "dress shirt",    "pron": "drés shért"},
    {"pt": "blusa",          "en": "blouse",         "pron": "bláus"},
    {"pt": "suéter",         "en": "sweater",        "pron": "suéter"},
    {"pt": "moletom",        "en": "hoodie",         "pron": "rúdi"},
    {"pt": "jaqueta",        "en": "jacket",         "pron": "djékit"},
    {"pt": "casaco",         "en": "coat",           "pron": "kôut"},
    {"pt": "sobretudo",      "en": "overcoat",       "pron": "ôuverkôut"},
    {"pt": "colete",         "en": "vest",           "pron": "vést"},
    {"pt": "polo",           "en": "polo shirt",     "pron": "pôulou shért"},
    {"pt": "regata",         "en": "tank top",       "pron": "ténk tóp"},
    {"pt": "top",            "en": "crop top",       "pron": "króp tóp"},

    # Parte de baixo
    {"pt": "calça",          "en": "pants",          "pron": "pénts"},
    {"pt": "jeans",          "en": "jeans",          "pron": "djins"},
    {"pt": "calça de moletom","en": "sweatpants",    "pron": "suétpénts"},
    {"pt": "bermuda",        "en": "shorts",         "pron": "shórts"},
    {"pt": "short",          "en": "short shorts",   "pron": "shórt shórts"},
    {"pt": "saia",           "en": "skirt",          "pron": "skért"},
    {"pt": "saia longa",     "en": "long skirt",     "pron": "long skért"},
    {"pt": "vestido",        "en": "dress",          "pron": "drés"},
    {"pt": "vestido longo",  "en": "long dress",     "pron": "long drés"},
    {"pt": "macacão",        "en": "jumpsuit",       "pron": "djámpsut"},
    {"pt": "terno",          "en": "suit",           "pron": "sút"},
    {"pt": "smoking",        "en": "tuxedo",         "pron": "taksídou"},
    {"pt": "uniforme",       "en": "uniform",        "pron": "iúniform"},
    {"pt": "pijama",         "en": "pajamas",        "pron": "pajámas"},

    # Íntimas
    {"pt": "cueca",          "en": "underwear",      "pron": "ánderuér"},
    {"pt": "cueca boxer",    "en": "boxers",         "pron": "bóksers"},
    {"pt": "calcinha",       "en": "panties",        "pron": "péntis"},
    {"pt": "sutiã",          "en": "bra",            "pron": "brá"},
    {"pt": "meia",           "en": "sock",           "pron": "sók"},
    {"pt": "meia-calça",     "en": "tights",         "pron": "táits"},

    # Calçados
    {"pt": "sapato",         "en": "shoe",           "pron": "shú"},
    {"pt": "sapato social",  "en": "dress shoe",     "pron": "drés shú"},
    {"pt": "tênis",          "en": "sneakers",       "pron": "sníkers"},
    {"pt": "sandália",       "en": "sandal",         "pron": "séndal"},
    {"pt": "chinelo",        "en": "flip-flop",      "pron": "flíp flóp"},
    {"pt": "bota",           "en": "boot",           "pron": "bút"},
    {"pt": "salto alto",     "en": "high heels",     "pron": "rái ríls"},
    {"pt": "sapatilha",      "en": "flat shoe",      "pron": "flét shú"},

    # Acessórios
    {"pt": "chapéu",         "en": "hat",            "pron": "rét"},
    {"pt": "boné",           "en": "cap",            "pron": "kép"},
    {"pt": "gorro",          "en": "beanie",         "pron": "bíni"},
    {"pt": "cachecol",       "en": "scarf",          "pron": "skárf"},
    {"pt": "luva",           "en": "glove",          "pron": "gláv"},
    {"pt": "cinto",          "en": "belt",           "pron": "bélt"},
    {"pt": "gravata",        "en": "tie",            "pron": "tái"},
    {"pt": "laço",           "en": "bow",            "pron": "bôu"},
    {"pt": "óculos",         "en": "glasses",        "pron": "gléses"},
    {"pt": "óculos de sol",  "en": "sunglasses",     "pron": "sángléses"},
    {"pt": "lente de contato","en": "contact lens",  "pron": "kóntekt léns"},
    {"pt": "bolsa",          "en": "bag",            "pron": "bég"},
    {"pt": "bolsa de mão",   "en": "handbag",        "pron": "réndbeg"},
    {"pt": "mochila",        "en": "backpack",       "pron": "békpék"},
    {"pt": "mala",           "en": "suitcase",       "pron": "sútkeis"},
    {"pt": "carteira",       "en": "wallet",         "pron": "uólet"},
    {"pt": "guarda-chuva",   "en": "umbrella",       "pron": "ambréla"},

    # Joias
    {"pt": "joia",           "en": "jewelry",        "pron": "djúelri"},
    {"pt": "anel",           "en": "ring",           "pron": "ríng"},
    {"pt": "aliança",        "en": "wedding ring",   "pron": "uéding ríng"},
    {"pt": "colar",          "en": "necklace",       "pron": "néklis"},
    {"pt": "brinco",         "en": "earring",        "pron": "íring"},
    {"pt": "pulseira",       "en": "bracelet",       "pron": "bréslet"},
    {"pt": "relógio",        "en": "watch",          "pron": "uóch"},
    {"pt": "corrente",       "en": "chain",          "pron": "chéin"},

    # Praia/piscina
    {"pt": "biquíni",        "en": "bikini",         "pron": "bikíni"},
    {"pt": "maiô",           "en": "swimsuit",       "pron": "suímsut"},
    {"pt": "sunga",          "en": "swim trunks",    "pron": "suím tránks"},
    {"pt": "toalha de praia","en": "beach towel",    "pron": "bích táuel"},

    # Materiais/cores
    {"pt": "algodão",        "en": "cotton",         "pron": "kóton"},
    {"pt": "seda",           "en": "silk",           "pron": "sílk"},
    {"pt": "lã",             "en": "wool",           "pron": "uúl"},
    {"pt": "couro",          "en": "leather",        "pron": "léder"},
    {"pt": "sintético",      "en": "synthetic",      "pron": "sinthétik"},
    {"pt": "estampado",      "en": "patterned",      "pron": "péterned"},
    {"pt": "liso",           "en": "plain",          "pron": "pléin"},
    {"pt": "listrado",       "en": "striped",        "pron": "stráipt"},

    # Frases
    {"pt": "estou vestindo",     "en": "I'm wearing",        "pron": "áim uérin"},
    {"pt": "vou trocar de roupa","en": "I'll change clothes","pron": "áil chéindj klôudz"},
    {"pt": "esta roupa serve?",  "en": "does this fit?",     "pron": "dáz dis fít"},
    {"pt": "é muito apertado",   "en": "it's too tight",     "pron": "its tú táit"},
    {"pt": "é muito largo",      "en": "it's too loose",     "pron": "its tú lús"},
    {"pt": "tamanho P",          "en": "size S",             "pron": "sáiz és"},
    {"pt": "tamanho M",          "en": "size M",             "pron": "sáiz ém"},
    {"pt": "tamanho G",          "en": "size L",             "pron": "sáiz él"},
]

# ============ 🐶 ANIMAIS (100 itens) ============
animais = [
    # Domésticos
    {"pt": "cachorro",      "en": "dog",            "pron": "dóg"},
    {"pt": "gato",          "en": "cat",            "pron": "két"},
    {"pt": "pássaro",       "en": "bird",           "pron": "bérd"},
    {"pt": "peixe",         "en": "fish",           "pron": "físh"},
    {"pt": "hamster",       "en": "hamster",        "pron": "rémester"},
    {"pt": "coelho",        "en": "rabbit",         "pron": "rébit"},
    {"pt": "papagaio",      "en": "parrot",         "pron": "pérot"},
    {"pt": "tartaruga",     "en": "turtle",         "pron": "tértol"},
    {"pt": "porquinho-da-índia","en": "guinea pig", "pron": "guíni píg"},

    # Fazenda
    {"pt": "cavalo",        "en": "horse",          "pron": "rórs"},
    {"pt": "vaca",          "en": "cow",            "pron": "káu"},
    {"pt": "boi",           "en": "bull",           "pron": "búl"},
    {"pt": "bezerro",       "en": "calf",           "pron": "kéf"},
    {"pt": "porco",         "en": "pig",            "pron": "píg"},
    {"pt": "ovelha",        "en": "sheep",          "pron": "shíp"},
    {"pt": "cordeiro",      "en": "lamb",           "pron": "lém"},
    {"pt": "cabra",         "en": "goat",           "pron": "gôut"},
    {"pt": "galinha",       "en": "chicken",        "pron": "chíken"},
    {"pt": "galo",          "en": "rooster",        "pron": "rúster"},
    {"pt": "pintinho",      "en": "chick",          "pron": "chík"},
    {"pt": "pato",          "en": "duck",           "pron": "dák"},
    {"pt": "ganso",         "en": "goose",          "pron": "gús"},
    {"pt": "peru",          "en": "turkey",         "pron": "térki"},
    {"pt": "burro",         "en": "donkey",         "pron": "dónki"},
    {"pt": "mula",          "en": "mule",           "pron": "miúl"},

    # Selvagens - mamíferos
    {"pt": "leão",          "en": "lion",           "pron": "láion"},
    {"pt": "leoa",          "en": "lioness",        "pron": "láiones"},
    {"pt": "tigre",         "en": "tiger",          "pron": "táiger"},
    {"pt": "elefante",      "en": "elephant",       "pron": "élefant"},
    {"pt": "macaco",        "en": "monkey",         "pron": "mánki"},
    {"pt": "gorila",        "en": "gorilla",        "pron": "goríla"},
    {"pt": "urso",          "en": "bear",           "pron": "bér"},
    {"pt": "lobo",          "en": "wolf",           "pron": "uólf"},
    {"pt": "raposa",        "en": "fox",            "pron": "fóks"},
    {"pt": "cervo",         "en": "deer",           "pron": "dír"},
    {"pt": "esquilo",       "en": "squirrel",       "pron": "skuírel"},
    {"pt": "morcego",       "en": "bat",            "pron": "bét"},
    {"pt": "rato",          "en": "mouse",          "pron": "máus"},
    {"pt": "ratazana",      "en": "rat",            "pron": "rét"},
    {"pt": "coala",         "en": "koala",          "pron": "koála"},
    {"pt": "panda",         "en": "panda",          "pron": "pénda"},
    {"pt": "girafa",        "en": "giraffe",        "pron": "djiréf"},
    {"pt": "zebra",         "en": "zebra",          "pron": "zíbra"},
    {"pt": "rinoceronte",   "en": "rhino",          "pron": "ráinou"},
    {"pt": "hipopótamo",    "en": "hippo",          "pron": "rípou"},
    {"pt": "camelo",        "en": "camel",          "pron": "kémel"},
    {"pt": "lontra",        "en": "otter",          "pron": "óter"},
    {"pt": "foca",          "en": "seal",           "pron": "síl"},
    {"pt": "baleia",        "en": "whale",          "pron": "uêil"},
    {"pt": "golfinho",      "en": "dolphin",        "pron": "dólfin"},
    {"pt": "tubarão",       "en": "shark",          "pron": "shárk"},

    # Répteis e anfíbios
    {"pt": "cobra",         "en": "snake",          "pron": "snéik"},
    {"pt": "lagarto",       "en": "lizard",         "pron": "lísard"},
    {"pt": "jacaré",        "en": "alligator",      "pron": "éligueitor"},
    {"pt": "crocodilo",     "en": "crocodile",      "pron": "krókodail"},
    {"pt": "sapo",          "en": "frog",           "pron": "frógu"},
    {"pt": "rã",            "en": "frog",           "pron": "frógu"},
    {"pt": "camaleão",      "en": "chameleon",      "pron": "kamilion"},

    # Aves
    {"pt": "águia",         "en": "eagle",          "pron": "ígol"},
    {"pt": "coruja",        "en": "owl",            "pron": "ául"},
    {"pt": "falção",        "en": "falcon",         "pron": "félkon"},
    {"pt": "pombo",         "en": "pigeon",         "pron": "pídjon"},
    {"pt": "gaivota",       "en": "seagull",        "pron": "sígol"},
    {"pt": "pinguim",       "en": "penguin",        "pron": "pénguin"},
    {"pt": "avestruz",      "en": "ostrich",        "pron": "óstrich"},
    {"pt": "flamingo",      "en": "flamingo",       "pron": "flamíngou"},
    {"pt": "tucano",        "en": "toucan",         "pron": "túken"},
    {"pt": "beija-flor",    "en": "hummingbird",    "pron": "rámingbérd"},

    # Insetos
    {"pt": "aranha",        "en": "spider",         "pron": "spáider"},
    {"pt": "abelha",        "en": "bee",            "pron": "bí"},
    {"pt": "borboleta",     "en": "butterfly",      "pron": "báterflai"},
    {"pt": "formiga",       "en": "ant",            "pron": "ént"},
    {"pt": "mosquito",      "en": "mosquito",       "pron": "maskítou"},
    {"pt": "mosca",         "en": "fly",            "pron": "flái"},
    {"pt": "barata",        "en": "cockroach",      "pron": "kókrouch"},
    {"pt": "besouro",       "en": "beetle",         "pron": "bítol"},
    {"pt": "grilo",         "en": "cricket",        "pron": "kríket"},
    {"pt": "escorpião",     "en": "scorpion",       "pron": "skórpion"},
    {"pt": "caracol",       "en": "snail",          "pron": "snéil"},
    {"pt": "minhoca",       "en": "worm",           "pron": "uórm"},
    {"pt": "lagarta",       "en": "caterpillar",    "pron": "kéterpiler"},

    # Sons dos animais
    {"pt": "o cachorro late",  "en": "the dog barks",   "pron": "de dóg bárks"},
    {"pt": "o gato mia",       "en": "the cat meows",   "pron": "de két miáus"},
    {"pt": "a vaca muge",      "en": "the cow moos",    "pron": "de káu mús"},
    {"pt": "o cavalo relincha","en": "the horse neighs","pron": "de rórs néis"},
    {"pt": "o galo canta",     "en": "the rooster crows","pron": "de rúster krôus"},
    {"pt": "o pássaro canta",  "en": "the bird sings",  "pron": "de bérd síngs"},
    {"pt": "o lobo uiva",      "en": "the wolf howls",  "pron": "de uólf ráuls"},
    {"pt": "a abelha zumbe",   "en": "the bee buzzes",  "pron": "de bí bázes"},

    # Frases
    {"pt": "eu tenho um cachorro","en": "I have a dog",    "pron": "ái rév e dóg"},
    {"pt": "eu gosto de gatos",   "en": "I like cats",     "pron": "ái láik kéts"},
    {"pt": "tenho medo de cobra", "en": "I'm afraid of snakes","pron": "áim afréid óv snéiks"},
    {"pt": "que animal é esse?",  "en": "what animal is this?","pron": "uóténimal is dis"},
    {"pt": "é perigoso?",         "en": "is it dangerous?", "pron": "is it déindjeros"},
    {"pt": "é de estimação",      "en": "it's a pet",      "pron": "its e pét"},
    {"pt": "animal selvagem",     "en": "wild animal",     "pron": "uáild énumal"},
    {"pt": "no zoológico",        "en": "at the zoo",      "pron": "ét de zú"},
]

# ============ 🌦️ CLIMA E NATUREZA (85 itens) ============
clima = [
    # Céu e astros
    {"pt": "sol",            "en": "sun",             "pron": "sán"},
    {"pt": "lua",            "en": "moon",            "pron": "mún"},
    {"pt": "estrela",        "en": "star",            "pron": "stár"},
    {"pt": "céu",            "en": "sky",             "pron": "skáí"},
    {"pt": "planeta",        "en": "planet",          "pron": "plénet"},
    {"pt": "Terra",          "en": "Earth",           "pron": "érth"},
    {"pt": "nuvem",          "en": "cloud",           "pron": "kláud"},
    {"pt": "espaço",         "en": "space",           "pron": "spéis"},

    # Clima
    {"pt": "chuva",          "en": "rain",            "pron": "réin"},
    {"pt": "neve",           "en": "snow",            "pron": "snôu"},
    {"pt": "vento",          "en": "wind",            "pron": "uínd"},
    {"pt": "tempestade",     "en": "storm",           "pron": "stórm"},
    {"pt": "trovão",         "en": "thunder",         "pron": "thánder"},
    {"pt": "relâmpago",      "en": "lightning",       "pron": "láithning"},
    {"pt": "arco-íris",      "en": "rainbow",         "pron": "réinbou"},
    {"pt": "neblina",        "en": "fog",             "pron": "fóg"},
    {"pt": "orvalho",        "en": "dew",             "pron": "diú"},
    {"pt": "granizo",        "en": "hail",            "pron": "réil"},
    {"pt": "tornado",        "en": "tornado",         "pron": "tornéidou"},
    {"pt": "furacão",        "en": "hurricane",       "pron": "rárikein"},
    {"pt": "terremoto",      "en": "earthquake",      "pron": "érthkuéik"},
    {"pt": "enchente",       "en": "flood",           "pron": "flád"},

    # Temperatura
    {"pt": "calor",          "en": "heat",            "pron": "rít"},
    {"pt": "frio",           "en": "cold",            "pron": "kôuld"},
    {"pt": "morno",          "en": "warm",            "pron": "uórm"},
    {"pt": "fresco",         "en": "cool",            "pron": "kúl"},
    {"pt": "úmido",          "en": "humid",           "pron": "riúmid"},
    {"pt": "seco",           "en": "dry",             "pron": "drái"},

    # Estações
    {"pt": "primavera",      "en": "spring",          "pron": "spríng"},
    {"pt": "verão",          "en": "summer",          "pron": "sámer"},
    {"pt": "outono",         "en": "autumn",          "pron": "ótom"},
    {"pt": "inverno",        "en": "winter",          "pron": "uínter"},

    # Plantas
    {"pt": "árvore",         "en": "tree",            "pron": "trí"},
    {"pt": "flor",           "en": "flower",          "pron": "fláuer"},
    {"pt": "folha",          "en": "leaf",            "pron": "líf"},
    {"pt": "grama",          "en": "grass",           "pron": "grés"},
    {"pt": "semente",        "en": "seed",            "pron": "síd"},
    {"pt": "raiz",           "en": "root",            "pron": "rút"},
    {"pt": "tronco",         "en": "trunk",           "pron": "tránk"},
    {"pt": "galho",          "en": "branch",          "pron": "brénch"},
    {"pt": "rosa",           "en": "rose",            "pron": "rôus"},
    {"pt": "girassol",       "en": "sunflower",       "pron": "sánfláuer"},
    {"pt": "margarida",      "en": "daisy",           "pron": "déizi"},
    {"pt": "tulipa",         "en": "tulip",           "pron": "túlip"},
    {"pt": "orquídea",       "en": "orchid",          "pron": "órkid"},
    {"pt": "palmeira",       "en": "palm tree",       "pron": "pám trí"},

    # Geografia
    {"pt": "montanha",       "en": "mountain",        "pron": "máunten"},
    {"pt": "rio",            "en": "river",           "pron": "ríver"},
    {"pt": "mar",            "en": "sea",             "pron": "sí"},
    {"pt": "oceano",         "en": "ocean",           "pron": "ôushan"},
    {"pt": "praia",          "en": "beach",           "pron": "bích"},
    {"pt": "ilha",           "en": "island",          "pron": "áiland"},
    {"pt": "lago",           "en": "lake",            "pron": "léik"},
    {"pt": "lagoa",          "en": "lagoon",          "pron": "lagún"},
    {"pt": "floresta",       "en": "forest",          "pron": "fórest"},
    {"pt": "selva",          "en": "jungle",          "pron": "djángol"},
    {"pt": "deserto",        "en": "desert",          "pron": "dézert"},
    {"pt": "caverna",        "en": "cave",            "pron": "kéiv"},
    {"pt": "cachoeira",      "en": "waterfall",       "pron": "uóterfól"},
    {"pt": "vulcão",         "en": "volcano",         "pron": "volkéinou"},
    {"pt": "vale",           "en": "valley",          "pron": "véli"},
    {"pt": "campo",          "en": "field",           "pron": "fíld"},
    {"pt": "fazenda",        "en": "farm",            "pron": "fárm"},
    {"pt": "cidade",         "en": "city",            "pron": "síti"},
    {"pt": "país",           "en": "country",         "pron": "kántri"},

    # Elementos
    {"pt": "terra",          "en": "earth",           "pron": "érth"},
    {"pt": "fogo",           "en": "fire",            "pron": "fáier"},
    {"pt": "água",           "en": "water",           "pron": "uóter"},
    {"pt": "ar",             "en": "air",             "pron": "ér"},
    {"pt": "pedra",          "en": "stone",           "pron": "stôun"},
    {"pt": "areia",          "en": "sand",            "pron": "sénd"},
    {"pt": "lama",           "en": "mud",             "pron": "mád"},
    {"pt": "gelo",           "en": "ice",             "pron": "áis"},
    {"pt": "poeira",         "en": "dust",            "pron": "dást"},
    {"pt": "metal",          "en": "metal",           "pron": "métal"},
    {"pt": "madeira",        "en": "wood",            "pron": "uúd"},

    # Frases
    {"pt": "como está o tempo?",   "en": "how is the weather?","pron": "ráu is de uéder"},
    {"pt": "está chovendo",        "en": "it's raining",      "pron": "its réining"},
    {"pt": "está nevando",         "en": "it's snowing",      "pron": "its snôuing"},
    {"pt": "está quente",          "en": "it's hot",          "pron": "its rót"},
    {"pt": "está frio",            "en": "it's cold",         "pron": "its kôuld"},
    {"pt": "está nublado",         "en": "it's cloudy",       "pron": "its kláudi"},
    {"pt": "está ensolarado",      "en": "it's sunny",        "pron": "its sáni"},
    {"pt": "está ventando",        "en": "it's windy",        "pron": "its uíndi"},
    {"pt": "vai chover amanhã?",   "en": "will it rain tomorrow?","pron": "uíl it réin tumórou"},
    {"pt": "que dia lindo!",       "en": "what a beautiful day!","pron": "uót e biútiful déi"},
]

# ============ 🚗 TRANSPORTE (85 itens) ============
transporte = [
    # Veículos
    {"pt": "carro",          "en": "car",            "pron": "kár"},
    {"pt": "moto",           "en": "motorcycle",     "pron": "móutorsaicol"},
    {"pt": "bicicleta",      "en": "bicycle",        "pron": "báisikol"},
    {"pt": "ônibus",         "en": "bus",            "pron": "bás"},
    {"pt": "metrô",          "en": "subway",         "pron": "sábuei"},
    {"pt": "trem",           "en": "train",          "pron": "tréin"},
    {"pt": "avião",          "en": "airplane",       "pron": "érplein"},
    {"pt": "helicóptero",    "en": "helicopter",     "pron": "rélikopter"},
    {"pt": "navio",          "en": "ship",           "pron": "shíp"},
    {"pt": "barco",          "en": "boat",           "pron": "bôut"},
    {"pt": "táxi",           "en": "taxi",           "pron": "téksi"},
    {"pt": "caminhão",       "en": "truck",          "pron": "trák"},
    {"pt": "van",            "en": "van",            "pron": "vén"},
    {"pt": "patinete",       "en": "scooter",        "pron": "skúter"},
    {"pt": "skate",          "en": "skateboard",     "pron": "skéitbord"},
    {"pt": "ônibus escolar", "en": "school bus",     "pron": "skúl bás"},
    {"pt": "ambulância",     "en": "ambulance",      "pron": "émbiulans"},
    {"pt": "carro de polícia","en": "police car",    "pron": "polís kár"},
    {"pt": "caminhão de bombeiro","en": "fire truck","pron": "fáier trák"},
    {"pt": "trator",         "en": "tractor",        "pron": "tréktor"},
    {"pt": "limusine",       "en": "limousine",      "pron": "límoziin"},
    {"pt": "fogão",          "en": "rocket",         "pron": "rókit"},

    # Lugares
    {"pt": "estrada",        "en": "road",           "pron": "rôud"},
    {"pt": "rua",            "en": "street",         "pron": "strít"},
    {"pt": "avenida",        "en": "avenue",         "pron": "évenu"},
    {"pt": "calçada",        "en": "sidewalk",       "pron": "sáiduók"},
    {"pt": "semáforo",       "en": "traffic light",  "pron": "tréfik láit"},
    {"pt": "faixa de pedestre","en": "crosswalk",    "pron": "krósuók"},
    {"pt": "placa",          "en": "sign",           "pron": "sáin"},
    {"pt": "posto de gasolina","en": "gas station",  "pron": "gués stéishon"},
    {"pt": "estacionamento", "en": "parking lot",    "pron": "párking lót"},
    {"pt": "garagem",        "en": "garage",         "pron": "garáj"},
    {"pt": "pedágio",        "en": "toll",           "pron": "tôul"},
    {"pt": "rodovia",        "en": "highway",        "pron": "ráiuei"},
    {"pt": "ponte",          "en": "bridge",         "pron": "brídj"},
    {"pt": "túnel",          "en": "tunnel",         "pron": "tánel"},
    {"pt": "esquina",        "en": "corner",         "pron": "kórner"},
    {"pt": "cruzamento",     "en": "intersection",   "pron": "intersékshon"},
    {"pt": "rotatória",      "en": "roundabout",     "pron": "ráundabáut"},
    {"pt": "beco",           "en": "alley",          "pron": "éli"},

    # Locais de transporte
    {"pt": "aeroporto",      "en": "airport",        "pron": "érport"},
    {"pt": "estação",        "en": "station",        "pron": "stéishon"},
    {"pt": "rodoviária",     "en": "bus station",    "pron": "bás stéishon"},
    {"pt": "porto",          "en": "port",           "pron": "pórt"},
    {"pt": "parada de ônibus","en": "bus stop",      "pron": "bás stóp"},
    {"pt": "ponto de táxi",  "en": "taxi stand",     "pron": "téksi sténd"},
    {"pt": "estação de metrô","en": "subway station","pron": "sábuei stéishon"},
    {"pt": "terminal",       "en": "terminal",       "pron": "términol"},

    # Partes do veículo
    {"pt": "volante",        "en": "steering wheel", "pron": "stíring uíl"},
    {"pt": "freio",          "en": "brake",          "pron": "bréik"},
    {"pt": "acelerador",     "en": "accelerator",    "pron": "ekséleréitor"},
    {"pt": "embreagem",      "en": "clutch",         "pron": "klách"},
    {"pt": "pneu",           "en": "tire",           "pron": "táier"},
    {"pt": "roda",           "en": "wheel",          "pron": "uíl"},
    {"pt": "farol",          "en": "headlight",      "pron": "rédlait"},
    {"pt": "lanterna",       "en": "taillight",      "pron": "téillait"},
    {"pt": "espelho retrovisor","en": "rearview mirror","pron": "rírviu míror"},
    {"pt": "porta-malas",    "en": "trunk",          "pron": "tránk"},
    {"pt": "capô",           "en": "hood",           "pron": "rúd"},
    {"pt": "para-brisa",     "en": "windshield",     "pron": "uíndshild"},
    {"pt": "limpador de para-brisa","en": "wiper",   "pron": "uáiper"},
    {"pt": "buzina",         "en": "horn",           "pron": "rórn"},
    {"pt": "cinto de segurança","en": "seatbelt",    "pron": "sítbelt"},
    {"pt": "airbag",         "en": "airbag",         "pron": "érbeg"},
    {"pt": "gasolina",       "en": "gasoline",       "pron": "guésolin"},
    {"pt": "álcool",         "en": "ethanol",        "pron": "éthanol"},
    {"pt": "diesel",         "en": "diesel",         "pron": "dízel"},
    {"pt": "elétrico",       "en": "electric",       "pron": "eléktrik"},
    {"pt": "bateria",        "en": "battery",        "pron": "béteri"},

    # Ações
    {"pt": "dirigir",        "en": "to drive",       "pron": "tu dráiv"},
    {"pt": "estacionar",     "en": "to park",        "pron": "tu párk"},
    {"pt": "acelerar",       "en": "to accelerate",  "pron": "tu ekséleréit"},
    {"pt": "frear",          "en": "to brake",       "pron": "tu bréik"},
    {"pt": "virar",          "en": "to turn",        "pron": "tu térn"},
    {"pt": "ultrapassar",    "en": "to overtake",    "pron": "tu ôuverteik"},
    {"pt": "buzinar",        "en": "to honk",        "pron": "tu rónk"},
    {"pt": "abastecer",      "en": "to refuel",      "pron": "tu rifíul"},
    {"pt": "pegar um táxi",  "en": "to take a taxi", "pron": "tu téik e téksi"},
    {"pt": "pegar o ônibus", "en": "to take the bus","pron": "tu téik de bás"},
    {"pt": "perder o trem",  "en": "to miss the train","pron": "tu mís de tréin"},
    {"pt": "comprar passagem","en": "to buy a ticket","pron": "tu bái e tíkit"},

    # Frases
    {"pt": "onde é a estação?",    "en": "where is the station?","pron": "uér is de stéishon"},
    {"pt": "quanto custa a passagem?","en": "how much is the ticket?","pron": "ráu mách is de tíkit"},
    {"pt": "que horas sai o ônibus?","en": "what time does the bus leave?","pron": "uót táim dáz de bás lív"},
    {"pt": "estou atrasado",       "en": "I'm late",           "pron": "áim léit"},
    {"pt": "perdi o ônibus",       "en": "I missed the bus",   "pron": "ái míst de bás"},
    {"pt": "estou perdido",        "en": "I'm lost",           "pron": "áim lóst"},
    {"pt": "quanto tempo demora?", "en": "how long does it take?","pron": "ráu long dáz it téik"},
    {"pt": "me leve para...",      "en": "take me to...",      "pron": "téik mi tu"},
    {"pt": "pare aqui",            "en": "stop here",          "pron": "stóp rír"},
    {"pt": "vou de carro",         "en": "I'm going by car",   "pron": "áim góuing bái kár"},
]

# ============ 🧭 DIREÇÕES (80 itens) ============
direcoes = [
    # Básicas
    {"pt": "esquerda",       "en": "left",           "pron": "léft"},
    {"pt": "direita",        "en": "right",          "pron": "ráit"},
    {"pt": "reto",           "en": "straight",       "pron": "stréit"},
    {"pt": "para frente",    "en": "forward",        "pron": "fórward"},
    {"pt": "para trás",      "en": "backward",       "pron": "békuerd"},
    {"pt": "de lado",        "en": "sideways",       "pron": "sáidueis"},
    {"pt": "em círculo",     "en": "in a circle",    "pron": "in e sérkol"},

    # Posição
    {"pt": "acima",          "en": "above",          "pron": "abáv"},
    {"pt": "abaixo",         "en": "below",          "pron": "bilôu"},
    {"pt": "em cima",        "en": "on top",         "pron": "ón tóp"},
    {"pt": "embaixo",        "en": "under",          "pron": "ánder"},
    {"pt": "dentro",         "en": "inside",         "pron": "insáid"},
    {"pt": "fora",           "en": "outside",        "pron": "áutsáid"},
    {"pt": "à frente",       "en": "ahead",          "pron": "aréd"},
    {"pt": "atrás",          "en": "behind",         "pron": "birráind"},
    {"pt": "ao lado",        "en": "beside",         "pron": "bissáid"},
    {"pt": "entre",          "en": "between",        "pron": "bituín"},
    {"pt": "do lado direito","en": "on the right",   "pron": "ón de ráit"},
    {"pt": "do lado esquerdo","en": "on the left",   "pron": "ón de léft"},
    {"pt": "no meio",        "en": "in the middle",  "pron": "in de mídol"},
    {"pt": "ao redor",       "en": "around",         "pron": "aráund"},

    # Distância
    {"pt": "perto",          "en": "near",           "pron": "nír"},
    {"pt": "longe",          "en": "far",            "pron": "fár"},
    {"pt": "aqui",           "en": "here",           "pron": "rír"},
    {"pt": "ali",            "en": "there",          "pron": "dér"},
    {"pt": "lá",             "en": "over there",     "pron": "ôuver dér"},
    {"pt": "em todo lugar",  "en": "everywhere",     "pron": "évriuer"},
    {"pt": "em algum lugar", "en": "somewhere",      "pron": "sámuer"},
    {"pt": "em lugar nenhum","en": "nowhere",        "pron": "nôuuer"},
    {"pt": "mais perto",     "en": "closer",         "pron": "klôuzer"},
    {"pt": "mais longe",     "en": "farther",        "pron": "fárder"},

    # Pontos cardeais
    {"pt": "norte",          "en": "north",          "pron": "nórth"},
    {"pt": "sul",            "en": "south",          "pron": "sáuth"},
    {"pt": "leste",          "en": "east",           "pron": "íst"},
    {"pt": "oeste",          "en": "west",           "pron": "uést"},
    {"pt": "nordeste",       "en": "northeast",      "pron": "nórthíst"},
    {"pt": "noroeste",       "en": "northwest",      "pron": "nórthuést"},
    {"pt": "sudeste",        "en": "southeast",      "pron": "sáuthíst"},
    {"pt": "sudoeste",       "en": "southwest",      "pron": "sáuthuést"},
    {"pt": "norte verdadeiro","en": "true north",    "pron": "trú nórth"},

    # Ações de direção
    {"pt": "vire à esquerda","en": "turn left",      "pron": "térn léft"},
    {"pt": "vire à direita", "en": "turn right",     "pron": "térn ráit"},
    {"pt": "siga em frente", "en": "go straight",    "pron": "gôu stréit"},
    {"pt": "pare",           "en": "stop",           "pron": "stóp"},
    {"pt": "volte",          "en": "go back",        "pron": "gôu bék"},
    {"pt": "suba",           "en": "go up",          "pron": "gôu áp"},
    {"pt": "desça",          "en": "go down",        "pron": "gôu dáun"},
    {"pt": "entre",          "en": "come in",        "pron": "kám ín"},
    {"pt": "saia",           "en": "get out",        "pron": "guét áut"},
    {"pt": "atravesse",      "en": "cross",          "pron": "krós"},
    {"pt": "siga a placa",   "en": "follow the sign","pron": "fólou de sáin"},
    {"pt": "pegue a primeira rua","en": "take the first street","pron": "téik de férst strít"},
    {"pt": "pegue a segunda rua","en": "take the second street","pron": "téik de sékond strít"},
    {"pt": "é a última rua", "en": "it's the last street","pron": "its de lést strít"},
    {"pt": "na esquina",     "en": "at the corner",  "pron": "ét de kórner"},
    {"pt": "no final da rua","en": "at the end of the street","pron": "ét de énd óv de strít"},
    {"pt": "próxima quadra", "en": "next block",     "pron": "nékst blók"},

    # Ferramentas
    {"pt": "mapa",           "en": "map",            "pron": "mép"},
    {"pt": "GPS",            "en": "GPS",            "pron": "djipíés"},
    {"pt": "bússola",        "en": "compass",        "pron": "kámpas"},
    {"pt": "placa de rua",   "en": "street sign",    "pron": "strít sáin"},
    {"pt": "endereço",       "en": "address",        "pron": "édres"},

    # Frases
    {"pt": "onde fica...?",       "en": "where is...?",       "pron": "uér is"},
    {"pt": "como chego em...?",   "en": "how do I get to...?","pron": "ráu du ái guét tu"},
    {"pt": "estou perdido",       "en": "I'm lost",           "pron": "áim lóst"},
    {"pt": "pode me ajudar?",     "en": "can you help me?",   "pron": "kén iu rélp mi"},
    {"pt": "é longe daqui?",      "en": "is it far from here?","pron": "is it fár from rír"},
    {"pt": "é perto daqui?",      "en": "is it near here?",   "pron": "is it nír rír"},
    {"pt": "quanto tempo a pé?",  "en": "how long on foot?",  "pron": "ráu long ón fút"},
    {"pt": "estou indo pro norte","en": "I'm going north",    "pron": "áim góuing nórth"},
    {"pt": "siga reto por 2 km",  "en": "go straight for 2 km","pron": "gôu stréit fór tú kilomíters"},
    {"pt": "vire na próxima",     "en": "turn at the next",   "pron": "térn ét de nékst"},
]

# ============ ESCREVER ============
modulos = {
    "casa":       casa,
    "roupas":     roupas,
    "animais":    animais,
    "clima":      clima,
    "transporte": transporte,
    "direcoes":   direcoes,
}

for nome, dados in modulos.items():
    caminho = PASTA / f"{nome}.json"
    with open(caminho, "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=2)
    print(f"OK: {nome}.json ({len(dados)} itens)")

print()
print("=" * 50)
print("Lote 1 EXPANDIDO preenchido com sucesso!")
print("Reinicie o Streamlit pra ver o conteudo.")
print("=" * 50)