import json
from pathlib import Path

BASE = Path(__file__).parent
PASTA = BASE / "dados" / "ingles"

# ============ 🧑 CORPO HUMANO (200) ============
corpo = [
    # Cabeça
    {"pt": "cabeça",          "en": "head",          "pron": "réd"},
    {"pt": "cabelo",          "en": "hair",          "pron": "rér"},
    {"pt": "rosto",           "en": "face",          "pron": "féis"},
    {"pt": "testa",           "en": "forehead",      "pron": "fórréd"},
    {"pt": "olho",            "en": "eye",           "pron": "ái"},
    {"pt": "sobrancelha",     "en": "eyebrow",       "pron": "áibráu"},
    {"pt": "cílios",          "en": "eyelashes",     "pron": "áiléshes"},
    {"pt": "pálpebra",        "en": "eyelid",        "pron": "áilid"},
    {"pt": "nariz",           "en": "nose",          "pron": "nôuz"},
    {"pt": "boca",            "en": "mouth",         "pron": "máuth"},
    {"pt": "lábio",           "en": "lip",           "pron": "líp"},
    {"pt": "dente",           "en": "tooth",         "pron": "túth"},
    {"pt": "dentes",          "en": "teeth",         "pron": "títh"},
    {"pt": "língua",          "en": "tongue",        "pron": "táng"},
    {"pt": "gengiva",         "en": "gum",           "pron": "gám"},
    {"pt": "queixo",          "en": "chin",          "pron": "chín"},
    {"pt": "bochecha",        "en": "cheek",         "pron": "chík"},
    {"pt": "orelha",          "en": "ear",           "pron": "ír"},
    {"pt": "pescoço",         "en": "neck",          "pron": "nék"},
    {"pt": "garganta",        "en": "throat",        "pron": "thrôut"},

    # Tronco
    {"pt": "ombro",           "en": "shoulder",      "pron": "shôulder"},
    {"pt": "peito",           "en": "chest",         "pron": "chést"},
    {"pt": "seio",            "en": "breast",        "pron": "brést"},
    {"pt": "barriga",         "en": "belly",         "pron": "béli"},
    {"pt": "estômago",        "en": "stomach",       "pron": "stómak"},
    {"pt": "costas",          "en": "back",          "pron": "bék"},
    {"pt": "coluna",          "en": "spine",         "pron": "spáin"},
    {"pt": "cintura",         "en": "waist",         "pron": "uéist"},
    {"pt": "quadril",         "en": "hip",           "pron": "ríp"},
    {"pt": "lado",            "en": "side",          "pron": "sáid"},
    {"pt": "tórax",           "en": "torso",         "pron": "tórsou"},

    # Braços
    {"pt": "braço",           "en": "arm",           "pron": "árm"},
    {"pt": "cotovelo",        "en": "elbow",         "pron": "élbou"},
    {"pt": "antebraço",       "en": "forearm",       "pron": "fórarm"},
    {"pt": "pulso",           "en": "wrist",         "pron": "ríst"},
    {"pt": "mão",             "en": "hand",          "pron": "rénd"},
    {"pt": "palma",           "en": "palm",          "pron": "pám"},
    {"pt": "dedo",            "en": "finger",        "pron": "fínguer"},
    {"pt": "polegar",         "en": "thumb",         "pron": "thám"},
    {"pt": "indicador",       "en": "index finger",  "pron": "índeks fínguer"},
    {"pt": "dedo médio",      "en": "middle finger", "pron": "mídol fínguer"},
    {"pt": "dedo anelar",     "en": "ring finger",   "pron": "ríng fínguer"},
    {"pt": "dedo mindinho",   "en": "pinky finger",  "pron": "pínki fínguer"},
    {"pt": "unha",            "en": "nail",          "pron": "néil"},

    # Pernas
    {"pt": "perna",           "en": "leg",           "pron": "lég"},
    {"pt": "coxa",            "en": "thigh",         "pron": "thái"},
    {"pt": "joelho",          "en": "knee",          "pron": "ní"},
    {"pt": "canela",          "en": "shin",          "pron": "shín"},
    {"pt": "tornozelo",       "en": "ankle",         "pron": "énkol"},
    {"pt": "pé",              "en": "foot",          "pron": "fút"},
    {"pt": "pés",             "en": "feet",          "pron": "fít"},
    {"pt": "dedo do pé",      "en": "toe",           "pron": "tôu"},
    {"pt": "calcanhar",       "en": "heel",          "pron": "ríl"},
    {"pt": "sola",            "en": "sole",          "pron": "sôul"},

    # Órgãos
    {"pt": "coração",         "en": "heart",         "pron": "rárt"},
    {"pt": "pulmão",          "en": "lung",          "pron": "lán"},
    {"pt": "fígado",          "en": "liver",         "pron": "líver"},
    {"pt": "rim",             "en": "kidney",        "pron": "kídni"},
    {"pt": "intestino",       "en": "intestine",     "pron": "intéstin"},
    {"pt": "cérebro",         "en": "brain",         "pron": "bréin"},
    {"pt": "veia",            "en": "vein",          "pron": "véin"},
    {"pt": "artéria",         "en": "artery",        "pron": "árteri"},
    {"pt": "sangue",          "en": "blood",         "pron": "blád"},
    {"pt": "osso",            "en": "bone",          "pron": "bôun"},
    {"pt": "músculo",         "en": "muscle",        "pron": "másol"},
    {"pt": "pele",            "en": "skin",          "pron": "skín"},
    {"pt": "nervo",           "en": "nerve",         "pron": "nérv"},
    {"pt": "pulso (batimento)","en": "pulse",        "pron": "páls"},
    {"pt": "respiração",      "en": "breath",        "pron": "bréth"},
    {"pt": "voz",             "en": "voice",         "pron": "vóis"},
    {"pt": "lágrima",         "en": "tear",          "pron": "tír"},
    {"pt": "suor",            "en": "sweat",         "pron": "suét"},
    {"pt": "saliva",          "en": "saliva",        "pron": "saláiva"},

    # Sentidos
    {"pt": "visão",           "en": "sight",         "pron": "sáit"},
    {"pt": "audição",         "en": "hearing",       "pron": "ríring"},
    {"pt": "olfato",          "en": "smell",         "pron": "smél"},
    {"pt": "paladar",         "en": "taste",         "pron": "téist"},
    {"pt": "tato",            "en": "touch",         "pron": "tách"},

    # Aparência
    {"pt": "alto",            "en": "tall",          "pron": "tól"},
    {"pt": "baixo",           "en": "short",         "pron": "shórt"},
    {"pt": "magro",           "en": "thin",          "pron": "thín"},
    {"pt": "gordo",           "en": "fat",           "pron": "fét"},
    {"pt": "forte",           "en": "strong",        "pron": "strong"},
    {"pt": "fraco",           "en": "weak",          "pron": "uík"},
    {"pt": "bonito",          "en": "handsome",      "pron": "rénsom"},
    {"pt": "bonita",          "en": "beautiful",     "pron": "biútiful"},
    {"pt": "feio",            "en": "ugly",          "pron": "ágli"},
    {"pt": "jovem",           "en": "young",         "pron": "iáng"},
    {"pt": "velho",           "en": "old",           "pron": "ôuld"},
    {"pt": "loiro",           "en": "blonde",        "pron": "blónd"},
    {"pt": "moreno",          "en": "brunette",      "pron": "brunét"},
    {"pt": "ruivo",           "en": "redhead",       "pron": "rédréd"},
    {"pt": "careca",          "en": "bald",          "pron": "bóld"},
    {"pt": "cabelo comprido", "en": "long hair",     "pron": "long rér"},
    {"pt": "cabelo curto",    "en": "short hair",    "pron": "shórt rér"},
    {"pt": "cabelo cacheado", "en": "curly hair",    "pron": "kérli rér"},
    {"pt": "cabelo liso",     "en": "straight hair", "pron": "stréit rér"},
    {"pt": "olhos azuis",     "en": "blue eyes",     "pron": "blú áis"},
    {"pt": "olhos castanhos", "en": "brown eyes",    "pron": "bráun áis"},
    {"pt": "olhos verdes",    "en": "green eyes",    "pron": "grín áis"},
    {"pt": "olhos pretos",    "en": "black eyes",    "pron": "blék áis"},

    # Ações
    {"pt": "andar",           "en": "to walk",       "pron": "tu uók"},
    {"pt": "correr",          "en": "to run",        "pron": "tu rán"},
    {"pt": "pular",           "en": "to jump",       "pron": "tu djámp"},
    {"pt": "sentar",          "en": "to sit",        "pron": "tu sít"},
    {"pt": "levantar",        "en": "to stand up",   "pron": "tu sténd áp"},
    {"pt": "deitar",          "en": "to lie down",   "pron": "tu lái dáun"},
    {"pt": "dormir",          "en": "to sleep",      "pron": "tu slíp"},
    {"pt": "acordar",         "en": "to wake up",    "pron": "tu uéik áp"},
    {"pt": "comer",           "en": "to eat",        "pron": "tu ít"},
    {"pt": "beber",           "en": "to drink",      "pron": "tu drínk"},
    {"pt": "respirar",        "en": "to breathe",    "pron": "tu bríth"},
    {"pt": "falar",           "en": "to speak",      "pron": "tu spík"},
    {"pt": "ouvir",           "en": "to hear",       "pron": "tu rír"},
    {"pt": "ver",             "en": "to see",        "pron": "tu sí"},
    {"pt": "olhar",           "en": "to look",       "pron": "tu lúk"},
    {"pt": "tocar",           "en": "to touch",      "pron": "tu tách"},
    {"pt": "cheirar",         "en": "to smell",      "pron": "tu smél"},
    {"pt": "provar",          "en": "to taste",      "pron": "tu téist"},
    {"pt": "sorrir",          "en": "to smile",      "pron": "tu smáil"},
    {"pt": "chorar",          "en": "to cry",        "pron": "tu krái"},
    {"pt": "rir",             "en": "to laugh",      "pron": "tu léf"},
    {"pt": "espirrar",        "en": "to sneeze",     "pron": "tu sníz"},
    {"pt": "tossir",          "en": "to cough",      "pron": "tu kóf"},
    {"pt": "bocejar",         "en": "to yawn",       "pron": "tu ión"},
    {"pt": "piscar",          "en": "to blink",      "pron": "tu blínk"},
    {"pt": "morder",          "en": "to bite",       "pron": "tu báit"},
    {"pt": "engolir",         "en": "to swallow",    "pron": "tu suólou"},
    {"pt": "mastigar",        "en": "to chew",       "pron": "tu chú"},
    {"pt": "chutar",          "en": "to kick",       "pron": "tu kík"},
    {"pt": "bater",           "en": "to hit",        "pron": "tu rít"},
    {"pt": "segurar",         "en": "to hold",       "pron": "tu rôuld"},
    {"pt": "apertar",         "en": "to squeeze",    "pron": "tu skuíz"},
    {"pt": "abraçar",         "en": "to hug",        "pron": "tu rág"},
    {"pt": "beijar",          "en": "to kiss",       "pron": "tu kís"},
    {"pt": "empurrar",        "en": "to push",       "pron": "tu púsh"},
    {"pt": "puxar",           "en": "to pull",       "pron": "tu púl"},
    {"pt": "carregar",        "en": "to carry",      "pron": "tu kéri"},
    {"pt": "levantar (peso)", "en": "to lift",       "pron": "tu líft"},
    {"pt": "pegar",           "en": "to grab",       "pron": "tu gréb"},
    {"pt": "soltar",          "en": "to release",    "pron": "tu rilís"},

    # Saúde e condições
    {"pt": "saudável",        "en": "healthy",       "pron": "rélthi"},
    {"pt": "doente",          "en": "sick",          "pron": "sík"},
    {"pt": "cansado",         "en": "tired",         "pron": "táierd"},
    {"pt": "com sono",        "en": "sleepy",        "pron": "slípi"},
    {"pt": "com fome",        "en": "hungry",        "pron": "rángri"},
    {"pt": "com sede",        "en": "thirsty",       "pron": "thérsti"},
    {"pt": "com dor",         "en": "in pain",       "pron": "in péin"},
    {"pt": "machucado",       "en": "hurt",          "pron": "rért"},
    {"pt": "quebrado",        "en": "broken",        "pron": "brôuken"},
    {"pt": "machucado (ferida)","en": "injured",     "pron": "índjdurd"},
    {"pt": "grávida",         "en": "pregnant",      "pron": "prégnant"},
    {"pt": "gripado",         "en": "with a cold",   "pron": "uíth e kôuld"},
    {"pt": "resfriado",       "en": "having a cold", "pron": "réving e kôuld"},
    {"pt": "com febre",       "en": "with fever",    "pron": "uíth fíver"},
    {"pt": "sarado",          "en": "in shape",      "pron": "in shéip"},
    {"pt": "fora de forma",   "en": "out of shape",  "pron": "áut óv shéip"},

    # Frases
    {"pt": "dor de cabeça",       "en": "headache",         "pron": "rédeik"},
    {"pt": "dor de barriga",      "en": "stomachache",      "pron": "stómakéik"},
    {"pt": "dor de dente",        "en": "toothache",        "pron": "túthéik"},
    {"pt": "dor nas costas",      "en": "backache",         "pron": "békeik"},
    {"pt": "dor de garganta",     "en": "sore throat",      "pron": "sór thrôut"},
    {"pt": "dor de ouvido",       "en": "earache",          "pron": "íreik"},
    {"pt": "dor no peito",        "en": "chest pain",       "pron": "chést péin"},
    {"pt": "dor nas pernas",      "en": "leg pain",         "pron": "lég péin"},
    {"pt": "meu braço dói",       "en": "my arm hurts",     "pron": "mái árm rérts"},
    {"pt": "meu pé está inchado", "en": "my foot is swollen","pron": "mái fút is suólen"},
    {"pt": "estou me sentindo mal","en": "I'm feeling sick", "pron": "áim fíling sík"},
    {"pt": "não estou bem",       "en": "I don't feel well", "pron": "ái dônt fíl uél"},
    {"pt": "preciso de um médico", "en": "I need a doctor",  "pron": "ái níd e dóktor"},
    {"pt": "quebrei o braço",     "en": "I broke my arm",    "pron": "ái brôuk mái árm"},
    {"pt": "quebrei a perna",     "en": "I broke my leg",    "pron": "ái brôuk mái lég"},
    {"pt": "estou sangrando",     "en": "I'm bleeding",      "pron": "áim blíding"},
    {"pt": "tomei um remédio",    "en": "I took medicine",   "pron": "ái túk mésdisin"},
    {"pt": "sou alérgico",        "en": "I'm allergic",      "pron": "áim alérdjik"},
    {"pt": "tenho asma",          "en": "I have asthma",     "pron": "ái rév ézma"},
    {"pt": "tenho diabetes",      "en": "I have diabetes",   "pron": "ái rév dáiabítis"},
    {"pt": "estou grávida",       "en": "I'm pregnant",      "pron": "áim prégnant"},
    {"pt": "estou de dieta",      "en": "I'm on a diet",     "pron": "áim ón e dáiet"},
    {"pt": "faço exercício",      "en": "I exercise",        "pron": "ái éksersáiz"},
    {"pt": "vou à academia",      "en": "I go to the gym",   "pron": "ái gôu tu de djím"},
]

# ============ 🕐 HORAS E DATAS (200) ============
horas = [
    # Horas
    {"pt": "hora",            "en": "hour",          "pron": "áuer"},
    {"pt": "hora (relógio)",  "en": "o'clock",       "pron": "oklók"},
    {"pt": "minuto",          "en": "minute",        "pron": "mínit"},
    {"pt": "segundo",         "en": "second",        "pron": "sékond"},
    {"pt": "manhã",           "en": "morning",       "pron": "mórning"},
    {"pt": "tarde",           "en": "afternoon",     "pron": "áfternun"},
    {"pt": "noite",           "en": "evening",       "pron": "ívning"},
    {"pt": "noite (dormir)",  "en": "night",         "pron": "náit"},
    {"pt": "meio-dia",        "en": "noon",          "pron": "nún"},
    {"pt": "meia-noite",      "en": "midnight",      "pron": "mídnáit"},
    {"pt": "madrugada",       "en": "dawn",          "pron": "dón"},
    {"pt": "amanhecer",       "en": "sunrise",       "pron": "sánráis"},
    {"pt": "anoitecer",       "en": "sunset",        "pron": "sánsét"},
    {"pt": "agora",           "en": "now",           "pron": "náu"},
    {"pt": "mais tarde",      "en": "later",         "pron": "léiter"},
    {"pt": "cedo",            "en": "early",         "pron": "érli"},
    {"pt": "tarde (atrasado)", "en": "late",         "pron": "léit"},
    {"pt": "em ponto",        "en": "sharp",         "pron": "shárp"},
    {"pt": "aproximadamente", "en": "about",         "pron": "abáut"},
    {"pt": "mais ou menos",   "en": "around",        "pron": "aráund"},

    # Números ordinais (tempo)
    {"pt": "primeiro",        "en": "first",         "pron": "férst"},
    {"pt": "segundo",         "en": "second",        "pron": "sékond"},
    {"pt": "terceiro",        "en": "third",         "pron": "thérd"},
    {"pt": "quarto",          "en": "fourth",        "pron": "fórth"},
    {"pt": "quinto",          "en": "fifth",         "pron": "fífth"},
    {"pt": "sexto",           "en": "sixth",         "pron": "síksth"},
    {"pt": "sétimo",          "en": "seventh",       "pron": "séventh"},
    {"pt": "oitavo",          "en": "eighth",        "pron": "éith"},
    {"pt": "nono",            "en": "ninth",         "pron": "náinth"},
    {"pt": "décimo",          "en": "tenth",         "pron": "ténth"},
    {"pt": "último",          "en": "last",          "pron": "lést"},
    {"pt": "próximo",         "en": "next",          "pron": "nékst"},
    {"pt": "penúltimo",       "en": "second to last","pron": "sékond tu lést"},

    # Horas específicas
    {"pt": "uma hora",        "en": "one o'clock",   "pron": "uán oklók"},
    {"pt": "duas horas",      "en": "two o'clock",   "pron": "tú oklók"},
    {"pt": "três horas",      "en": "three o'clock", "pron": "thrí oklók"},
    {"pt": "quatro horas",    "en": "four o'clock",  "pron": "fór oklók"},
    {"pt": "cinco horas",     "en": "five o'clock",  "pron": "fáiv oklók"},
    {"pt": "seis horas",      "en": "six o'clock",   "pron": "síks oklók"},
    {"pt": "sete horas",      "en": "seven o'clock", "pron": "séven oklók"},
    {"pt": "oito horas",      "en": "eight o'clock", "pron": "êit oklók"},
    {"pt": "nove horas",      "en": "nine o'clock",  "pron": "náin oklók"},
    {"pt": "dez horas",       "en": "ten o'clock",   "pron": "tén oklók"},
    {"pt": "onze horas",      "en": "eleven o'clock","pron": "iléven oklók"},
    {"pt": "meio-dia e meia", "en": "twelve thirty","pron": "tuélv thérti"},

    # Minutos
    {"pt": "quinze minutos",  "en": "fifteen minutes","pron": "fíftin mínits"},
    {"pt": "trinta minutos",  "en": "thirty minutes","pron": "thérti mínits"},
    {"pt": "quarenta e cinco minutos","en": "forty-five minutes","pron": "fórti fáiv mínits"},
    {"pt": "e quinze",        "en": "quarter past",  "pron": "kuórter pést"},
    {"pt": "e meia",          "en": "half past",     "pron": "réf pést"},
    {"pt": "quinze para",     "en": "quarter to",    "pron": "kuórter tu"},
    {"pt": "dez para",        "en": "ten to",        "pron": "tén tu"},
    {"pt": "cinco para",      "en": "five to",       "pron": "fáiv tu"},
    {"pt": "e cinco",         "en": "five past",     "pron": "fáiv pést"},
    {"pt": "e dez",           "en": "ten past",      "pron": "tén pést"},
    {"pt": "e vinte",         "en": "twenty past",   "pron": "tuénti pést"},
    {"pt": "em ponto",        "en": "on the dot",    "pron": "ón de dót"},

    # Dias
    {"pt": "dia",             "en": "day",           "pron": "déi"},
    {"pt": "hoje",            "en": "today",         "pron": "tudéi"},
    {"pt": "amanhã",          "en": "tomorrow",      "pron": "tumórou"},
    {"pt": "ontem",           "en": "yesterday",     "pron": "iéstérdéi"},
    {"pt": "anteontem",       "en": "day before yesterday","pron": "déi bifór iéstérdéi"},
    {"pt": "depois de amanhã","en": "day after tomorrow","pron": "déi éfter tumórou"},
    {"pt": "esta noite",      "en": "tonight",       "pron": "tunáit"},
    {"pt": "esta manhã",      "en": "this morning",  "pron": "dis mórning"},
    {"pt": "esta tarde",      "en": "this afternoon","pron": "dis áfternun"},
    {"pt": "ontem à noite",   "en": "last night",    "pron": "lést náit"},
    {"pt": "amanhã cedo",     "en": "tomorrow morning","pron": "tumórou mórning"},
    {"pt": "amanhã à noite",  "en": "tomorrow night","pron": "tumórou náit"},
    {"pt": "todos os dias",   "en": "every day",     "pron": "évri déi"},
    {"pt": "dia útil",        "en": "weekday",       "pron": "uíkdei"},
    {"pt": "fim de semana",   "en": "weekend",       "pron": "uíkend"},
    {"pt": "dia de semana",   "en": "weekday",       "pron": "uíkdei"},
    {"pt": "dia santo",       "en": "holy day",      "pron": "rôuli déi"},
    {"pt": "dia útil",        "en": "business day",  "pron": "bíznis déi"},

    # Semanas
    {"pt": "semana",          "en": "week",          "pron": "uík"},
    {"pt": "esta semana",     "en": "this week",     "pron": "dis uík"},
    {"pt": "semana passada",  "en": "last week",     "pron": "lést uík"},
    {"pt": "semana que vem",  "en": "next week",     "pron": "nékst uík"},
    {"pt": "semanalmente",    "en": "weekly",        "pron": "uíkli"},
    {"pt": "duas semanas",    "en": "two weeks",     "pron": "tú uíks"},
    {"pt": "quinzena",        "en": "fortnight",     "pron": "fórtnáit"},

    # Meses
    {"pt": "mês",             "en": "month",         "pron": "mánth"},
    {"pt": "este mês",        "en": "this month",    "pron": "dis mánth"},
    {"pt": "mês passado",     "en": "last month",    "pron": "lést mánth"},
    {"pt": "mês que vem",     "en": "next month",    "pron": "nékst mánth"},
    {"pt": "mensalmente",     "en": "monthly",       "pron": "mánthli"},
    {"pt": "janeiro",         "en": "January",       "pron": "djéniueri"},
    {"pt": "fevereiro",       "en": "February",      "pron": "fébrueri"},
    {"pt": "março",           "en": "March",         "pron": "márch"},
    {"pt": "abril",           "en": "April",         "pron": "éipril"},
    {"pt": "maio",            "en": "May",           "pron": "méi"},
    {"pt": "junho",           "en": "June",          "pron": "djún"},
    {"pt": "julho",           "en": "July",          "pron": "djulái"},
    {"pt": "agosto",          "en": "August",        "pron": "ógost"},
    {"pt": "setembro",        "en": "September",     "pron": "septémber"},
    {"pt": "outubro",         "en": "October",       "pron": "októuber"},
    {"pt": "novembro",        "en": "November",      "pron": "novémber"},
    {"pt": "dezembro",        "en": "December",      "pron": "disémber"},

    # Anos
    {"pt": "ano",             "en": "year",          "pron": "íer"},
    {"pt": "este ano",        "en": "this year",     "pron": "dis íer"},
    {"pt": "ano passado",     "en": "last year",     "pron": "lést íer"},
    {"pt": "ano que vem",     "en": "next year",     "pron": "nékst íer"},
    {"pt": "anualmente",      "en": "yearly",        "pron": "íerli"},
    {"pt": "década",          "en": "decade",        "pron": "dékeid"},
    {"pt": "século",          "en": "century",       "pron": "sénchuri"},
    {"pt": "milênio",         "en": "millennium",    "pron": "milénium"},

    # Estações
    {"pt": "primavera",       "en": "spring",        "pron": "spríng"},
    {"pt": "verão",           "en": "summer",        "pron": "sámer"},
    {"pt": "outono",          "en": "autumn",        "pron": "ótom"},
    {"pt": "inverno",         "en": "winter",        "pron": "uínter"},

    # Feriados
    {"pt": "feriado",         "en": "holiday",       "pron": "rólidei"},
    {"pt": "ano novo",        "en": "New Year",      "pron": "niú íer"},
    {"pt": "natal",           "en": "Christmas",     "pron": "krísmass"},
    {"pt": "véspera de natal","en": "Christmas Eve", "pron": "krísmass ív"},
    {"pt": "páscoa",          "en": "Easter",        "pron": "íster"},
    {"pt": "carnaval",        "en": "Carnival",      "pron": "kárnivol"},
    {"pt": "dia das mães",    "en": "Mother's Day",  "pron": "máders déi"},
    {"pt": "dia dos pais",    "en": "Father's Day",  "pron": "fáders déi"},
    {"pt": "dia dos namorados","en": "Valentine's Day","pron": "vélentains déi"},
    {"pt": "halloween",       "en": "Halloween",     "pron": "rélouín"},
    {"pt": "ação de graças",  "en": "Thanksgiving",  "pron": "thénksguíving"},
    {"pt": "dia do trabalho", "en": "Labor Day",     "pron": "léibor déi"},
    {"pt": "independência",   "en": "Independence Day","pron": "indipéndens déi"},
    {"pt": "aniversário",     "en": "birthday",      "pron": "bérthdéi"},
    {"pt": "aniversário de casamento","en": "anniversary","pron": "anivérsari"},

    # Frequência
    {"pt": "sempre",          "en": "always",        "pron": "ólueis"},
    {"pt": "nunca",           "en": "never",         "pron": "néver"},
    {"pt": "às vezes",        "en": "sometimes",     "pron": "sámtáims"},
    {"pt": "frequentemente",  "en": "often",         "pron": "ófen"},
    {"pt": "raramente",       "en": "rarely",        "pron": "rérli"},
    {"pt": "diariamente",     "en": "daily",         "pron": "déili"},
    {"pt": "de vez em quando","en": "once in a while","pron": "uáns in e uáil"},
    {"pt": "toda hora",       "en": "all the time",  "pron": "ól de táim"},
    {"pt": "de novo",         "en": "again",         "pron": "aguén"},
    {"pt": "quase sempre",    "en": "almost always", "pron": "ólmôust ólueis"},
    {"pt": "quase nunca",     "en": "hardly ever",   "pron": "rárdli éver"},

    # Frases
    {"pt": "que horas são?",           "en": "what time is it?",     "pron": "uót táim is it"},
    {"pt": "são três horas",           "en": "it's three o'clock",   "pron": "its thrí oklók"},
    {"pt": "são três e meia",          "en": "it's half past three", "pron": "its réf pést thrí"},
    {"pt": "são três e quinze",        "en": "it's quarter past three","pron": "its kuórter pést thrí"},
    {"pt": "são quinze para as quatro","en": "it's quarter to four", "pron": "its kuórter tu fór"},
    {"pt": "que dia é hoje?",          "en": "what day is it today?","pron": "uót déi is it tudéi"},
    {"pt": "hoje é segunda-feira",     "en": "today is Monday",      "pron": "tudéi is mándei"},
    {"pt": "que dia é amanhã?",        "en": "what day is tomorrow?", "pron": "uót déi is tumórou"},
    {"pt": "que dia foi ontem?",       "en": "what day was yesterday?","pron": "uót déi uós iéstérdéi"},
    {"pt": "em que mês estamos?",      "en": "what month is it?",    "pron": "uót mánth is it"},
    {"pt": "que ano estamos?",         "en": "what year is it?",     "pron": "uót íer is it"},
    {"pt": "que horas você tem?",      "en": "what time do you have?","pron": "uót táim du iu rév"},
    {"pt": "que horas abre?",          "en": "what time does it open?","pron": "uót táim dáz it ôupen"},
    {"pt": "que horas fecha?",         "en": "what time does it close?","pron": "uót táim dáz it klôuz"},
    {"pt": "que horas começa?",        "en": "what time does it start?","pron": "uót táim dáz it stárt"},
    {"pt": "quanto tempo demora?",     "en": "how long does it take?","pron": "ráu long dáz it téik"},
    {"pt": "está na hora",             "en": "it's time",            "pron": "its táim"},
    {"pt": "é hora de ir",             "en": "it's time to go",      "pron": "its táim tu gôu"},
    {"pt": "estou atrasado",           "en": "I'm late",             "pron": "áim léit"},
    {"pt": "cheguei cedo",             "en": "I arrived early",      "pron": "ái aráivd érli"},
    {"pt": "daqui a pouco",            "en": "in a bit",             "pron": "in e bít"},
    {"pt": "nos vemos amanhã",         "en": "see you tomorrow",     "pron": "sí iu tumórou"},
    {"pt": "nos vemos na segunda",     "en": "see you on Monday",    "pron": "sí iu ón mándei"},
    {"pt": "até amanhã",               "en": "until tomorrow",       "pron": "antíl tumórou"},
    {"pt": "até mais tarde",           "en": "see you later",        "pron": "sí iu léiter"},
    {"pt": "bom dia",                  "en": "good morning",         "pron": "gud mórning"},
    {"pt": "boa tarde",                "en": "good afternoon",       "pron": "gud áfternun"},
    {"pt": "boa noite",                "en": "good evening",         "pron": "gud ívning"},
    {"pt": "que dia maravilhoso!",     "en": "what a wonderful day!", "pron": "uót e uánderful déi"},
    {"pt": "que horas você pode?",     "en": "what time can you?",    "pron": "uót táim kén iu"},
    {"pt": "quando você pode?",        "en": "when can you?",         "pron": "uén kén iu"},
    {"pt": "qual o melhor dia?",       "en": "what's the best day?",  "pron": "uóts de bést déi"},
    {"pt": "estou livre amanhã",       "en": "I'm free tomorrow",     "pron": "áim frí tumórou"},
    {"pt": "não tenho tempo",          "en": "I don't have time",     "pron": "ái dônt rév táim"},
    {"pt": "vou pensar",               "en": "I'll think about it",   "pron": "áil thínk abáut it"},
    {"pt": "que semana longa!",        "en": "what a long week!",     "pron": "uót e long uík"},
    {"pt": "boa semana!",              "en": "have a good week!",     "pron": "rév e gúd uík"},
    {"pt": "bom fim de semana!",       "en": "have a nice weekend!",  "pron": "rév e náis uíkend"},
    {"pt": "feliz aniversário!",       "en": "happy birthday!",       "pron": "répi bérthdéi"},
    {"pt": "feliz ano novo!",          "en": "happy new year!",       "pron": "répi niú íer"},
    {"pt": "feliz natal!",             "en": "merry Christmas!",      "pron": "méri krísmass"},
    {"pt": "boas festas!",             "en": "happy holidays!",       "pron": "répi rólideis"},

    # Duração
    {"pt": "por uma hora",            "en": "for an hour",           "pron": "fór en áuer"},
    {"pt": "por duas horas",          "en": "for two hours",         "pron": "fór tú áuers"},
    {"pt": "por um dia",              "en": "for a day",             "pron": "fór e déi"},
    {"pt": "por uma semana",          "en": "for a week",            "pron": "fór e uík"},
    {"pt": "por um mês",              "en": "for a month",           "pron": "fór e mánth"},
    {"pt": "por um ano",              "en": "for a year",            "pron": "fór e íer"},
    {"pt": "daqui a uma hora",        "en": "in an hour",            "pron": "in en áuer"},
    {"pt": "daqui a dois dias",       "en": "in two days",           "pron": "in tú déis"},
    {"pt": "daqui a uma semana",      "en": "in a week",             "pron": "in e uík"},
    {"pt": "daqui a um mês",          "en": "in a month",            "pron": "in e mánth"},
    {"pt": "há uma hora",             "en": "an hour ago",           "pron": "en áuer agôu"},
    {"pt": "há dois dias",            "en": "two days ago",          "pron": "tú déis agôu"},
    {"pt": "há uma semana",           "en": "a week ago",            "pron": "e uík agôu"},
    {"pt": "há um mês",               "en": "a month ago",           "pron": "e mánth agôu"},
    {"pt": "há muito tempo",          "en": "a long time ago",       "pron": "e long táim agôu"},
    {"pt": "recentemente",            "en": "recently",              "pron": "rísentli"},
    {"pt": "ultimamente",             "en": "lately",                "pron": "léitli"},
    {"pt": "em breve",                "en": "soon",                  "pron": "sún"},
    {"pt": "em breve possível",       "en": "as soon as possible",   "pron": "és sún és pósibol"},
    {"pt": "imediatamente",           "en": "immediately",           "pron": "imídiatli"},
]

# ============ 🔷 FORMAS E TAMANHOS (200) ============
formas = [
    # Formas básicas
    {"pt": "forma",           "en": "shape",         "pron": "shéip"},
    {"pt": "círculo",         "en": "circle",        "pron": "sérkol"},
    {"pt": "quadrado",        "en": "square",        "pron": "skué r"},
    {"pt": "triângulo",       "en": "triangle",      "pron": "tráiéngol"},
    {"pt": "retângulo",       "en": "rectangle",     "pron": "rékténgol"},
    {"pt": "losango",         "en": "diamond",       "pron": "dáiamond"},
    {"pt": "estrela",         "en": "star",          "pron": "stár"},
    {"pt": "coração",         "en": "heart",         "pron": "rárt"},
    {"pt": "oval",            "en": "oval",          "pron": "ôuval"},
    {"pt": "elipse",          "en": "ellipse",       "pron": "ilíps"},
    {"pt": "pentágono",       "en": "pentagon",      "pron": "péntagon"},
    {"pt": "hexágono",        "en": "hexagon",       "pron": "réksagon"},
    {"pt": "octógono",        "en": "octagon",       "pron": "óktagon"},
    {"pt": "esfera",          "en": "sphere",        "pron": "sfír"},
    {"pt": "cubo",            "en": "cube",          "pron": "kiúb"},
    {"pt": "cilindro",        "en": "cylinder",      "pron": "sílindar"},
    {"pt": "cone",            "en": "cone",          "pron": "kôun"},
    {"pt": "pirâmide",        "en": "pyramid",       "pron": "píramid"},

    # Descrições
    {"pt": "reto",            "en": "straight",      "pron": "stréit"},
    {"pt": "curvo",           "en": "curved",        "pron": "kérvd"},
    {"pt": "redondo",         "en": "round",         "pron": "ráund"},
    {"pt": "plano",           "en": "flat",          "pron": "flét"},
    {"pt": "fino",            "en": "thin",          "pron": "thín"},
    {"pt": "grosso",          "en": "thick",         "pron": "thík"},
    {"pt": "estreito",        "en": "narrow",        "pron": "nérou"},
    {"pt": "largo",           "en": "wide",          "pron": "uáid"},
    {"pt": "comprido",        "en": "long",          "pron": "long"},
    {"pt": "curto",           "en": "short",         "pron": "shórt"},
    {"pt": "alto",            "en": "tall",          "pron": "tól"},
    {"pt": "baixo",           "en": "low",           "pron": "lôu"},
    {"pt": "profundo",        "en": "deep",          "pron": "díp"},
    {"pt": "raso",            "en": "shallow",       "pron": "shélou"},
    {"pt": "pontudo",         "en": "pointed",       "pron": "póintid"},
    {"pt": "afiado",          "en": "sharp",         "pron": "shárp"},
    {"pt": "liso",            "en": "smooth",        "pron": "smúth"},
    {"pt": "áspero",          "en": "rough",         "pron": "ráf"},
    {"pt": "cheio",           "en": "full",          "pron": "fúl"},
    {"pt": "vazio",           "en": "empty",         "pron": "émpti"},

    # Tamanhos
    {"pt": "tamanho",         "en": "size",          "pron": "sáiz"},
    {"pt": "grande",          "en": "big",           "pron": "bíg"},
    {"pt": "grande (enorme)", "en": "large",         "pron": "lárj"},
    {"pt": "pequeno",         "en": "small",         "pron": "smól"},
    {"pt": "pequenininho",    "en": "tiny",          "pron": "táini"},
    {"pt": "médio",           "en": "medium",        "pron": "mídium"},
    {"pt": "gigante",         "en": "giant",         "pron": "djáiant"},
    {"pt": "enorme",          "en": "huge",          "pron": "riúdj"},
    {"pt": "minúsculo",       "en": "minuscule",     "pron": "mináskiul"},
    {"pt": "médio-grande",    "en": "large",         "pron": "lárj"},
    {"pt": "tamanho P",       "en": "size S",        "pron": "sáiz és"},
    {"pt": "tamanho M",       "en": "size M",        "pron": "sáiz ém"},
    {"pt": "tamanho G",       "en": "size L",        "pron": "sáiz él"},
    {"pt": "tamanho GG",      "en": "size XL",       "pron": "sáiz eksél"},
    {"pt": "tamanho único",   "en": "one size",      "pron": "uán sáiz"},
    {"pt": "sob medida",      "en": "custom",        "pron": "kástom"},
    {"pt": "fora de tamanho", "en": "out of size",   "pron": "áut óv sáiz"},

    # Pesos e medidas
    {"pt": "peso",            "en": "weight",        "pron": "uéit"},
    {"pt": "grama",           "en": "gram",          "pron": "grém"},
    {"pt": "quilograma",      "en": "kilogram",      "pron": "kílogram"},
    {"pt": "tonelada",        "en": "ton",           "pron": "tán"},
    {"pt": "miligrama",       "en": "milligram",     "pron": "míligrém"},
    {"pt": "litro",           "en": "liter",         "pron": "líter"},
    {"pt": "mililitro",       "en": "milliliter",    "pron": "mílilíter"},
    {"pt": "metro",           "en": "meter",         "pron": "míter"},
    {"pt": "centímetro",      "en": "centimeter",    "pron": "séntimíter"},
    {"pt": "milímetro",       "en": "millimeter",    "pron": "mílimíter"},
    {"pt": "quilômetro",      "en": "kilometer",     "pron": "kilómiter"},
    {"pt": "polegada",        "en": "inch",          "pron": "ínch"},
    {"pt": "pé (medida)",     "en": "foot",          "pron": "fút"},
    {"pt": "jarda",           "en": "yard",          "pron": "iárd"},
    {"pt": "milha",           "en": "mile",          "pron": "máil"},
    {"pt": "galão",           "en": "gallon",        "pron": "gélon"},
    {"pt": "libra (peso)",    "en": "pound",         "pron": "páund"},
    {"pt": "onça",            "en": "ounce",         "pron": "áuns"},

    # Comparações
    {"pt": "maior",           "en": "bigger",        "pron": "bíguer"},
    {"pt": "menor",           "en": "smaller",       "pron": "smóler"},
    {"pt": "mais alto",       "en": "taller",        "pron": "tóler"},
    {"pt": "mais baixo",      "en": "shorter",       "pron": "shórter"},
    {"pt": "mais longo",      "en": "longer",        "pron": "lónguer"},
    {"pt": "mais curto",      "en": "shorter",       "pron": "shórter"},
    {"pt": "mais largo",      "en": "wider",         "pron": "uáider"},
    {"pt": "mais estreito",   "en": "narrower",      "pron": "nérouer"},
    {"pt": "mais grosso",     "en": "thicker",       "pron": "thíker"},
    {"pt": "mais fino",       "en": "thinner",       "pron": "thíner"},
    {"pt": "o maior",         "en": "the biggest",   "pron": "de bíguest"},
    {"pt": "o menor",         "en": "the smallest",  "pron": "de smólest"},
    {"pt": "o melhor",        "en": "the best",      "pron": "de bést"},
    {"pt": "o pior",          "en": "the worst",     "pron": "de uórst"},
    {"pt": "igual",           "en": "equal",         "pron": "íkuol"},
    {"pt": "diferente",       "en": "different",     "pron": "díferent"},
    {"pt": "o mesmo",         "en": "the same",      "pron": "de séim"},
    {"pt": "parecido",        "en": "similar",       "pron": "símilar"},

    # Quantidade
    {"pt": "todos",           "en": "all",           "pron": "ól"},
    {"pt": "alguns",          "en": "some",          "pron": "sám"},
    {"pt": "muitos",          "en": "many",          "pron": "méni"},
    {"pt": "poucos",          "en": "few",           "pron": "fiú"},
    {"pt": "nenhum",          "en": "none",          "pron": "nán"},
    {"pt": "vários",          "en": "several",       "pron": "séveral"},
    {"pt": "cada",            "en": "each",          "pron": "ích"},
    {"pt": "todo",            "en": "every",         "pron": "évri"},
    {"pt": "ambos",           "en": "both",          "pron": "bôuth"},
    {"pt": "outro",           "en": "other",         "pron": "áder"},
    {"pt": "mais",            "en": "more",          "pron": "mór"},
    {"pt": "menos",           "en": "less",          "pron": "lés"},
    {"pt": "muito",           "en": "very",          "pron": "véri"},
    {"pt": "pouco",           "en": "little",        "pron": "lítol"},
    {"pt": "bastante",        "en": "enough",        "pron": "ináf"},
    {"pt": "demais",          "en": "too much",      "pron": "tú mách"},
    {"pt": "metade",          "en": "half",          "pron": "réf"},
    {"pt": "um quarto",       "en": "a quarter",     "pron": "e kuórter"},
    {"pt": "um terço",        "en": "a third",       "pron": "e thérd"},
    {"pt": "dobro",           "en": "double",        "pron": "dábol"},
    {"pt": "triplo",          "en": "triple",        "pron": "trípol"},
    {"pt": "por cento",       "en": "percent",       "pron": "persént"},

    # Cores (extras)
    {"pt": "claro",           "en": "light",         "pron": "láit"},
    {"pt": "escuro",          "en": "dark",          "pron": "dárk"},
    {"pt": "brilhante",       "en": "bright",        "pron": "bráit"},
    {"pt": "opaco",           "en": "matte",         "pron": "mét"},
    {"pt": "transparente",    "en": "transparent",   "pron": "trénspérent"},
    {"pt": "colorido",        "en": "colorful",      "pron": "kólorful"},
    {"pt": "preto e branco",  "en": "black and white","pron": "blék énd uáit"},
    {"pt": "bege",            "en": "beige",         "pron": "béidj"},
    {"pt": "vinho",           "en": "wine",          "pron": "uáin"},
    {"pt": "dourado",         "en": "gold",          "pron": "gôuld"},
    {"pt": "prateado",        "en": "silver",        "pron": "sílver"},
    {"pt": "turquesa",        "en": "turquoise",     "pron": "térkuois"},
    {"pt": "violeta",         "en": "violet",        "pron": "váiolet"},
    {"pt": "lilás",           "en": "lilac",         "pron": "láilek"},
    {"pt": "salmão",          "en": "salmon",        "pron": "sémon"},
    {"pt": "creme",           "en": "cream",         "pron": "krím"},

    # Texturas
    {"pt": "macio",           "en": "soft",          "pron": "sóft"},
    {"pt": "duro",            "en": "hard",          "pron": "rárd"},
    {"pt": "liso",            "en": "smooth",        "pron": "smúth"},
    {"pt": "rugoso",          "en": "rough",         "pron": "ráf"},
    {"pt": "molhado",         "en": "wet",           "pron": "uét"},
    {"pt": "seco",            "en": "dry",           "pron": "drái"},
    {"pt": "quente",          "en": "hot",           "pron": "rót"},
    {"pt": "frio",            "en": "cold",          "pron": "kôuld"},
    {"pt": "pegajoso",        "en": "sticky",        "pron": "stíki"},
    {"pt": "escorregadio",    "en": "slippery",      "pron": "slíperi"},
    {"pt": "leve",            "en": "light",         "pron": "láit"},
    {"pt": "pesado",          "en": "heavy",         "pron": "révi"},
    {"pt": "fofo",            "en": "fluffy",        "pron": "fláfi"},
    {"pt": "brilhante",       "en": "shiny",         "pron": "sháini"},

    # Frases
    {"pt": "qual o tamanho?",         "en": "what size?",        "pron": "uót sáiz"},
    {"pt": "que tamanho você usa?",   "en": "what size do you wear?","pron": "uót sáiz du iu uér"},
    {"pt": "tem em outro tamanho?",   "en": "do you have another size?","pron": "du iu rév anáder sáiz"},
    {"pt": "tem em tamanho maior?",   "en": "do you have a bigger size?","pron": "du iu rév e bíguer sáiz"},
    {"pt": "tem em tamanho menor?",   "en": "do you have a smaller size?","pron": "du iu rév e smóler sáiz"},
    {"pt": "é muito grande",          "en": "it's too big",      "pron": "its tú bíg"},
    {"pt": "é muito pequeno",         "en": "it's too small",    "pron": "its tú smól"},
    {"pt": "é muito largo",           "en": "it's too loose",    "pron": "its tú lús"},
    {"pt": "é muito apertado",        "en": "it's too tight",    "pron": "its tú táit"},
    {"pt": "serve perfeitamente",     "en": "it fits perfectly", "pron": "it fíts pérfektli"},
    {"pt": "não serve",               "en": "it doesn't fit",    "pron": "it dáznt fít"},
    {"pt": "quanto pesa?",            "en": "how much does it weigh?","pron": "ráu mách dáz it uéi"},
    {"pt": "quanto mede?",            "en": "how big is it?",    "pron": "ráu bíg is it"},
    {"pt": "qual a altura?",          "en": "what's the height?","pron": "uóts de ráit"},
    {"pt": "qual a largura?",         "en": "what's the width?", "pron": "uóts de uít"},
    {"pt": "qual o comprimento?",     "en": "what's the length?","pron": "uóts de léngth"},
    {"pt": "qual a profundidade?",    "en": "what's the depth?", "pron": "uóts de déth"},
    {"pt": "que forma tem?",          "en": "what shape is it?","pron": "uót shéip is it"},
    {"pt": "é redondo",               "en": "it's round",        "pron": "its ráund"},
    {"pt": "é quadrado",              "en": "it's square",       "pron": "its skué r"},
    {"pt": "é do tamanho de uma bola","en": "it's the size of a ball","pron": "its de sáiz óv e ból"},
    {"pt": "mais ou menos isso",      "en": "about this much",   "pron": "abáut dis mách"},
    {"pt": "um pouco maior",          "en": "a bit bigger",      "pron": "e bít bíguer"},
    {"pt": "um pouco menor",          "en": "a bit smaller",     "pron": "e bít smóler"},
    {"pt": "do mesmo tamanho",        "en": "the same size",     "pron": "de séim sáiz"},
]

# ============ 🎵 MÚSICA E CINEMA (200) ============
midia = [
    # Música
    {"pt": "música",          "en": "music",         "pron": "miúsik"},
    {"pt": "canção",          "en": "song",          "pron": "song"},
    {"pt": "melodia",         "en": "melody",        "pron": "mélodi"},
    {"pt": "ritmo",           "en": "rhythm",        "pron": "ríthm"},
    {"pt": "letra",           "en": "lyrics",        "pron": "líriks"},
    {"pt": "refrão",          "en": "chorus",        "pron": "kóras"},
    {"pt": "verso",           "en": "verse",         "pron": "vérs"},
    {"pt": "acorde",          "en": "chord",         "pron": "kórd"},
    {"pt": "nota",            "en": "note",          "pron": "nôut"},
    {"pt": "batida",          "en": "beat",          "pron": "bít"},
    {"pt": "harmonia",        "en": "harmony",       "pron": "rármoni"},
    {"pt": "álbum",           "en": "album",         "pron": "élbam"},
    {"pt": "single",          "en": "single",        "pron": "síngol"},
    {"pt": "playlist",        "en": "playlist",      "pron": "pléilist"},
    {"pt": "concerto",        "en": "concert",       "pron": "kónsert"},
    {"pt": "show",            "en": "show",          "pron": "shôu"},
    {"pt": "turnê",           "en": "tour",          "pron": "túr"},
    {"pt": "festival",        "en": "festival",      "pron": "féstivol"},
    {"pt": "palco",           "en": "stage",         "pron": "stéidj"},
    {"pt": "plateia",         "en": "audience",      "pron": "ódians"},
    {"pt": "microfone",       "en": "microphone",    "pron": "máikrofôun"},
    {"pt": "instrumento",     "en": "instrument",    "pron": "ínstrument"},
    {"pt": "banda",           "en": "band",          "pron": "bénd"},
    {"pt": "orquestra",       "en": "orchestra",     "pron": "órkistra"},
    {"pt": "coral",           "en": "choir",         "pron": "kuáier"},

    # Instrumentos
    {"pt": "violão",          "en": "acoustic guitar","pron": "akústik gitár"},
    {"pt": "guitarra",        "en": "guitar",        "pron": "gitár"},
    {"pt": "guitarra elétrica","en": "electric guitar","pron": "eléktrik gitár"},
    {"pt": "baixo",           "en": "bass",          "pron": "béis"},
    {"pt": "bateria",         "en": "drums",         "pron": "dráms"},
    {"pt": "piano",           "en": "piano",         "pron": "piénou"},
    {"pt": "teclado",         "en": "keyboard",      "pron": "kíborg"},
    {"pt": "violino",         "en": "violin",        "pron": "váiolin"},
    {"pt": "violoncelo",      "en": "cello",         "pron": "chélou"},
    {"pt": "flauta",          "en": "flute",         "pron": "flút"},
    {"pt": "saxofone",        "en": "saxophone",     "pron": "séksofôun"},
    {"pt": "trompete",        "en": "trumpet",       "pron": "trámpit"},
    {"pt": "trombone",        "en": "trombone",      "pron": "trombôun"},
    {"pt": "clarinete",       "en": "clarinet",      "pron": "klarinét"},
    {"pt": "harpa",           "en": "harp",          "pron": "hárp"},
    {"pt": "acordeão",        "en": "accordion",     "pron": "akórdion"},
    {"pt": "cavaquinho",      "en": "ukulele",       "pron": "iukeléli"},
    {"pt": "pandeiro",        "en": "tambourine",    "pron": "témburín"},
    {"pt": "violão clássico", "en": "classical guitar","pron": "klásikol gitár"},

    # Gêneros
    {"pt": "rock",            "en": "rock",          "pron": "rók"},
    {"pt": "pop",             "en": "pop",           "pron": "póp"},
    {"pt": "jazz",            "en": "jazz",          "pron": "djéz"},
    {"pt": "blues",           "en": "blues",         "pron": "blús"},
    {"pt": "samba",           "en": "samba",         "pron": "sémba"},
    {"pt": "bossa nova",      "en": "bossa nova",    "pron": "bósa nóva"},
    {"pt": "forró",           "en": "forró",         "pron": "forró"},
    {"pt": "sertanejo",       "en": "country",       "pron": "kántri"},
    {"pt": "funk",            "en": "funk",          "pron": "fánk"},
    {"pt": "rap",             "en": "rap",           "pron": "rép"},
    {"pt": "hip hop",         "en": "hip hop",       "pron": "ríp róp"},
    {"pt": "reggae",          "en": "reggae",        "pron": "réguéi"},
    {"pt": "eletrônica",      "en": "electronic",    "pron": "elektrónik"},
    {"pt": "clássica",        "en": "classical",     "pron": "klásikol"},
    {"pt": "ópera",           "en": "opera",         "pron": "ópera"},
    {"pt": "gospel",          "en": "gospel",        "pron": "góspel"},
    {"pt": "pop rock",        "en": "pop rock",      "pron": "póp rók"},
    {"pt": "heavy metal",     "en": "heavy metal",   "pron": "révi métal"},
    {"pt": "punk",            "en": "punk",          "pron": "pánk"},
    {"pt": "indie",           "en": "indie",         "pron": "índi"},
    {"pt": "k-pop",           "en": "k-pop",         "pron": "kéi póp"},
    {"pt": "latin",           "en": "latin",         "pron": "létin"},

    # Cinema
    {"pt": "cinema",          "en": "cinema",        "pron": "sínema"},
    {"pt": "filme",           "en": "movie",         "pron": "múvi"},
    {"pt": "filme (cinema)",  "en": "film",          "pron": "fíl m"},
    {"pt": "série",           "en": "series",        "pron": "síris"},
    {"pt": "novela",          "en": "soap opera",    "pron": "sôup ópera"},
    {"pt": "documentário",    "en": "documentary",   "pron": "dokiuménteri"},
    {"pt": "animação",        "en": "animation",     "pron": "éniméishon"},
    {"pt": "desenho",         "en": "cartoon",       "pron": "kartún"},
    {"pt": "comédia",         "en": "comedy",        "pron": "kómedi"},
    {"pt": "drama",           "en": "drama",         "pron": "dráma"},
    {"pt": "terror",          "en": "horror",        "pron": "róror"},
    {"pt": "suspense",        "en": "thriller",      "pron": "thríler"},
    {"pt": "ação",            "en": "action",        "pron": "ékshon"},
    {"pt": "aventura",        "en": "adventure",     "pron": "edvénchur"},
    {"pt": "ficção científica","en": "science fiction","pron": "sáiens fíkshon"},
    {"pt": "fantasia",        "en": "fantasy",       "pron": "féntasi"},
    {"pt": "romance",         "en": "romance",       "pron": "roméns"},
    {"pt": "musical",         "en": "musical",       "pron": "miúsikol"},
    {"pt": "biografia",       "en": "biography",     "pron": "baiógrafi"},
    {"pt": "guerra",          "en": "war",           "pron": "uór"},
    {"pt": "faroeste",        "en": "western",       "pron": "uéstern"},
    {"pt": "policial",        "en": "crime",         "pron": "kráim"},

    # Produção
    {"pt": "diretor",         "en": "director",      "pron": "diréktor"},
    {"pt": "ator",            "en": "actor",         "pron": "éktor"},
    {"pt": "atriz",           "en": "actress",       "pron": "éktres"},
    {"pt": "elenco",          "en": "cast",          "pron": "kést"},
    {"pt": "personagem",      "en": "character",     "pron": "kérakter"},
    {"pt": "protagonista",    "en": "protagonist",   "pron": "protógonist"},
    {"pt": "vilão",           "en": "villain",       "pron": "vílein"},
    {"pt": "roteiro",         "en": "script",        "pron": "skrípt"},
    {"pt": "cenário",         "en": "scenery",       "pron": "síneri"},
    {"pt": "figurino",        "en": "costume",       "pron": "kóstum"},
    {"pt": "maquiagem",       "en": "makeup",        "pron": "méikap"},
    {"pt": "efeitos especiais","en": "special effects","pron": "spéshal ifékts"},
    {"pt": "trilha sonora",   "en": "soundtrack",    "pron": "sáundtrék"},
    {"pt": "cena",            "en": "scene",         "pron": "sín"},
    {"pt": "episódio",        "en": "episode",       "pron": "épisôud"},
    {"pt": "temporada",       "en": "season",        "pron": "sízon"},
    {"pt": "estreia",         "en": "premiere",      "pron": "primíer"},
    {"pt": "bilheteria",      "en": "box office",    "pron": "bóks ófis"},

    # TV
    {"pt": "televisão",       "en": "television",    "pron": "télevíjan"},
    {"pt": "canal",           "en": "channel",       "pron": "chénel"},
    {"pt": "programa",        "en": "program",       "pron": "prógram"},
    {"pt": "noticiário",      "en": "news",          "pron": "niús"},
    {"pt": "jornal",          "en": "newspaper",     "pron": "niúspéiper"},
    {"pt": "revista",         "en": "magazine",      "pron": "méguazin"},
    {"pt": "livro",           "en": "book",          "pron": "búk"},
    {"pt": "romance (livro)", "en": "novel",         "pron": "nóvel"},
    {"pt": "poesia",          "en": "poetry",        "pron": "póuetri"},
    {"pt": "conto",           "en": "short story",   "pron": "shórt stóri"},
    {"pt": "jornalista",      "en": "journalist",    "pron": "djérnalist"},
    {"pt": "apresentador",    "en": "host",          "pron": "rôust"},
    {"pt": "entrevista",      "en": "interview",     "pron": "ínterviu"},
    {"pt": "reportagem",      "en": "report",        "pron": "ripórt"},
    {"pt": "podcast",         "en": "podcast",       "pron": "pódkést"},

    # Internet/streaming
    {"pt": "streaming",       "en": "streaming",     "pron": "stríming"},
    {"pt": "assistir",        "en": "to watch",      "pron": "tu uóch"},
    {"pt": "ouvir",           "en": "to listen",     "pron": "tu lísan"},
    {"pt": "baixar",          "en": "to download",   "pron": "tu dáunloud"},
    {"pt": "compartilhar",    "en": "to share",      "pron": "tu shér"},
    {"pt": "curtir",          "en": "to like",       "pron": "tu láik"},
    {"pt": "seguir",          "en": "to follow",     "pron": "tu fólou"},
    {"pt": "inscrever-se",    "en": "to subscribe",  "pron": "tu sabs craib"},
    {"pt": "postar",          "en": "to post",       "pron": "tu pôust"},
    {"pt": "comentar",        "en": "to comment",    "pron": "tu kóment"},
    {"pt": "youtuber",        "en": "youtuber",      "pron": "iutúber"},
    {"pt": "influencer",      "en": "influencer",    "pron": "ínfluenser"},
    {"pt": "seguidor",        "en": "follower",      "pron": "fólouer"},
    {"pt": "live",            "en": "live",          "pron": "láiv"},
    {"pt": "vlog",            "en": "vlog",          "pron": "vlóg"},

    # Frases
    {"pt": "que música é essa?",   "en": "what song is this?","pron": "uót song is dis"},
    {"pt": "quem canta?",          "en": "who sings this?",  "pron": "rú síngs dis"},
    {"pt": "eu amo essa banda",    "en": "I love this band", "pron": "ái láv dis bénd"},
    {"pt": "que filme bom!",       "en": "what a good movie!","pron": "uót e gúd múvi"},
    {"pt": "já viu esse filme?",   "en": "have you seen this movie?","pron": "rév iu sín dis múvi"},
    {"pt": "vale a pena assistir?", "en": "is it worth watching?","pron": "is it uérth uóch ing"},
    {"pt": "é muito bom",          "en": "it's very good",   "pron": "its véri gúd"},
    {"pt": "não gostei",           "en": "I didn't like it", "pron": "ái dídnt láik it"},
    {"pt": "é hilário",            "en": "it's hilarious",   "pron": "its rilérias"},
    {"pt": "chorei assistindo",    "en": "I cried watching it","pron": "ái kráid uóch ing it"},
    {"pt": "qual sua banda favorita?","en": "what's your favorite band?","pron": "uóts iór féivorit bénd"},
    {"pt": "qual seu filme favorito?","en": "what's your favorite movie?","pron": "uóts iór féivorit múvi"},
    {"pt": "vamos ao cinema?",     "en": "let's go to the movies?","pron": "léts gôu tu de múvis"},
    {"pt": "tem legenda?",         "en": "does it have subtitles?","pron": "dáz it rév sábtaitols"},
    {"pt": "é dublado?",           "en": "is it dubbed?",    "pron": "is it dáb d"},
    {"pt": "em que canal passa?",  "en": "what channel is it on?","pron": "uót chénel is it ón"},
    {"pt": "que horas começa?",    "en": "what time does it start?","pron": "uót táim dáz it stárt"},
    {"pt": "quanto tempo dura?",   "en": "how long is it?",  "pron": "ráu long is it"},
    {"pt": "adorei!",              "en": "I loved it!",      "pron": "ái lávd it"},
    {"pt": "recomendo!",           "en": "I recommend it!",  "pron": "ái rekuménd it"},
]

# ============ ⚽ ESPORTES (200) ============
esportes = [
    # Esportes
    {"pt": "esporte",         "en": "sport",         "pron": "spórt"},
    {"pt": "futebol",         "en": "soccer",        "pron": "sóker"},
    {"pt": "futebol americano","en": "football",     "pron": "fútból"},
    {"pt": "basquete",        "en": "basketball",    "pron": "báskitból"},
    {"pt": "vôlei",           "en": "volleyball",    "pron": "vóliból"},
    {"pt": "tênis",           "en": "tennis",        "pron": "ténis"},
    {"pt": "tênis de mesa",   "en": "table tennis",  "pron": "téibol ténis"},
    {"pt": "natação",         "en": "swimming",      "pron": "suíming"},
    {"pt": "atletismo",       "en": "athletics",     "pron": "ethlétiks"},
    {"pt": "corrida",         "en": "running",       "pron": "ráning"},
    {"pt": "ciclismo",        "en": "cycling",       "pron": "sáikling"},
    {"pt": "boxe",            "en": "boxing",        "pron": "bóksing"},
    {"pt": "artes marciais",  "en": "martial arts",  "pron": "márshal árts"},
    {"pt": "judô",            "en": "judo",          "pron": "djúdou"},
    {"pt": "karatê",          "en": "karate",        "pron": "karáti"},
    {"pt": "jiu-jitsu",       "en": "jiu-jitsu",     "pron": "djú djútsu"},
    {"pt": "muay thai",       "en": "muay thai",     "pron": "muei tái"},
    {"pt": "ginástica",       "en": "gymnastics",    "pron": "djimnéstiks"},
    {"pt": "yoga",            "en": "yoga",          "pron": "iôuga"},
    {"pt": "pilates",         "en": "pilates",       "pron": "pilátis"},
    {"pt": "escalada",        "en": "climbing",      "pron": "kláiming"},
    {"pt": "surfe",           "en": "surfing",       "pron": "sérfing"},
    {"pt": "skate",           "en": "skateboarding", "pron": "skéitbórding"},
    {"pt": "patinação",       "en": "skating",       "pron": "skéiting"},
    {"pt": "esqui",           "en": "skiing",        "pron": "skíing"},
    {"pt": "hóquei",          "en": "hockey",        "pron": "róki"},
    {"pt": "golfe",           "en": "golf",          "pron": "gólf"},
    {"pt": "beisebol",        "en": "baseball",      "pron": "béisból"},
    {"pt": "rugby",           "en": "rugby",         "pron": "rágbi"},
    {"pt": "handebol",        "en": "handball",      "pron": "réndból"},
    {"pt": "badminton",       "en": "badminton",     "pron": "bédminton"},
    {"pt": "esgrima",         "en": "fencing",       "pron": "fénsing"},
    {"pt": "equitação",       "en": "horse riding",  "pron": "rórs ráiding"},
    {"pt": "pesca",           "en": "fishing",       "pron": "físhing"},
    {"pt": "caça",            "en": "hunting",       "pron": "ránting"},
    {"pt": "paraquedismo",    "en": "skydiving",     "pron": "skáidáiving"},
    {"pt": "mergulho",        "en": "diving",        "pron": "dáiving"},
    {"pt": "canoagem",        "en": "canoeing",      "pron": "kanúing"},
    {"pt": "vela",            "en": "sailing",       "pron": "séiling"},
    {"pt": "hipismo",         "en": "equestrian",    "pron": "ikuéstrian"},
    {"pt": "boliche",         "en": "bowling",       "pron": "bôuling"},
    {"pt": "sinuca",          "en": "billiards",     "pron": "bíliards"},
    {"pt": "damas",           "en": "checkers",      "pron": "chékers"},
    {"pt": "xadrez",          "en": "chess",         "pron": "chés"},
    {"pt": "pôquer",          "en": "poker",         "pron": "pôuker"},
    {"pt": "eSports",         "en": "eSports",       "pron": "í spórts"},

    # Pessoas
    {"pt": "atleta",          "en": "athlete",       "pron": "éthlit"},
    {"pt": "jogador",         "en": "player",        "pron": "pléier"},
    {"pt": "técnico",         "en": "coach",         "pron": "kôuch"},
    {"pt": "árbitro",         "en": "referee",       "pron": "réferi"},
    {"pt": "juiz",            "en": "judge",         "pron": "djáj"},
    {"pt": "torcedor",        "en": "fan",           "pron": "fén"},
    {"pt": "time",            "en": "team",          "pron": "tím"},
    {"pt": "capitão",         "en": "captain",       "pron": "képten"},
    {"pt": "goleiro",         "en": "goalkeeper",    "pron": "gôulkíper"},
    {"pt": "zagueiro",        "en": "defender",      "pron": "dífénder"},
    {"pt": "atacante",        "en": "forward",       "pron": "fórward"},
    {"pt": "meio-campista",   "en": "midfielder",    "pron": "mídfílder"},
    {"pt": "campeão",         "en": "champion",      "pron": "chém pion"},
    {"pt": "vice-campeão",    "en": "runner-up",     "pron": "ráner áp"},
    {"pt": "medalhista",      "en": "medalist",      "pron": "médalist"},

    # Competições
    {"pt": "jogo",            "en": "game",          "pron": "guéim"},
    {"pt": "partida",         "en": "match",         "pron": "métch"},
    {"pt": "campeonato",      "en": "championship",  "pron": "chém pionship"},
    {"pt": "torneio",         "en": "tournament",    "pron": "túrnament"},
    {"pt": "copa",            "en": "cup",           "pron": "káp"},
    {"pt": "olimpíadas",      "en": "Olympics",      "pron": "olím piks"},
    {"pt": "competição",      "en": "competition",   "pron": "kompetíshon"},
    {"pt": "treino",          "en": "training",      "pron": "tréining"},
    {"pt": "aquecimento",     "en": "warm-up",       "pron": "uórm áp"},
    {"pt": "eliminatória",    "en": "qualifier",     "pron": "kuólifáier"},
    {"pt": "final",           "en": "final",         "pron": "fáinal"},
    {"pt": "semifinal",       "en": "semifinal",     "pron": "semi fáinal"},
    {"pt": "quartas de final","en": "quarterfinals", "pron": "kuórterfáinals"},
    {"pt": "oitavas de final","en": "round of 16",   "pron": "ráund óv síkstín"},
    {"pt": "fase de grupos",  "en": "group stage",   "pron": "grúp stéidj"},
    {"pt": "prorrogação",     "en": "overtime",      "pron": "ôuvertáim"},
    {"pt": "pênalti",         "en": "penalty",       "pron": "pénalti"},
    {"pt": "falta",           "en": "foul",          "pron": "fául"},
    {"pt": "cartão amarelo",  "en": "yellow card",   "pron": "iélou kárd"},
    {"pt": "cartão vermelho", "en": "red card",      "pron": "réd kárd"},
    {"pt": "gol",             "en": "goal",          "pron": "gôul"},
    {"pt": "ponto",           "en": "point",         "pron": "póint"},
    {"pt": "placar",          "en": "score",         "pron": "skór"},
    {"pt": "empate",          "en": "tie",           "pron": "tái"},
    {"pt": "vitória",         "en": "victory",       "pron": "víktori"},
    {"pt": "derrota",         "en": "defeat",        "pron": "difít"},
    {"pt": "recorde",         "en": "record",        "pron": "rékord"},
    {"pt": "medalha de ouro", "en": "gold medal",    "pron": "gôuld médal"},
    {"pt": "medalha de prata","en": "silver medal",  "pron": "sílver médal"},
    {"pt": "medalha de bronze","en": "bronze medal", "pron": "brónz médal"},

    # Equipamento
    {"pt": "bola",            "en": "ball",          "pron": "ból"},
    {"pt": "raquete",         "en": "racket",        "pron": "rékit"},
    {"pt": "luva",            "en": "glove",         "pron": "gláv"},
    {"pt": "capacete",        "en": "helmet",        "pron": "rélmet"},
    {"pt": "uniforme",        "en": "uniform",       "pron": "iúniform"},
    {"pt": "camisa",          "en": "jersey",        "pron": "djérsi"},
    {"pt": "chuteira",        "en": "cleats",        "pron": "klíts"},
    {"pt": "tênis esportivo", "en": "sneakers",      "pron": "sníkers"},
    {"pt": "rede",            "en": "net",           "pron": "nét"},
    {"pt": "trave",           "en": "goalpost",      "pron": "gôulpôust"},
    {"pt": "cesta",           "en": "hoop",          "pron": "rúp"},
    {"pt": "taco",            "en": "bat",           "pron": "bét"},
    {"pt": "prancha",         "en": "board",         "pron": "bórd"},
    {"pt": "bastão",          "en": "stick",         "pron": "stík"},
    {"pt": "halteres",        "en": "dumbbells",     "pron": "dámbels"},
    {"pt": "corda",           "en": "rope",          "pron": "rôup"},
    {"pt": "apito",           "en": "whistle",       "pron": "uísol"},
    {"pt": "cronômetro",      "en": "stopwatch",     "pron": "stópuóch"},

    # Ações
    {"pt": "jogar",           "en": "to play",       "pron": "tu pléi"},
    {"pt": "treinar",         "en": "to train",      "pron": "tu tréin"},
    {"pt": "correr",          "en": "to run",        "pron": "tu rán"},
    {"pt": "nadar",           "en": "to swim",       "pron": "tu suím"},
    {"pt": "chutar",          "en": "to kick",       "pron": "tu kík"},
    {"pt": "arremessar",      "en": "to throw",      "pron": "tu thrôu"},
    {"pt": "pegar",           "en": "to catch",      "pron": "tu kéch"},
    {"pt": "marcar",          "en": "to score",      "pron": "tu skór"},
    {"pt": "ganhar",          "en": "to win",        "pron": "tu uín"},
    {"pt": "perder",          "en": "to lose",       "pron": "tu lúz"},
    {"pt": "empatar",         "en": "to tie",        "pron": "tu tái"},
    {"pt": "vencer",          "en": "to defeat",     "pron": "tu difít"},
    {"pt": "competir",        "en": "to compete",    "pron": "tu kompet"},
    {"pt": "aquecer",         "en": "to warm up",    "pron": "tu uórm áp"},
    {"pt": "alongar",         "en": "to stretch",    "pron": "tu strétch"},
    {"pt": "descansar",       "en": "to rest",       "pron": "tu rést"},
    {"pt": "treinar (peso)",  "en": "to lift",       "pron": "tu líft"},
    {"pt": "pedalar",         "en": "to pedal",      "pron": "tu pédal"},
    {"pt": "escalar",         "en": "to climb",      "pron": "tu kláim"},
    {"pt": "mergulhar",       "en": "to dive",       "pron": "tu dáiv"},
    {"pt": "surfar",          "en": "to surf",       "pron": "tu sérf"},
    {"pt": "patinar",         "en": "to skate",      "pron": "tu skéit"},
    {"pt": "esquiar",         "en": "to ski",        "pron": "tu skí"},
    {"pt": "torcer",          "en": "to cheer",      "pron": "tu chír"},

    # Locais
    {"pt": "estádio",         "en": "stadium",       "pron": "stéidium"},
    {"pt": "quadra",          "en": "court",         "pron": "kórt"},
    {"pt": "campo",           "en": "field",         "pron": "fíld"},
    {"pt": "ginásio",         "en": "gymnasium",     "pron": "djimnézium"},
    {"pt": "piscina",         "en": "pool",          "pron": "púl"},
    {"pt": "pista",           "en": "track",         "pron": "trék"},
    {"pt": "academia",        "en": "gym",           "pron": "djím"},
    {"pt": "vestiário",       "en": "locker room",   "pron": "lóker rúm"},
    {"pt": "arquibancada",    "en": "bleachers",     "pron": "blíchers"},
    {"pt": "ringue",          "en": "ring",          "pron": "ríng"},
    {"pt": "tatame",          "en": "mat",           "pron": "mét"},
    {"pt": "montanha",        "en": "mountain",      "pron": "máunten"},
    {"pt": "praia",           "en": "beach",         "pron": "bích"},
    {"pt": "parque",          "en": "park",          "pron": "párk"},

    # Frases
    {"pt": "você gosta de futebol?","en": "do you like soccer?","pron": "du iu láik sóker"},
    {"pt": "quem ganhou?",        "en": "who won?",         "pron": "rú uán"},
    {"pt": "qual o placar?",      "en": "what's the score?", "pron": "uóts de skór"},
    {"pt": "quando é o jogo?",    "en": "when is the game?", "pron": "uén is de guéim"},
    {"pt": "que horas começa?",   "en": "what time does it start?","pron": "uót táim dáz it stárt"},
    {"pt": "qual o seu time?",    "en": "what's your team?", "pron": "uóts iór tím"},
    {"pt": "sou torcedor do...",  "en": "I'm a fan of...",   "pron": "áim e fén óv"},
    {"pt": "torço pro...",        "en": "I root for...",     "pron": "ái rút fór"},
    {"pt": "vamos ganhar!",       "en": "we're going to win!","pron": "uír góuing tu uín"},
    {"pt": "que jogo emocionante!","en": "what an exciting game!","pron": "uót en eksáiting guéim"},
    {"pt": "foi incrível",        "en": "it was amazing",    "pron": "it uós améizing"},
    {"pt": "que pena!",           "en": "what a pity!",      "pron": "uót e píti"},
    {"pt": "ele é muito bom",     "en": "he's very good",    "pron": "ríz véri gúd"},
    {"pt": "joga bem",            "en": "plays well",        "pron": "pléis uél"},
    {"pt": "estou treinando",     "en": "I'm training",      "pron": "áim tréining"},
    {"pt": "vou à academia",      "en": "I go to the gym",   "pron": "ái gôu tu de djím"},
    {"pt": "faço musculação",     "en": "I lift weights",    "pron": "ái líft uéits"},
    {"pt": "corro todos os dias", "en": "I run every day",   "pron": "ái rán évri déi"},
    {"pt": "jogo bola com amigos","en": "I play soccer with friends","pron": "ái pléi sóker uíth frénds"},
    {"pt": "vamos jogar?",        "en": "want to play?",     "pron": "uónt tu pléi"},
    {"pt": "topa um futebol?",    "en": "up for some soccer?","pron": "áp fór sám sóker"},
    {"pt": "sou faixa preta",     "en": "I'm a black belt",  "pron": "áim e blék bélt"},
    {"pt": "pratico yoga",        "en": "I do yoga",         "pron": "ái dú iôuga"},
    {"pt": "faço natação",        "en": "I swim",            "pron": "ái suím"},
    {"pt": "malho há anos",       "en": "I've worked out for years","pron": "áiv uórkt áut fór íers"},
]

# ============ ✈️ VIAGEM (200) ============
viagem = [
    # Planejamento
    {"pt": "viagem",          "en": "trip",          "pron": "tríp"},
    {"pt": "viagem (jornada)","en": "travel",        "pron": "trévol"},
    {"pt": "férias",          "en": "vacation",      "pron": "vekéishon"},
    {"pt": "feriado",         "en": "holiday",       "pron": "rólidei"},
    {"pt": "passaporte",      "en": "passport",      "pron": "péspourt"},
    {"pt": "visto",           "en": "visa",          "pron": "víza"},
    {"pt": "documento",       "en": "document",      "pron": "dókiument"},
    {"pt": "identidade",      "en": "ID",            "pron": "ái dí"},
    {"pt": "passagem",        "en": "ticket",        "pron": "tíkit"},
    {"pt": "reserva",         "en": "reservation",   "pron": "rezervéishon"},
    {"pt": "seguro viagem",   "en": "travel insurance","pron": "trévol inshúrans"},
    {"pt": "roteiro",         "en": "itinerary",     "pron": "aitíneréri"},
    {"pt": "mala",            "en": "suitcase",      "pron": "sútkeis"},
    {"pt": "mochila",         "en": "backpack",      "pron": "békpék"},
    {"pt": "bagagem de mão",  "en": "carry-on",      "pron": "kéri ón"},
    {"pt": "guia",            "en": "guide",         "pron": "gáid"},
    {"pt": "mapa",            "en": "map",           "pron": "mép"},
    {"pt": "guia turístico",  "en": "guidebook",     "pron": "gáidbúk"},
    {"pt": "turista",         "en": "tourist",       "pron": "túrist"},
    {"pt": "viajante",        "en": "traveler",      "pron": "trévoler"},

    # Aeroporto
    {"pt": "aeroporto",       "en": "airport",       "pron": "érport"},
    {"pt": "voo",             "en": "flight",        "pron": "fláit"},
    {"pt": "voo direto",      "en": "direct flight", "pron": "dirékt fláit"},
    {"pt": "voo com conexão", "en": "connecting flight","pron": "konékting fláit"},
    {"pt": "escala",          "en": "layover",       "pron": "léiôuver"},
    {"pt": "check-in",        "en": "check-in",      "pron": "chék ín"},
    {"pt": "embarque",        "en": "boarding",      "pron": "bórding"},
    {"pt": "cartão de embarque","en": "boarding pass","pron": "bórding pés"},
    {"pt": "portão",          "en": "gate",          "pron": "guéit"},
    {"pt": "poltrona",        "en": "seat",          "pron": "sít"},
    {"pt": "corredor",        "en": "aisle",         "pron": "áil"},
    {"pt": "janela",          "en": "window",        "pron": "uíndou"},
    {"pt": "bagagem",         "en": "luggage",       "pron": "lágidj"},
    {"pt": "esteira",         "en": "conveyor belt", "pron": "konvéior bélt"},
    {"pt": "alfândega",       "en": "customs",       "pron": "ká stoms"},
    {"pt": "imigração",       "en": "immigration",   "pron": "imigréishon"},
    {"pt": "passaporte",      "en": "passport control","pron": "péspourt kontrol"},
    {"pt": "raio-x",          "en": "x-ray",         "pron": "éks réi"},
    {"pt": "detector de metal","en": "metal detector","pron": "métal ditéktor"},
    {"pt": "atraso",          "en": "delay",         "pron": "diléi"},
    {"pt": "cancelado",       "en": "canceled",      "pron": "kénseld"},
    {"pt": "turbulência",     "en": "turbulence",    "pron": "térbiulens"},
    {"pt": "piloto",          "en": "pilot",         "pron": "páilot"},
    {"pt": "comissário",      "en": "flight attendant","pron": "fláit eténdant"},
    {"pt": "primeira classe", "en": "first class",   "pron": "férst klés"},
    {"pt": "classe executiva", "en": "business class","pron": "bíznis klés"},
    {"pt": "classe econômica","en": "economy class", "pron": "ikónomi klés"},

    # Hotel
    {"pt": "hotel",           "en": "hotel",         "pron": "routél"},
    {"pt": "pousada",         "en": "inn",           "pron": "ín"},
    {"pt": "hostel",          "en": "hostel",        "pron": "róstel"},
    {"pt": "resort",          "en": "resort",        "pron": "rizórt"},
    {"pt": "quarto",          "en": "room",          "pron": "rúm"},
    {"pt": "quarto individual","en": "single room",  "pron": "síngol rúm"},
    {"pt": "quarto duplo",    "en": "double room",   "pron": "dábol rúm"},
    {"pt": "quarto de casal", "en": "double bed room","pron": "dábol béd rúm"},
    {"pt": "suíte",           "en": "suite",         "pron": "suít"},
    {"pt": "recepcionista",   "en": "receptionist",  "pron": "risépshanist"},
    {"pt": "chave",           "en": "key",           "pron": "kí"},
    {"pt": "cartão-chave",    "en": "key card",      "pron": "kí kárd"},
    {"pt": "elevador",        "en": "elevator",      "pron": "éleveitor"},
    {"pt": "café da manhã",   "en": "breakfast",     "pron": "brékfast"},
    {"pt": "meia-pensão",     "en": "half board",    "pron": "réf bórd"},
    {"pt": "pensão completa", "en": "full board",    "pron": "fúl bórd"},
    {"pt": "check-out",       "en": "check-out",     "pron": "chék áut"},
    {"pt": "conta",           "en": "bill",          "pron": "bíl"},
    {"pt": "toalha",          "en": "towel",         "pron": "táuel"},
    {"pt": "sabonete",        "en": "soap",          "pron": "sôup"},
    {"pt": "ar-condicionado", "en": "air conditioning","pron": "ér kondíshoning"},
    {"pt": "wi-fi",           "en": "wi-fi",         "pron": "uáifái"},

    # Transporte local
    {"pt": "táxi",            "en": "taxi",          "pron": "téksi"},
    {"pt": "ônibus",          "en": "bus",           "pron": "bás"},
    {"pt": "metrô",           "en": "subway",        "pron": "sábuei"},
    {"pt": "trem",            "en": "train",         "pron": "tréin"},
    {"pt": "aluguel de carro","en": "car rental",    "pron": "kár réntal"},
    {"pt": "aplicativo",      "en": "app",           "pron": "ép"},
    {"pt": "motorista",       "en": "driver",        "pron": "dráiver"},
    {"pt": "passageiro",      "en": "passenger",     "pron": "pésendjer"},
    {"pt": "bilhete",         "en": "ticket",        "pron": "tíkit"},
    {"pt": "mapa",            "en": "map",           "pron": "mép"},
    {"pt": "ponto de ônibus", "en": "bus stop",      "pron": "bás stóp"},
    {"pt": "estação",         "en": "station",       "pron": "stéishon"},
    {"pt": "aluguel de bike", "en": "bike rental",   "pron": "báik réntal"},
    {"pt": "caminhada",       "en": "walk",          "pron": "uók"},
    {"pt": "trânsito",        "en": "traffic",       "pron": "tréfik"},

    # Turismo
    {"pt": "atração",         "en": "attraction",    "pron": "atrékshon"},
    {"pt": "ponto turístico", "en": "tourist spot",  "pron": "túrist spót"},
    {"pt": "museu",           "en": "museum",        "pron": "miuzíum"},
    {"pt": "monumento",       "en": "monument",      "pron": "móniument"},
    {"pt": "igreja",          "en": "church",        "pron": "chérch"},
    {"pt": "castelo",         "en": "castle",        "pron": "késol"},
    {"pt": "praça",           "en": "square",        "pron": "skué r"},
    {"pt": "parque",          "en": "park",          "pron": "párk"},
    {"pt": "praia",           "en": "beach",         "pron": "bích"},
    {"pt": "montanha",        "en": "mountain",      "pron": "máunten"},
    {"pt": "cidade histórica","en": "historic town", "pron": "ristórik táun"},
    {"pt": "tour guiado",     "en": "guided tour",   "pron": "gáidid túr"},
    {"pt": "ingresso",        "en": "entrance ticket","pron": "éntrens tíkit"},
    {"pt": "lembrança",       "en": "souvenir",      "pron": "suvinír"},
    {"pt": "foto",            "en": "photo",         "pron": "fôutou"},
    {"pt": "selfie",          "en": "selfie",        "pron": "sélfi"},
    {"pt": "museu de arte",   "en": "art museum",    "pron": "árt miuzíum"},
    {"pt": "vista",           "en": "view",          "pron": "viú"},
    {"pt": "mirante",         "en": "viewpoint",     "pron": "viúpoint"},
    {"pt": "horário de funcionamento","en": "opening hours","pron": "ôupening áuers"},

    # Restaurante (viagem)
    {"pt": "restaurante",     "en": "restaurant",    "pron": "réstorant"},
    {"pt": "cardápio",        "en": "menu",          "pron": "ményu"},
    {"pt": "conta",           "en": "bill",          "pron": "bíl"},
    {"pt": "gorjeta",         "en": "tip",           "pron": "típ"},
    {"pt": "prato típico",    "en": "local dish",    "pron": "lôukol dísh"},
    {"pt": "comida local",    "en": "local food",    "pron": "lôukol fúd"},
    {"pt": "recomendação",    "en": "recommendation","pron": "rekumendéishon"},
    {"pt": "para viagem",     "en": "to go",         "pron": "tu gôu"},
    {"pt": "sem gelo",        "en": "no ice",        "pron": "nôu áis"},
    {"pt": "vegetariano",     "en": "vegetarian",    "pron": "vedjetérion"},
    {"pt": "alérgico a",      "en": "allergic to",   "pron": "alérdjik tu"},

    # Dinheiro e compras
    {"pt": "dinheiro",        "en": "money",         "pron": "máni"},
    {"pt": "câmbio",          "en": "exchange",      "pron": "ekstchéindj"},
    {"pt": "casa de câmbio",  "en": "exchange office","pron": "ekstchéindj ófis"},
    {"pt": "caixa eletrônico","en": "ATM",           "pron": "ei ti ém"},
    {"pt": "cartão de crédito","en": "credit card",  "pron": "krédit kárd"},
    {"pt": "dinheiro em espécie","en": "cash",       "pron": "késh"},
    {"pt": "recibo",          "en": "receipt",       "pron": "risít"},
    {"pt": "imposto",         "en": "tax",           "pron": "téks"},
    {"pt": "tax free",        "en": "tax free",      "pron": "téks frí"},
    {"pt": "gorjeta",         "en": "tip",           "pron": "típ"},

    # Saúde em viagem
    {"pt": "farmácia",        "en": "pharmacy",      "pron": "fármasi"},
    {"pt": "hospital",        "en": "hospital",      "pron": "róspital"},
    {"pt": "médico",          "en": "doctor",        "pron": "dóktor"},
    {"pt": "remédio",         "en": "medicine",      "pron": "mésdisin"},
    {"pt": "receita médica",  "en": "prescription",  "pron": "priskrípshon"},
    {"pt": "dor de cabeça",   "en": "headache",      "pron": "rédeik"},
    {"pt": "dor de barriga",  "en": "stomachache",   "pron": "stómakéik"},
    {"pt": "enjoo",           "en": "nausea",        "pron": "nózia"},
    {"pt": "emergência",      "en": "emergency",     "pron": "imérdjensi"},
    {"pt": "ambulância",      "en": "ambulance",     "pron": "émbiulans"},

    # Frases
    {"pt": "onde fica o banheiro?","en": "where is the bathroom?","pron": "uér is de béthrum"},
    {"pt": "onde fica o hotel?",   "en": "where is the hotel?","pron": "uér is de routél"},
    {"pt": "onde é a estação?",    "en": "where is the station?","pron": "uér is de stéishon"},
    {"pt": "quanto custa?",        "en": "how much does it cost?","pron": "ráu mách dáz it kóst"},
    {"pt": "aceita cartão?",       "en": "do you accept cards?","pron": "du iu aksépt kárds"},
    {"pt": "onde posso trocar dinheiro?","en": "where can I exchange money?","pron": "uér kén ái ekstchéindj máni"},
    {"pt": "pode me ajudar?",      "en": "can you help me?", "pron": "kén iu rélp mi"},
    {"pt": "estou perdido",        "en": "I'm lost",         "pron": "áim lóst"},
    {"pt": "falo pouco inglês",    "en": "I speak a little English","pron": "ái spík e lítol ínglish"},
    {"pt": "pode falar devagar?",  "en": "can you speak slowly?","pron": "kén iu spík slôuli"},
    {"pt": "quanto tempo demora?", "en": "how long does it take?","pron": "ráu long dáz it téik"},
    {"pt": "é longe daqui?",       "en": "is it far from here?","pron": "is it fár from rír"},
    {"pt": "que horas abre?",      "en": "what time does it open?","pron": "uót táim dáz it ôupen"},
    {"pt": "que horas fecha?",     "en": "what time does it close?","pron": "uót táim dáz it klôuz"},
    {"pt": "tem wifi aqui?",       "en": "is there wifi here?","pron": "is dér uáifái rír"},
    {"pt": "qual a senha do wifi?","en": "what's the wifi password?","pron": "uóts de uáifái péssuord"},
    {"pt": "posso tirar uma foto?","en": "can I take a picture?","pron": "kén ái téik e píkcher"},
    {"pt": "pode tirar uma foto minha?","en": "can you take a picture of me?","pron": "kén iu téik e píkcher óv mi"},
    {"pt": "que lugar lindo!",     "en": "what a beautiful place!","pron": "uót e biútiful pléis"},
    {"pt": "estou adorando a viagem","en": "I'm loving the trip","pron": "áim láving de tríp"},
    {"pt": "foi uma viagem incrível","en": "it was an amazing trip","pron": "it uós en améizing tríp"},
    {"pt": "quero voltar",         "en": "I want to come back","pron": "ái uónt tu kám bék"},
    {"pt": "recomendo visitar",    "en": "I recommend visiting","pron": "ái rekuménd vísiting"},
    {"pt": "vale muito a pena",    "en": "it's really worth it","pron": "its ríli uérth it"},
]

# ============ ESCREVER ============
modulos = {
    "corpo":    corpo,
    "horas":    horas,
    "formas":   formas,
    "midia":    midia,
    "esportes": esportes,
    "viagem":   viagem,
}

for nome, dados in modulos.items():
    caminho = PASTA / f"{nome}.json"
    with open(caminho, "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=2)
    print(f"OK: {nome}.json ({len(dados)} itens)")

print()
print("=" * 50)
print("Lote 3 (Avancado) preenchido com sucesso!")
print("Reinicie o Streamlit pra ver o conteudo.")
print("=" * 50)