import json
from pathlib import Path

BASE = Path(__file__).parent
PASTA = BASE / "dados" / "ingles"

# ============ 🔤 VERBOS ESSENCIAIS (150) ============
verbos = [
    # Ser/estar/ter
    {"pt": "ser",            "en": "to be",          "pron": "tu bí"},
    {"pt": "estar",          "en": "to be",          "pron": "tu bí"},
    {"pt": "ter",            "en": "to have",        "pron": "tu rév"},
    {"pt": "haver",          "en": "there is",       "pron": "dér is"},
    {"pt": "existir",        "en": "to exist",       "pron": "tu egzíst"},
    {"pt": "possuir",        "en": "to own",         "pron": "tu ôun"},
    {"pt": "estar com",      "en": "to have on",     "pron": "tu rév ón"},

    # Movimento
    {"pt": "ir",             "en": "to go",          "pron": "tu gôu"},
    {"pt": "vir",            "en": "to come",        "pron": "tu kám"},
    {"pt": "chegar",         "en": "to arrive",      "pron": "tu aráiv"},
    {"pt": "sair",           "en": "to leave",       "pron": "tu lív"},
    {"pt": "voltar",         "en": "to return",      "pron": "tu ritérn"},
    {"pt": "entrar",         "en": "to enter",       "pron": "tu énter"},
    {"pt": "subir",          "en": "to go up",       "pron": "tu gôu áp"},
    {"pt": "descer",         "en": "to go down",     "pron": "tu gôu dáun"},
    {"pt": "correr",         "en": "to run",         "pron": "tu rán"},
    {"pt": "andar",          "en": "to walk",        "pron": "tu uók"},
    {"pt": "dirigir",        "en": "to drive",       "pron": "tu dráiv"},
    {"pt": "voar",           "en": "to fly",         "pron": "tu flái"},
    {"pt": "nadar",          "en": "to swim",        "pron": "tu suím"},
    {"pt": "pular",          "en": "to jump",        "pron": "tu djámp"},
    {"pt": "dançar",         "en": "to dance",       "pron": "tu déns"},
    {"pt": "cair",           "en": "to fall",        "pron": "tu fól"},
    {"pt": "levantar",       "en": "to lift",        "pron": "tu líft"},
    {"pt": "empurrar",       "en": "to push",        "pron": "tu púsh"},
    {"pt": "puxar",          "en": "to pull",        "pron": "tu púl"},
    {"pt": "carregar",       "en": "to carry",       "pron": "tu kéri"},
    {"pt": "correr (apressar)","en": "to rush",      "pron": "tu rásh"},
    {"pt": "caminhar",       "en": "to stroll",      "pron": "tu strôul"},
    {"pt": "passear",        "en": "to take a walk", "pron": "tu téik e uók"},

    # Ações básicas
    {"pt": "fazer",          "en": "to do",          "pron": "tu dú"},
    {"pt": "fazer (criar)",  "en": "to make",        "pron": "tu méik"},
    {"pt": "querer",         "en": "to want",        "pron": "tu uónt"},
    {"pt": "precisar",       "en": "to need",        "pron": "tu níd"},
    {"pt": "poder",          "en": "can",            "pron": "kén"},
    {"pt": "conseguir",      "en": "to manage",      "pron": "tu ménedj"},
    {"pt": "saber",          "en": "to know",        "pron": "tu nôu"},
    {"pt": "conhecer",       "en": "to meet",        "pron": "tu mít"},
    {"pt": "gostar",         "en": "to like",        "pron": "tu láik"},
    {"pt": "amar",           "en": "to love",        "pron": "tu láv"},
    {"pt": "odiar",          "en": "to hate",        "pron": "tu réit"},
    {"pt": "preferir",       "en": "to prefer",      "pron": "tu prifér"},
    {"pt": "escolher",       "en": "to choose",      "pron": "tu chúz"},
    {"pt": "decidir",        "en": "to decide",      "pron": "tu dissáid"},
    {"pt": "tentar",         "en": "to try",         "pron": "tu trái"},
    {"pt": "conseguir",      "en": "to succeed",     "pron": "tu saksíd"},
    {"pt": "falhar",         "en": "to fail",        "pron": "tu féil"},
    {"pt": "começar",        "en": "to start",       "pron": "tu stárt"},
    {"pt": "terminar",       "en": "to finish",      "pron": "tu fínish"},
    {"pt": "continuar",      "en": "to continue",    "pron": "tu kontíniu"},
    {"pt": "parar",          "en": "to stop",        "pron": "tu stóp"},

    # Comunicação
    {"pt": "falar",          "en": "to speak",       "pron": "tu spík"},
    {"pt": "dizer",          "en": "to say",         "pron": "tu séi"},
    {"pt": "contar",         "en": "to tell",        "pron": "tu tél"},
    {"pt": "perguntar",      "en": "to ask",         "pron": "tu ésk"},
    {"pt": "responder",      "en": "to answer",      "pron": "tu énsar"},
    {"pt": "ouvir",          "en": "to listen",      "pron": "tu lísan"},
    {"pt": "escutar",        "en": "to hear",        "pron": "tu rír"},
    {"pt": "ver",            "en": "to see",         "pron": "tu sí"},
    {"pt": "olhar",          "en": "to look",        "pron": "tu lúk"},
    {"pt": "ler",            "en": "to read",        "pron": "tu ríd"},
    {"pt": "escrever",       "en": "to write",       "pron": "tu ráit"},
    {"pt": "estudar",        "en": "to study",       "pron": "tu stádi"},
    {"pt": "aprender",       "en": "to learn",       "pron": "tu lérn"},
    {"pt": "ensinar",        "en": "to teach",       "pron": "tu tích"},
    {"pt": "explicar",       "en": "to explain",     "pron": "tu ekspléin"},
    {"pt": "traduzir",       "en": "to translate",   "pron": "tu trénsleit"},
    {"pt": "chamar",         "en": "to call",        "pron": "tu kól"},
    {"pt": "conversar",      "en": "to talk",        "pron": "tu tók"},
    {"pt": "gritar",         "en": "to shout",       "pron": "tu sháut"},
    {"pt": "sussurrar",      "en": "to whisper",     "pron": "tu uísper"},
    {"pt": "concordar",      "en": "to agree",       "pron": "tu agrí"},
    {"pt": "discordar",      "en": "to disagree",    "pron": "tu disagric"},
    {"pt": "prometer",       "en": "to promise",     "pron": "tu prómis"},
    {"pt": "avisar",         "en": "to warn",        "pron": "tu uórn"},
    {"pt": "mentir",         "en": "to lie",         "pron": "tu lái"},
    {"pt": "reclamar",       "en": "to complain",    "pron": "tu kompléin"},

    # Vida diária
    {"pt": "comer",          "en": "to eat",         "pron": "tu ít"},
    {"pt": "beber",          "en": "to drink",       "pron": "tu drínk"},
    {"pt": "dormir",         "en": "to sleep",       "pron": "tu slíp"},
    {"pt": "acordar",        "en": "to wake up",     "pron": "tu uéik áp"},
    {"pt": "levantar-se",    "en": "to get up",      "pron": "tu guét áp"},
    {"pt": "trabalhar",      "en": "to work",        "pron": "tu uórk"},
    {"pt": "descansar",      "en": "to rest",        "pron": "tu rést"},
    {"pt": "brincar",        "en": "to play",        "pron": "tu pléi"},
    {"pt": "jogar",          "en": "to play",        "pron": "tu pléi"},
    {"pt": "ganhar",         "en": "to win",         "pron": "tu uín"},
    {"pt": "perder",         "en": "to lose",        "pron": "tu lúz"},
    {"pt": "ganhar (receber)","en": "to earn",       "pron": "tu érn"},
    {"pt": "cuidar",         "en": "to take care",   "pron": "tu téik kér"},
    {"pt": "ajudar",         "en": "to help",        "pron": "tu rélp"},
    {"pt": "usar",           "en": "to use",         "pron": "tu iús"},
    {"pt": "vestir",         "en": "to wear",        "pron": "tu uér"},
    {"pt": "tirar (roupa)",  "en": "to take off",    "pron": "tu téik óf"},
    {"pt": "colocar",        "en": "to put",         "pron": "tu pút"},
    {"pt": "guardar",        "en": "to keep",        "pron": "tu kíp"},
    {"pt": "limpar",         "en": "to clean",       "pron": "tu klín"},
    {"pt": "lavar",          "en": "to wash",        "pron": "tu uósh"},
    {"pt": "cozinhar",       "en": "to cook",        "pron": "tu kúk"},
    {"pt": "cortar",         "en": "to cut",         "pron": "tu kát"},
    {"pt": "abrir",          "en": "to open",        "pron": "tu ôupen"},
    {"pt": "fechar",         "en": "to close",       "pron": "tu klôuz"},

    # Compras/ações
    {"pt": "comprar",        "en": "to buy",         "pron": "tu bái"},
    {"pt": "vender",         "en": "to sell",        "pron": "tu sél"},
    {"pt": "pagar",          "en": "to pay",         "pron": "tu péi"},
    {"pt": "dar",            "en": "to give",        "pron": "tu guív"},
    {"pt": "receber",        "en": "to receive",     "pron": "tu risív"},
    {"pt": "trocar",         "en": "to exchange",    "pron": "tu ekstchéindj"},
    {"pt": "procurar",       "en": "to look for",    "pron": "tu lúk fór"},
    {"pt": "encontrar",      "en": "to find",        "pron": "tu fáind"},
    {"pt": "perder (objeto)","en": "to lose",        "pron": "tu lúz"},
    {"pt": "achar",          "en": "to think",       "pron": "tu thínk"},

    # Emoções mentais
    {"pt": "pensar",         "en": "to think",       "pron": "tu thínk"},
    {"pt": "acreditar",      "en": "to believe",     "pron": "tu bilív"},
    {"pt": "sentir",         "en": "to feel",        "pron": "tu fíl"},
    {"pt": "lembrar",        "en": "to remember",    "pron": "tu rimémber"},
    {"pt": "esquecer",       "en": "to forget",      "pron": "tu forgét"},
    {"pt": "entender",       "en": "to understand",  "pron": "tu ándersténd"},
    {"pt": "imaginar",       "en": "to imagine",     "pron": "tu imédjin"},
    {"pt": "esperar",        "en": "to hope",        "pron": "tu rôup"},
    {"pt": "esperar (aguardar)","en": "to wait",     "pron": "tu uéit"},
    {"pt": "rir",            "en": "to laugh",       "pron": "tu léf"},
    {"pt": "chorar",         "en": "to cry",         "pron": "tu krái"},
    {"pt": "sorrir",         "en": "to smile",       "pron": "tu smáil"},
    {"pt": "sonhar",         "en": "to dream",       "pron": "tu drím"},

    # Phrasal verbs comuns
    {"pt": "levantar-se (cama)","en": "to get up",   "pron": "tu guét áp"},
    {"pt": "sair (passear)", "en": "to go out",      "pron": "tu gôu áut"},
    {"pt": "voltar (retornar)","en": "to come back", "pron": "tu kám bék"},
    {"pt": "desistir",       "en": "to give up",     "pron": "tu guív áp"},
    {"pt": "continuar",      "en": "to go on",       "pron": "tu gôu ón"},
    {"pt": "procurar",       "en": "to look for",    "pron": "tu lúk fór"},
    {"pt": "cuidar de",      "en": "to look after",  "pron": "tu lúk áfter"},
    {"pt": "esperar",        "en": "to look forward","pron": "tu lúk fórward"},
    {"pt": "descobrir",      "en": "to find out",    "pron": "tu fáind áut"},
    {"pt": "preencher",      "en": "to fill in",     "pron": "tu fíl ín"},
    {"pt": "desligar",       "en": "to turn off",    "pron": "tu térn óf"},
    {"pt": "ligar",          "en": "to turn on",     "pron": "tu térn ón"},
    {"pt": "pegar (apanhar)", "en": "to pick up",    "pron": "tu pík áp"},
    {"pt": "deixar (largar)", "en": "to put down",   "pron": "tu pút dáun"},
    {"pt": "crescer",        "en": "to grow up",     "pron": "tu grôu áp"},
    {"pt": "cair (briga)",   "en": "to fall out",    "pron": "tu fól áut"},

    # Frases com verbos
    {"pt": "eu quero",       "en": "I want",         "pron": "ái uónt"},
    {"pt": "eu preciso",     "en": "I need",         "pron": "ái níd"},
    {"pt": "eu posso",       "en": "I can",          "pron": "ái kén"},
    {"pt": "eu vou",         "en": "I'm going to",   "pron": "áim góuing tu"},
    {"pt": "eu gosto de",    "en": "I like to",      "pron": "ái láik tu"},
    {"pt": "eu sei",         "en": "I know",         "pron": "ái nôu"},
    {"pt": "eu acho que",    "en": "I think that",   "pron": "ái thínk dét"},
    {"pt": "eu entendo",     "en": "I understand",   "pron": "ái ándersténd"},
    {"pt": "não sei",        "en": "I don't know",   "pron": "ái dônt nôu"},
    {"pt": "não entendo",    "en": "I don't understand","pron": "ái dônt ándersténd"},
    {"pt": "não consigo",    "en": "I can't",        "pron": "ái ként"},
]

# ============ ❓ PERGUNTAS (150) ============
perguntas = [
    # Palavras interrogativas
    {"pt": "quem?",             "en": "who?",          "pron": "rú"},
    {"pt": "o que?",            "en": "what?",         "pron": "uót"},
    {"pt": "onde?",             "en": "where?",        "pron": "uér"},
    {"pt": "quando?",           "en": "when?",         "pron": "uén"},
    {"pt": "por que?",          "en": "why?",          "pron": "uái"},
    {"pt": "como?",             "en": "how?",          "pron": "ráu"},
    {"pt": "qual?",             "en": "which?",        "pron": "uích"},
    {"pt": "quanto?",           "en": "how much?",     "pron": "ráu mách"},
    {"pt": "quantos?",          "en": "how many?",     "pron": "ráu méni"},
    {"pt": "de quem?",          "en": "whose?",        "pron": "rús"},
    {"pt": "para quê?",         "en": "what for?",     "pron": "uót fór"},
    {"pt": "com quem?",         "en": "with whom?",    "pron": "uíth rúm"},
    {"pt": "até quando?",       "en": "until when?",   "pron": "antíl uén"},

    # Apresentação
    {"pt": "como você está?",   "en": "how are you?",         "pron": "ráu ár iu"},
    {"pt": "qual seu nome?",    "en": "what's your name?",    "pron": "uóts iór néim"},
    {"pt": "qual seu sobrenome?","en": "what's your last name?","pron": "uóts iór lést néim"},
    {"pt": "de onde você é?",   "en": "where are you from?",  "pron": "uér ár iu from"},
    {"pt": "onde você nasceu?", "en": "where were you born?", "pron": "uér uér iu bórn"},
    {"pt": "quantos anos você tem?","en": "how old are you?", "pron": "ráu ôuld ár iu"},
    {"pt": "o que você faz?",   "en": "what do you do?",      "pron": "uót du iu dú"},
    {"pt": "onde você trabalha?","en": "where do you work?",  "pron": "uér du iu uórk"},
    {"pt": "onde você mora?",   "en": "where do you live?",   "pron": "uér du iu lív"},
    {"pt": "você é casado?",    "en": "are you married?",     "pron": "ár iu mérid"},
    {"pt": "você tem filhos?",  "en": "do you have kids?",    "pron": "du iu rév kíds"},
    {"pt": "você tem irmãos?",  "en": "do you have siblings?","pron": "du iu rév síblings"},
    {"pt": "qual seu telefone?","en": "what's your phone number?","pron": "uóts iór fôun námber"},
    {"pt": "qual seu email?",   "en": "what's your email?",   "pron": "uóts iór ímeil"},

    # Comunicação
    {"pt": "você fala inglês?", "en": "do you speak English?","pron": "du iu spík ínglish"},
    {"pt": "você fala português?","en": "do you speak Portuguese?","pron": "du iu spík pórchuguis"},
    {"pt": "você entende?",     "en": "do you understand?",   "pron": "du iu ándersténd"},
    {"pt": "você pode repetir?","en": "can you repeat?",      "pron": "kén iu ripít"},
    {"pt": "pode falar mais devagar?","en": "can you speak slower?","pron": "kén iu spík slôuer"},
    {"pt": "pode falar mais alto?","en": "can you speak louder?","pron": "kén iu spík láuder"},
    {"pt": "o que significa isso?","en": "what does this mean?","pron": "uót dáz dis mín"},
    {"pt": "como se diz em inglês?","en": "how do you say in English?","pron": "ráu du iu séi in ínglish"},
    {"pt": "como se escreve?",  "en": "how do you spell it?","pron": "ráu du iu spél it"},
    {"pt": "como se pronuncia?", "en": "how do you pronounce it?","pron": "ráu du iu pronáuns it"},
    {"pt": "o que é isso?",     "en": "what is this?",        "pron": "uót is dis"},
    {"pt": "quem é ele?",       "en": "who is he?",           "pron": "rú is rí"},
    {"pt": "quem é ela?",       "en": "who is she?",          "pron": "rú is shí"},
    {"pt": "você pode me ajudar?","en": "can you help me?",   "pron": "kén iu rélp mi"},
    {"pt": "posso te perguntar algo?","en": "can I ask you something?","pron": "kén ái ésk iu sámthing"},

    # Tempo
    {"pt": "que horas são?",    "en": "what time is it?",     "pron": "uót táim is it"},
    {"pt": "que dia é hoje?",   "en": "what day is it?",      "pron": "uót déi is it"},
    {"pt": "que dia é amanhã?", "en": "what day is tomorrow?","pron": "uót déi is tumórou"},
    {"pt": "quando é...?",      "en": "when is...?",          "pron": "uén is"},
    {"pt": "quanto tempo demora?","en": "how long does it take?","pron": "ráu long dáz it téik"},
    {"pt": "que horas abre?",   "en": "what time does it open?","pron": "uót táim dáz it ôupen"},
    {"pt": "que horas fecha?",  "en": "what time does it close?","pron": "uót táim dáz it klôuz"},
    {"pt": "está aberto agora?","en": "is it open now?",      "pron": "is it ôupen náu"},
    {"pt": "você tem tempo?",   "en": "do you have time?",    "pron": "du iu rév táim"},
    {"pt": "que dia você pode?","en": "what day can you?",    "pron": "uót déi kén iu"},

    # Preços
    {"pt": "quanto custa?",     "en": "how much does it cost?","pron": "ráu mách dáz it kóst"},
    {"pt": "quanto é?",         "en": "how much is it?",      "pron": "ráu mách is it"},
    {"pt": "tem desconto?",     "en": "is there a discount?", "pron": "is dér e dískáunt"},
    {"pt": "aceita cartão?",    "en": "do you accept cards?", "pron": "du iu aksépt kárds"},
    {"pt": "aceita dinheiro?",  "en": "do you accept cash?",  "pron": "du iu aksépt késh"},
    {"pt": "tem troco?",        "en": "do you have change?",  "pron": "du iu rév chéindj"},
    {"pt": "pode parcelar?",    "en": "can I pay in installments?","pron": "kén ái péi in instólments"},
    {"pt": "está em promoção?", "en": "is it on sale?",       "pron": "is it ón séil"},
    {"pt": "é grátis?",         "en": "is it free?",          "pron": "is it frí"},
    {"pt": "quanto fica no total?","en": "what's the total?","pron": "uóts de tóutol"},

    # Locais
    {"pt": "onde é o banheiro?","en": "where is the bathroom?","pron": "uér is de béthrum"},
    {"pt": "onde é a saída?",   "en": "where is the exit?",   "pron": "uér is de égzit"},
    {"pt": "onde é a entrada?", "en": "where is the entrance?","pron": "uér is de éntrens"},
    {"pt": "onde fica a estação?","en": "where is the station?","pron": "uér is de stéishon"},
    {"pt": "onde fica o hotel?","en": "where is the hotel?",  "pron": "uér is de routél"},
    {"pt": "onde fica o hospital?","en": "where is the hospital?","pron": "uér is de róspital"},
    {"pt": "onde fica a polícia?","en": "where is the police?","pron": "uér is de polís"},
    {"pt": "onde fica o banco?","en": "where is the bank?",   "pron": "uér is de bénk"},
    {"pt": "tem um restaurante perto?","en": "is there a restaurant nearby?","pron": "is dér e réstorant nírbai"},
    {"pt": "tem um banco perto?","en": "is there a bank nearby?","pron": "is dér e bénk nírbai"},
    {"pt": "onde posso encontrar...?","en": "where can I find...?","pron": "uér kén ái fáind"},

    # Preferências
    {"pt": "você gosta de...?", "en": "do you like...?",      "pron": "du iu láik"},
    {"pt": "você quer...?",     "en": "do you want...?",      "pron": "du iu uónt"},
    {"pt": "você pode...?",     "en": "can you...?",          "pron": "kén iu"},
    {"pt": "você tem...?",      "en": "do you have...?",      "pron": "du iu rév"},
    {"pt": "posso...?",         "en": "may I...?",            "pron": "méi ái"},
    {"pt": "poderia me ajudar?","en": "could you help me?",   "pron": "kúd iu rélp mi"},
    {"pt": "por que não?",      "en": "why not?",             "pron": "uái nót"},
    {"pt": "e você?",           "en": "and you?",             "pron": "énd iu"},
    {"pt": "tudo bem?",         "en": "is everything ok?",    "pron": "is évrithing ôukei"},
    {"pt": "e aí?",             "en": "what's up?",           "pron": "uóts áp"},
    {"pt": "você já comeu?",    "en": "have you eaten?",      "pron": "rév iu íten"},
    {"pt": "você já foi...?",   "en": "have you been to...?", "pron": "rév iu bín tu"},

    # Viagem
    {"pt": "onde é o check-in?","en": "where is check-in?",  "pron": "uér is chék ín"},
    {"pt": "que horas sai o voo?","en": "what time is the flight?","pron": "uót táim is de fláit"},
    {"pt": "qual é o portão?",  "en": "which is the gate?",  "pron": "uích is de guéit"},
    {"pt": "a que horas embarco?","en": "what time do I board?","pron": "uót táim du ái bórd"},
    {"pt": "tem wi-fi aqui?",   "en": "is there wi-fi here?","pron": "is dér uáifái rír"},
    {"pt": "qual a senha do wi-fi?","en": "what's the wi-fi password?","pron": "uóts de uáifái péssuord"},
    {"pt": "posso ver o cardápio?","en": "can I see the menu?","pron": "kén ái sí de ményu"},
    {"pt": "tem quarto vago?",  "en": "do you have a room available?","pron": "du iu rév e rúm avéilabol"},

    # Médico
    {"pt": "onde dói?",         "en": "where does it hurt?","pron": "uér dáz it rért"},
    {"pt": "que remédio você toma?","en": "what medicine do you take?","pron": "uót mésdisin du iu téik"},
    {"pt": "você é alérgico a algo?","en": "are you allergic to anything?","pron": "ár iu alérdjik tu énithing"},
    {"pt": "há quanto tempo está assim?","en": "how long have you been like this?","pron": "ráu long rév iu bín láik dis"},
    {"pt": "você tem plano de saúde?","en": "do you have health insurance?","pron": "du iu rév rélth inshúrans"},

    # Trabalho
    {"pt": "você trabalha com o quê?","en": "what do you work with?","pron": "uót du iu uórk uíth"},
    {"pt": "há quanto tempo trabalha aqui?","en": "how long have you worked here?","pron": "ráu long rév iu uórkt rír"},
    {"pt": "você gosta do seu trabalho?","en": "do you like your job?","pron": "du iu láik iór djób"},
    {"pt": "que horas você sai do trabalho?","en": "what time do you leave work?","pron": "uót táim du iu lív uórk"},
    {"pt": "você trabalha home office?","en": "do you work from home?","pron": "du iu uórk from rôum"},

    # Frases prontas de cortesia
    {"pt": "tudo bem com você?",   "en": "how have you been?",   "pron": "ráu rév iu bín"},
    {"pt": "que novidades?",       "en": "what's new?",          "pron": "uóts niú"},
    {"pt": "como foi seu dia?",    "en": "how was your day?",    "pron": "ráu uós iór déi"},
    {"pt": "como está o tempo?",   "en": "how is the weather?",  "pron": "ráu is de uéder"},
    {"pt": "tudo certo?",          "en": "everything good?",     "pron": "évrithing gúd"},
    {"pt": "vai dar certo?",       "en": "will it work out?",    "pron": "uíl it uórk áut"},
    {"pt": "que horas nos encontramos?","en": "what time shall we meet?","pron": "uót táim shél uí mít"},
    {"pt": "onde nos encontramos?","en": "where shall we meet?", "pron": "uér shél uí mít"},
    {"pt": "você já sabe?",        "en": "do you already know?","pron": "du iu olrédi nôu"},
    {"pt": "quer ir comigo?",      "en": "want to come with me?","pron": "uónt tu kám uíth mi"},
    {"pt": "posso te ligar depois?","en": "can I call you later?","pron": "kén ái kól iu léiter"},
    {"pt": "você me manda mensagem?","en": "can you text me?","pron": "kén iu tékst mi"},

    # Emergência
    {"pt": "você pode me ajudar?", "en": "can you help me?",     "pron": "kén iu rélp mi"},
    {"pt": "chame a polícia!",     "en": "call the police!",     "pron": "kól de polís"},
    {"pt": "chame uma ambulância!","en": "call an ambulance!",   "pron": "kól en émbiulans"},
    {"pt": "onde é o hospital mais próximo?","en": "where is the nearest hospital?","pron": "uér is de nírest róspital"},
    {"pt": "é uma emergência!",    "en": "it's an emergency!",   "pron": "its en imérdjensi"},
    {"pt": "estou perdido!",       "en": "I'm lost!",            "pron": "áim lóst"},
    {"pt": "fui roubado!",         "en": "I was robbed!",        "pron": "ái uós róbd"},
    {"pt": "perdi meu passaporte","en": "I lost my passport",    "pron": "ái lóst mái péspourt"},
    {"pt": "não falo inglês",      "en": "I don't speak English","pron": "ái dônt spík ínglish"},

    # Extras - perguntas comuns do cotidiano
    {"pt": "você pode me emprestar?","en": "can you lend me?",   "pron": "kén iu lénd mi"},
    {"pt": "você tem um minuto?",  "en": "do you have a minute?","pron": "du iu rév e mínit"},
    {"pt": "posso entrar?",        "en": "may I come in?",       "pron": "méi ái kám ín"},
    {"pt": "posso sentar?",        "en": "may I sit down?",      "pron": "méi ái sít dáun"},
    {"pt": "posso experimentar?",  "en": "may I try it on?",     "pron": "méi ái trái it ón"},
    {"pt": "posso levar?",         "en": "may I take it?",       "pron": "méi ái téik it"},
    {"pt": "posso pagar depois?",  "en": "may I pay later?",     "pron": "méi ái péi léiter"},
    {"pt": "tudo pronto?",         "en": "is everything ready?", "pron": "is évrithing rédi"},
    {"pt": "vamos?",               "en": "shall we go?",         "pron": "shél uí gôu"},
    {"pt": "posso?",               "en": "may I?",               "pron": "méi ái"},
    {"pt": "tudo isso?",           "en": "all this?",            "pron": "ól dis"},
    {"pt": "que tal?",             "en": "how about?",           "pron": "ráu abáut"},
    {"pt": "você tem certeza?",    "en": "are you sure?",        "pron": "ár iu shúr"},
    {"pt": "posso confiar?",       "en": "can I trust you?",     "pron": "kén ái trást iu"},
    {"pt": "o que aconteceu?",     "en": "what happened?",       "pron": "uót répend"},
    {"pt": "por que não me contou?","en": "why didn't you tell me?","pron": "uái dídnt iu tél mi"},
    {"pt": "você já viu isso?",    "en": "have you seen this?",  "pron": "rév iu sín dis"},
    {"pt": "quem fez isso?",       "en": "who did this?",        "pron": "rú díd dis"},
    {"pt": "onde você estava?",    "en": "where were you?",      "pron": "uér uér iu"},
    {"pt": "o que você acha?",     "en": "what do you think?",   "pron": "uót du iu thínk"},
]

# ============ 😊 EMOÇÕES (150) ============
emocoes = [
    # Positivas
    {"pt": "feliz",          "en": "happy",          "pron": "répi"},
    {"pt": "alegre",         "en": "cheerful",       "pron": "chírful"},
    {"pt": "animado",        "en": "excited",        "pron": "eksáitid"},
    {"pt": "contente",       "en": "glad",           "pron": "gléd"},
    {"pt": "satisfeito",     "en": "satisfied",      "pron": "sétisfaid"},
    {"pt": "orgulhoso",      "en": "proud",          "pron": "práud"},
    {"pt": "grato",          "en": "grateful",       "pron": "gréitful"},
    {"pt": "apaixonado",     "en": "in love",        "pron": "in láv"},
    {"pt": "esperançoso",    "en": "hopeful",        "pron": "rôupful"},
    {"pt": "calmo",          "en": "calm",           "pron": "kám"},
    {"pt": "relaxado",       "en": "relaxed",        "pron": "rilékst"},
    {"pt": "tranquilo",      "en": "peaceful",       "pron": "písful"},
    {"pt": "empolgado",      "en": "thrilled",       "pron": "thríld"},
    {"pt": "radiante",       "en": "radiant",        "pron": "réidiant"},
    {"pt": "de bem com a vida","en": "happy-go-lucky","pron": "répi gôu láki"},

    # Negativas
    {"pt": "triste",         "en": "sad",            "pron": "séd"},
    {"pt": "com raiva",      "en": "angry",          "pron": "éngri"},
    {"pt": "irritado",       "en": "annoyed",        "pron": "anóid"},
    {"pt": "frustrado",      "en": "frustrated",     "pron": "frástreitid"},
    {"pt": "com medo",       "en": "afraid",         "pron": "afréid"},
    {"pt": "assustado",      "en": "scared",         "pron": "skéd"},
    {"pt": "ansioso",        "en": "anxious",        "pron": "énkshas"},
    {"pt": "nervoso",        "en": "nervous",        "pron": "nérvas"},
    {"pt": "preocupado",     "en": "worried",        "pron": "uórid"},
    {"pt": "estressado",     "en": "stressed",       "pron": "strést"},
    {"pt": "cansado",        "en": "tired",          "pron": "táierd"},
    {"pt": "exausto",        "en": "exhausted",      "pron": "egzóstid"},
    {"pt": "entediado",      "en": "bored",          "pron": "bórd"},
    {"pt": "sozinho",        "en": "lonely",         "pron": "lôunli"},
    {"pt": "deprimido",      "en": "depressed",      "pron": "diprést"},
    {"pt": "confuso",        "en": "confused",       "pron": "konfiúzd"},
    {"pt": "envergonhado",   "en": "embarrassed",    "pron": "embérast"},
    {"pt": "culpado",        "en": "guilty",         "pron": "guílti"},
    {"pt": "com ciúmes",     "en": "jealous",        "pron": "djélos"},
    {"pt": "decepcionado",   "en": "disappointed",   "pron": "disapóintid"},
    {"pt": "surpreso",       "en": "surprised",      "pron": "sorpráizd"},
    {"pt": "chocado",        "en": "shocked",        "pron": "shókt"},
    {"pt": "furioso",        "en": "furious",        "pron": "fiúrias"},
    {"pt": "revoltado",      "en": "outraged",       "pron": "áutréidjd"},
    {"pt": "desapontado",    "en": "let down",       "pron": "lét dáun"},
    {"pt": "arrependido",    "en": "regretful",      "pron": "rigrétful"},
    {"pt": "desanimado",     "en": "discouraged",    "pron": "diskóridjd"},
    {"pt": "desesperado",    "en": "desperate",      "pron": "désperat"},
    {"pt": "desamparado",    "en": "helpless",       "pron": "rélples"},
    {"pt": "humilhado",      "en": "humiliated",     "pron": "riumílieitid"},
    {"pt": "rejeitado",      "en": "rejected",       "pron": "ridjéktid"},
    {"pt": "traído",         "en": "betrayed",       "pron": "bitréid"},
    {"pt": "perdido",        "en": "lost",           "pron": "lóst"},
    {"pt": "sem esperança",  "en": "hopeless",       "pron": "rôuples"},
    {"pt": "com pena",       "en": "sorry for",      "pron": "sóri fór"},

    # Estados
    {"pt": "com fome",       "en": "hungry",         "pron": "rángri"},
    {"pt": "com sede",       "en": "thirsty",        "pron": "thérsti"},
    {"pt": "com sono",       "en": "sleepy",         "pron": "slípi"},
    {"pt": "com calor",      "en": "hot",            "pron": "rót"},
    {"pt": "com frio",       "en": "cold",           "pron": "kôuld"},
    {"pt": "doente",         "en": "sick",           "pron": "sík"},
    {"pt": "machucado",      "en": "hurt",           "pron": "rért"},
    {"pt": "bem",            "en": "well",           "pron": "uél"},
    {"pt": "mal",            "en": "bad",            "pron": "béd"},
    {"pt": "ocupado",        "en": "busy",           "pron": "bízi"},
    {"pt": "livre",          "en": "free",           "pron": "frí"},
    {"pt": "pronto",         "en": "ready",          "pron": "rédi"},
    {"pt": "atrasado",       "en": "late",           "pron": "léit"},
    {"pt": "adiantado",      "en": "early",          "pron": "érli"},
    {"pt": "de boa",         "en": "chill",          "pron": "chíl"},
    {"pt": "animadíssimo",   "en": "pumped up",      "pron": "pámpt áp"},
    {"pt": "queimado",       "en": "burned out",     "pron": "bérnd áut"},

    # Personalidade (adjetivos)
    {"pt": "simpático",      "en": "nice",           "pron": "náis"},
    {"pt": "gentil",         "en": "kind",           "pron": "káind"},
    {"pt": "educado",        "en": "polite",         "pron": "poláit"},
    {"pt": "grosseiro",      "en": "rude",           "pron": "rúd"},
    {"pt": "legal",          "en": "cool",           "pron": "kúl"},
    {"pt": "chato",          "en": "boring",         "pron": "bóring"},
    {"pt": "engraçado",      "en": "funny",          "pron": "fáni"},
    {"pt": "sério",          "en": "serious",        "pron": "sírias"},
    {"pt": "inteligente",    "en": "smart",          "pron": "smárt"},
    {"pt": "burro",          "en": "dumb",           "pron": "dám"},
    {"pt": "esperto",        "en": "clever",         "pron": "kléver"},
    {"pt": "preguiçoso",     "en": "lazy",           "pron": "léizi"},
    {"pt": "trabalhador",    "en": "hardworking",    "pron": "rárd uórking"},
    {"pt": "corajoso",       "en": "brave",          "pron": "bréiv"},
    {"pt": "medroso",        "en": "coward",         "pron": "káuard"},
    {"pt": "honesto",        "en": "honest",         "pron": "ónest"},
    {"pt": "mentiroso",      "en": "liar",           "pron": "lái ar"},
    {"pt": "generoso",       "en": "generous",       "pron": "djéneras"},
    {"pt": "egoísta",        "en": "selfish",        "pron": "sélfish"},
    {"pt": "tímido",         "en": "shy",            "pron": "shái"},
    {"pt": "extrovertido",   "en": "outgoing",       "pron": "áutgóuing"},
    {"pt": "calado",         "en": "quiet",          "pron": "kuáiet"},
    {"pt": "falador",        "en": "talkative",      "pron": "tókativ"},
    {"pt": "otimista",       "en": "optimistic",     "pron": "optimístik"},
    {"pt": "pessimista",     "en": "pessimistic",    "pron": "pesimístik"},
    {"pt": "confiante",      "en": "confident",      "pron": "kónfident"},
    {"pt": "inseguro",       "en": "insecure",       "pron": "insikiúr"},
    {"pt": "atencioso",      "en": "thoughtful",     "pron": "thótful"},
    {"pt": "distraído",      "en": "distracted",     "pron": "distréktid"},
    {"pt": "criativo",       "en": "creative",       "pron": "kriéitiv"},
    {"pt": "curioso",        "en": "curious",        "pron": "kiúrias"},
    {"pt": "paciente",       "en": "patient",        "pron": "péishant"},
    {"pt": "impaciente",     "en": "impatient",      "pron": "impéishant"},
    {"pt": "charmoso",       "en": "charming",       "pron": "chármin"},
    {"pt": "arrogante",      "en": "arrogant",       "pron": "érogant"},
    {"pt": "humilde",        "en": "humble",         "pron": "rámbol"},
    {"pt": "sensível",       "en": "sensitive",      "pron": "sénsitiv"},
    {"pt": "forte",          "en": "strong",         "pron": "strong"},
    {"pt": "fraco",          "en": "weak",           "pron": "uík"},

    # Expressões
    {"pt": "estou feliz",            "en": "I'm happy",          "pron": "áim répi"},
    {"pt": "estou triste",           "en": "I'm sad",            "pron": "áim séd"},
    {"pt": "estou cansado",          "en": "I'm tired",          "pron": "áim táierd"},
    {"pt": "estou com fome",         "en": "I'm hungry",         "pron": "áim rángri"},
    {"pt": "estou com medo",         "en": "I'm scared",         "pron": "áim skéd"},
    {"pt": "estou animado",          "en": "I'm excited",        "pron": "áim eksáitid"},
    {"pt": "estou preocupado",       "en": "I'm worried",        "pron": "áim uórid"},
    {"pt": "não estou bem",          "en": "I'm not ok",         "pron": "áim nót ôukei"},
    {"pt": "estou melhor",           "en": "I'm better",         "pron": "áim béter"},
    {"pt": "não me sinto bem",       "en": "I don't feel well",  "pron": "ái dônt fíl uél"},
    {"pt": "que ótimo!",             "en": "that's great!",      "pron": "déts gréit"},
    {"pt": "que pena!",              "en": "that's a pity!",     "pron": "déts e píti"},
    {"pt": "que raiva!",             "en": "I'm so angry!",      "pron": "áim sôu éngri"},
    {"pt": "não acredito!",          "en": "I can't believe it!","pron": "ái ként bilív it"},
    {"pt": "estou muito feliz",      "en": "I'm very happy",     "pron": "áim véri répi"},
    {"pt": "estou nervoso",          "en": "I'm nervous",        "pron": "áim nérvas"},
    {"pt": "estou de boa",           "en": "I'm chill",          "pron": "áim chíl"},
    {"pt": "estou orgulhoso de você","en": "I'm proud of you",   "pron": "áim práud óv iu"},
    {"pt": "estou apaixonado",       "en": "I'm in love",        "pron": "áim in láv"},
    {"pt": "estou com ciúmes",       "en": "I'm jealous",        "pron": "áim djélos"},
    {"pt": "estou surpreso",         "en": "I'm surprised",      "pron": "áim sorpráizd"},
    {"pt": "estou decepcionado",     "en": "I'm disappointed",   "pron": "áim disapóintid"},
    {"pt": "estou estressado",       "en": "I'm stressed",       "pron": "áim strést"},
    {"pt": "estou entediado",        "en": "I'm bored",          "pron": "áim bórd"},
    {"pt": "estou sozinho",          "en": "I'm lonely",         "pron": "áim lôunli"},
    {"pt": "estou ocupado",          "en": "I'm busy",           "pron": "áim bízi"},
    {"pt": "estou pronto",           "en": "I'm ready",          "pron": "áim rédi"},
    {"pt": "estou atrasado",         "en": "I'm late",           "pron": "áim léit"},
    {"pt": "estou perdido",          "en": "I'm lost",           "pron": "áim lóst"},
    {"pt": "não estou entendendo",   "en": "I'm not understanding","pron": "áim nót ándersténding"},
    {"pt": "tô nem aí",              "en": "I don't care",       "pron": "ái dônt kér"},
    {"pt": "que susto!",             "en": "what a scare!",      "pron": "uót e skér"},
    {"pt": "que alívio!",            "en": "what a relief!",     "pron": "uót e rilíf"},
    {"pt": "me sinto mal",           "en": "I feel bad",         "pron": "ái fíl béd"},
    {"pt": "me sinto ótimo",         "en": "I feel great",       "pron": "ái fíl gréit"},
    {"pt": "estou confuso",          "en": "I'm confused",       "pron": "áim konfiúzd"},
    {"pt": "estou com saudade",      "en": "I miss you",         "pron": "ái mís iu"},
    {"pt": "estou muito grato",      "en": "I'm very grateful",  "pron": "áim véri gréitful"},
    {"pt": "foi divertido",          "en": "it was fun",         "pron": "it uós fán"},
    {"pt": "foi horrível",           "en": "it was awful",       "pron": "it uós óful"},
    {"pt": "foi incrível",           "en": "it was amazing",     "pron": "it uós améizing"},
    {"pt": "que dia maravilhoso!",   "en": "what a wonderful day!","pron": "uót e uánderful déi"},
    {"pt": "estou com preguiça",     "en": "I'm feeling lazy",   "pron": "áim fíling léizi"},
    {"pt": "estou sem paciência",    "en": "I have no patience", "pron": "ái rév nôu péishans"},
    {"pt": "estou exausto",          "en": "I'm exhausted",      "pron": "áim egzóstid"},
]

# ============ 💰 DINHEIRO E COMPRAS (150) ============
dinheiro = [
    # Dinheiro
    {"pt": "dinheiro",       "en": "money",          "pron": "máni"},
    {"pt": "moeda",          "en": "coin",           "pron": "kóin"},
    {"pt": "nota",           "en": "bill",           "pron": "bíl"},
    {"pt": "cédula",         "en": "banknote",       "pron": "bénknout"},
    {"pt": "troco",          "en": "change",         "pron": "chéindj"},
    {"pt": "conta",          "en": "bill",           "pron": "bíl"},
    {"pt": "preço",          "en": "price",          "pron": "práis"},
    {"pt": "valor",          "en": "value",          "pron": "védju"},
    {"pt": "desconto",       "en": "discount",       "pron": "dískaunt"},
    {"pt": "promoção",       "en": "sale",           "pron": "séil"},
    {"pt": "imposto",        "en": "tax",            "pron": "téks"},
    {"pt": "salário",        "en": "salary",         "pron": "sélari"},
    {"pt": "lucro",          "en": "profit",         "pron": "prófit"},
    {"pt": "dívida",         "en": "debt",           "pron": "dét"},
    {"pt": "receita",        "en": "revenue",        "pron": "révenu"},
    {"pt": "despesa",        "en": "expense",        "pron": "ekspéns"},
    {"pt": "orçamento",      "en": "budget",         "pron": "bádjet"},
    {"pt": "economia",       "en": "savings",        "pron": "séivings"},
    {"pt": "investimento",   "en": "investment",     "pron": "invéstment"},
    {"pt": "juros",          "en": "interest",       "pron": "íntrest"},

    # Moedas
    {"pt": "real",           "en": "real",           "pron": "riól"},
    {"pt": "dólar",          "en": "dollar",         "pron": "dólar"},
    {"pt": "euro",           "en": "euro",           "pron": "iúrou"},
    {"pt": "libra",          "en": "pound",          "pron": "páund"},
    {"pt": "iene",           "en": "yen",            "pron": "ián"},
    {"pt": "rublo",          "en": "ruble",          "pron": "rúbol"},
    {"pt": "peso",           "en": "peso",           "pron": "pésou"},
    {"pt": "câmbio",         "en": "exchange rate",  "pron": "ekstchéindj réit"},

    # Meios de pagamento
    {"pt": "cartão de crédito","en": "credit card",  "pron": "krédit kárd"},
    {"pt": "cartão de débito","en": "debit card",    "pron": "débit kárd"},
    {"pt": "dinheiro em espécie","en": "cash",       "pron": "késh"},
    {"pt": "cheque",         "en": "check",          "pron": "chék"},
    {"pt": "boleto",         "en": "bank slip",      "pron": "bénk slíp"},
    {"pt": "pix",            "en": "instant transfer","pron": "ínstant trénsfer"},
    {"pt": "carteira digital","en": "digital wallet","pron": "dídjitol uólet"},
    {"pt": "transferência",  "en": "transfer",       "pron": "trénsfer"},
    {"pt": "depósito",       "en": "deposit",        "pron": "dipózit"},
    {"pt": "saque",          "en": "withdrawal",     "pron": "uíthdróal"},

    # Ações
    {"pt": "comprar",        "en": "to buy",         "pron": "tu bái"},
    {"pt": "vender",         "en": "to sell",        "pron": "tu sél"},
    {"pt": "pagar",          "en": "to pay",         "pron": "tu péi"},
    {"pt": "gastar",         "en": "to spend",       "pron": "tu spénd"},
    {"pt": "economizar",     "en": "to save",        "pron": "tu séiv"},
    {"pt": "emprestar",      "en": "to lend",        "pron": "tu lénd"},
    {"pt": "pedir emprestado","en": "to borrow",     "pron": "tu bórou"},
    {"pt": "devolver",       "en": "to return",      "pron": "tu ritérn"},
    {"pt": "trocar",         "en": "to exchange",    "pron": "tu ekstchéindj"},
    {"pt": "investir",       "en": "to invest",      "pron": "tu invést"},
    {"pt": "negociar",       "en": "to negotiate",   "pron": "tu nigóushieit"},
    {"pt": "pechinchar",     "en": "to haggle",      "pron": "tu régol"},
    {"pt": "cobrar",         "en": "to charge",      "pron": "tu chárdj"},
    {"pt": "pagar à vista",  "en": "to pay cash",    "pron": "tu péi késh"},
    {"pt": "pagar parcelado","en": "to pay in installments","pron": "tu péi in instólments"},

    # Adjetivos
    {"pt": "caro",           "en": "expensive",      "pron": "ekspénsiv"},
    {"pt": "barato",         "en": "cheap",          "pron": "chíp"},
    {"pt": "grátis",         "en": "free",           "pron": "frí"},
    {"pt": "novo",           "en": "new",            "pron": "niú"},
    {"pt": "usado",          "en": "used",           "pron": "iúzd"},
    {"pt": "em promoção",    "en": "on sale",        "pron": "ón séil"},
    {"pt": "caríssimo",      "en": "very expensive", "pron": "véri ekspénsiv"},
    {"pt": "acessível",      "en": "affordable",     "pron": "afórdabol"},
    {"pt": "razoável",       "en": "reasonable",     "pron": "rízonebol"},
    {"pt": "justo",          "en": "fair",           "pron": "fér"},
    {"pt": "abusivo",        "en": "overpriced",     "pron": "ôuverpráist"},
    {"pt": "vale a pena",    "en": "worth it",       "pron": "uérth it"},
    {"pt": "não vale",       "en": "not worth it",   "pron": "nót uérth it"},

    # Lugares
    {"pt": "loja",           "en": "store",          "pron": "stór"},
    {"pt": "mercado",        "en": "market",         "pron": "márkit"},
    {"pt": "supermercado",   "en": "supermarket",    "pron": "súpermárkit"},
    {"pt": "shopping",       "en": "mall",           "pron": "mól"},
    {"pt": "banco",          "en": "bank",           "pron": "bénk"},
    {"pt": "caixa eletrônico","en": "ATM",           "pron": "ei ti ém"},
    {"pt": "farmácia",       "en": "pharmacy",       "pron": "fármasi"},
    {"pt": "padaria",        "en": "bakery",         "pron": "béikeri"},
    {"pt": "livraria",       "en": "bookstore",      "pron": "búkstor"},
    {"pt": "feira",          "en": "market",         "pron": "márkit"},
    {"pt": "loja de roupas", "en": "clothing store", "pron": "klôudhing stór"},
    {"pt": "loja de sapatos","en": "shoe store",     "pron": "shú stór"},
    {"pt": "joalheria",      "en": "jewelry store",  "pron": "djúelri stór"},
    {"pt": "papelaria",      "en": "stationery store","pron": "stéishoneri stór"},

    # Produtos
    {"pt": "produto",        "en": "product",        "pron": "pródakt"},
    {"pt": "mercadoria",     "en": "merchandise",    "pron": "mérchandais"},
    {"pt": "comida",         "en": "food",           "pron": "fúd"},
    {"pt": "bebida",         "en": "drink",          "pron": "drínk"},
    {"pt": "remédio",        "en": "medicine",       "pron": "mésdisin"},
    {"pt": "roupa",          "en": "clothes",        "pron": "klôudz"},
    {"pt": "sapato",         "en": "shoe",           "pron": "shú"},
    {"pt": "eletrônico",     "en": "electronic",     "pron": "elektrónik"},
    {"pt": "celular",        "en": "cell phone",     "pron": "sél fôun"},
    {"pt": "computador",     "en": "computer",       "pron": "kompiúter"},
    {"pt": "brinquedo",      "en": "toy",            "pron": "tói"},
    {"pt": "presente",       "en": "gift",           "pron": "guíft"},
    {"pt": "lembrança",      "en": "souvenir",       "pron": "suvinír"},

    # Loja - vocabulário
    {"pt": "vitrine",        "en": "shop window",    "pron": "shóp uíndou"},
    {"pt": "prateleira",     "en": "shelf",          "pron": "shelf"},
    {"pt": "provador",       "en": "fitting room",   "pron": "fíting rúm"},
    {"pt": "caixa",          "en": "cashier",        "pron": "késhír"},
    {"pt": "sacola",         "en": "bag",            "pron": "bég"},
    {"pt": "etiqueta",       "en": "tag",            "pron": "tég"},
    {"pt": "código de barras","en": "barcode",       "pron": "bárkoud"},
    {"pt": "nota fiscal",    "en": "receipt",        "pron": "risít"},
    {"pt": "garantia",       "en": "warranty",       "pron": "uóranti"},
    {"pt": "cliente",        "en": "customer",       "pron": "kástomer"},
    {"pt": "vendedor",       "en": "salesperson",    "pron": "séilspérson"},
    {"pt": "gerente",        "en": "manager",        "pron": "ménedjer"},

    # Frases
    {"pt": "quanto custa?",       "en": "how much does it cost?","pron": "ráu mách dáz it kóst"},
    {"pt": "é muito caro",        "en": "it's too expensive",   "pron": "its tú ekspénsiv"},
    {"pt": "tem mais barato?",    "en": "is there anything cheaper?","pron": "is dér énithing chíper"},
    {"pt": "aceita cartão?",      "en": "do you accept cards?", "pron": "du iu aksépt kárds"},
    {"pt": "aceita pix?",         "en": "do you accept instant transfer?","pron": "du iu aksépt ínstant trénsfer"},
    {"pt": "só dinheiro",         "en": "cash only",            "pron": "késh ôunli"},
    {"pt": "quero pagar",         "en": "I want to pay",        "pron": "ái uónt tu péi"},
    {"pt": "a conta, por favor",  "en": "the bill, please",     "pron": "de bíl plíz"},
    {"pt": "pode me dar um desconto?","en": "can you give me a discount?","pron": "kén iu guív mi e dískaunt"},
    {"pt": "tá caro demais",      "en": "it's too expensive",   "pron": "its tú ekspénsiv"},
    {"pt": "vou pensar",          "en": "I'll think about it",  "pron": "áil thínk abáut it"},
    {"pt": "só estou olhando",    "en": "I'm just looking",     "pron": "áim djást lúking"},
    {"pt": "pode embrulhar?",     "en": "can you wrap it?",     "pron": "kén iu rép it"},
    {"pt": "posso experimentar?", "en": "can I try it on?",     "pron": "kén ái trái it ón"},
    {"pt": "tem em outra cor?",   "en": "do you have it in another color?","pron": "du iu rév it in anáder kólor"},
    {"pt": "tem em outro tamanho?","en": "do you have it in another size?","pron": "du iu rév it in anáder sáiz"},
    {"pt": "onde é o caixa?",     "en": "where is the cashier?","pron": "uér is de keshír"},
    {"pt": "quero trocar isso",   "en": "I want to exchange this","pron": "ái uónt tu ekstchéindj dis"},
    {"pt": "quero devolver",      "en": "I want to return it",  "pron": "ái uónt tu ritérn it"},
    {"pt": "qual o prazo de garantia?","en": "what's the warranty?","pron": "uóts de uóranti"},
]

# ============ 🍽️ RESTAURANTE (150) ============
restaurante = [
    # Lugares
    {"pt": "restaurante",    "en": "restaurant",     "pron": "réstorant"},
    {"pt": "lanchonete",     "en": "snack bar",      "pron": "snék bár"},
    {"pt": "cafeteria",      "en": "café",           "pron": "kaféi"},
    {"pt": "bar",            "en": "bar",            "pron": "bár"},
    {"pt": "pizzaria",       "en": "pizzeria",       "pron": "pitsería"},
    {"pt": "padaria",        "en": "bakery",         "pron": "béikeri"},
    {"pt": "churrascaria",   "en": "steakhouse",     "pron": "stéikráus"},
    {"pt": "sorveteria",     "en": "ice cream shop", "pron": "áis krím shóp"},
    {"pt": "café da manhã",  "en": "breakfast",      "pron": "brékfast"},
    {"pt": "fast food",      "en": "fast food",      "pron": "fést fúd"},
    {"pt": "self-service",   "en": "buffet",         "pron": "buféi"},
    {"pt": "food truck",     "en": "food truck",     "pron": "fúd trák"},

    # Cardápio
    {"pt": "cardápio",       "en": "menu",           "pron": "ményu"},
    {"pt": "entrada",        "en": "appetizer",      "pron": "épitáizer"},
    {"pt": "prato principal","en": "main course",    "pron": "méin kórs"},
    {"pt": "sobremesa",      "en": "dessert",        "pron": "dizért"},
    {"pt": "bebida",         "en": "drink",          "pron": "drínk"},
    {"pt": "porção",         "en": "portion",        "pron": "pórshon"},
    {"pt": "prato do dia",   "en": "dish of the day","pron": "dísh óv de déi"},
    {"pt": "especialidade",  "en": "specialty",      "pron": "spéshalti"},
    {"pt": "sugestão do chef","en": "chef's suggestion","pron": "shéfs soudjestchon"},
    {"pt": "combo",          "en": "combo",          "pron": "kómbou"},
    {"pt": "menu infantil",  "en": "kids menu",      "pron": "kíds ményu"},

    # Utensílios
    {"pt": "prato",          "en": "plate",          "pron": "pléit"},
    {"pt": "copo",           "en": "glass",          "pron": "glés"},
    {"pt": "xícara",         "en": "cup",            "pron": "káp"},
    {"pt": "garfo",          "en": "fork",           "pron": "fórk"},
    {"pt": "faca",           "en": "knife",          "pron": "náif"},
    {"pt": "colher",         "en": "spoon",          "pron": "spún"},
    {"pt": "guardanapo",     "en": "napkin",         "pron": "népkin"},
    {"pt": "toalha de mesa", "en": "tablecloth",     "pron": "téibolkloth"},
    {"pt": "bule",           "en": "kettle",         "pron": "kétol"},
    {"pt": "tigela",         "en": "bowl",           "pron": "bôul"},
    {"pt": "bandeja",        "en": "tray",           "pron": "tréi"},
    {"pt": "canudo",         "en": "straw",          "pron": "stró"},
    {"pt": "palito",         "en": "toothpick",      "pron": "túthpik"},
    {"pt": "cortador de carne","en": "steak knife",  "pron": "stéik náif"},
    {"pt": "tábua",          "en": "cutting board",  "pron": "káting bórd"},
    {"pt": "panela",         "en": "pot",            "pron": "pót"},
    {"pt": "frigideira",     "en": "pan",            "pron": "pén"},

    # Pessoas
    {"pt": "garçom",         "en": "waiter",         "pron": "uéiter"},
    {"pt": "garçonete",      "en": "waitress",       "pron": "uéitres"},
    {"pt": "cozinheiro",     "en": "cook",           "pron": "kúk"},
    {"pt": "chef",           "en": "chef",           "pron": "shéf"},
    {"pt": "cliente",        "en": "customer",       "pron": "kástomer"},
    {"pt": "mesa",           "en": "table",          "pron": "téibol"},
    {"pt": "conta",          "en": "bill",           "pron": "bíl"},
    {"pt": "gorjeta",        "en": "tip",            "pron": "típ"},

    # Bebidas
    {"pt": "água",           "en": "water",          "pron": "uóter"},
    {"pt": "água com gás",   "en": "sparkling water","pron": "spárkling uóter"},
    {"pt": "suco",           "en": "juice",          "pron": "djús"},
    {"pt": "suco de laranja","en": "orange juice",   "pron": "órendj djús"},
    {"pt": "refrigerante",   "en": "soda",           "pron": "sóuda"},
    {"pt": "coca-cola",      "en": "coke",           "pron": "kôuk"},
    {"pt": "café",           "en": "coffee",         "pron": "cófi"},
    {"pt": "café com leite", "en": "latte",          "pron": "látei"},
    {"pt": "chá",            "en": "tea",            "pron": "tí"},
    {"pt": "chá gelado",     "en": "iced tea",       "pron": "áist tí"},
    {"pt": "leite",          "en": "milk",           "pron": "mílk"},
    {"pt": "cerveja",        "en": "beer",           "pron": "bír"},
    {"pt": "vinho",          "en": "wine",           "pron": "uáin"},
    {"pt": "vinho tinto",    "en": "red wine",       "pron": "réd uáin"},
    {"pt": "vinho branco",   "en": "white wine",     "pron": "uáit uáin"},
    {"pt": "vodka",          "en": "vodka",          "pron": "vódka"},
    {"pt": "whisky",         "en": "whiskey",        "pron": "uíski"},
    {"pt": "caipirinha",     "en": "caipirinha",     "pron": "kaipirínia"},
    {"pt": "coquetel",       "en": "cocktail",       "pron": "kóktel"},
    {"pt": "batida",         "en": "milkshake",      "pron": "mílksheik"},
    {"pt": "chocolate quente","en": "hot chocolate", "pron": "rót chóklit"},
    {"pt": "água de coco",   "en": "coconut water",  "pron": "kókonat uóter"},

    # Pratos
    {"pt": "hambúrguer",     "en": "hamburger",      "pron": "rémberger"},
    {"pt": "sanduíche",      "en": "sandwich",       "pron": "sénduich"},
    {"pt": "pizza",          "en": "pizza",          "pron": "pítsa"},
    {"pt": "massa",          "en": "pasta",          "pron": "pásta"},
    {"pt": "lasanha",        "en": "lasagna",        "pron": "lazánia"},
    {"pt": "espaguete",      "en": "spaghetti",      "pron": "spaguéti"},
    {"pt": "sopa",           "en": "soup",           "pron": "súp"},
    {"pt": "salada",         "en": "salad",          "pron": "sélad"},
    {"pt": "salada de frutas","en": "fruit salad",   "pron": "frút sélad"},
    {"pt": "arroz",          "en": "rice",           "pron": "ráis"},
    {"pt": "feijão",         "en": "beans",          "pron": "bíns"},
    {"pt": "batata frita",   "en": "french fries",   "pron": "frénch fráis"},
    {"pt": "purê de batata", "en": "mashed potatoes","pron": "mésht potéitous"},
    {"pt": "bife",           "en": "steak",          "pron": "stéik"},
    {"pt": "frango grelhado","en": "grilled chicken","pron": "gríld chíken"},
    {"pt": "peixe",          "en": "fish",           "pron": "físh"},
    {"pt": "camarão",        "en": "shrimp",         "pron": "shrímp"},
    {"pt": "tacos",          "en": "tacos",          "pron": "tákous"},
    {"pt": "burrito",        "en": "burrito",        "pron": "burítou"},
    {"pt": "sushi",          "en": "sushi",          "pron": "súshi"},
    {"pt": "temaki",         "en": "temaki",         "pron": "temáki"},
    {"pt": "yakisoba",       "en": "yakisoba",       "pron": "iákisóuba"},
    {"pt": "churrasco",      "en": "barbecue",       "pron": "bárbikiu"},
    {"pt": "espetinho",      "en": "skewer",         "pron": "skiúer"},
    {"pt": "panqueca",       "en": "pancake",        "pron": "pénkeik"},
    {"pt": "omelete",        "en": "omelet",         "pron": "ómlet"},
    {"pt": "ovo frito",      "en": "fried egg",      "pron": "fráid ég"},
    {"pt": "torrada",        "en": "toast",          "pron": "tôust"},
    {"pt": "croissant",      "en": "croissant",      "pron": "kroasán"},
    {"pt": "pão de queijo",  "en": "cheese bread",   "pron": "chíz bréd"},

    # Sobremesas
    {"pt": "bolo",           "en": "cake",           "pron": "kéik"},
    {"pt": "bolo de chocolate","en": "chocolate cake","pron": "chóklit kéik"},
    {"pt": "sorvete",        "en": "ice cream",      "pron": "áis krím"},
    {"pt": "pudim",          "en": "pudding",        "pron": "púding"},
    {"pt": "torta",          "en": "pie",            "pron": "pái"},
    {"pt": "brownie",        "en": "brownie",        "pron": "bráuni"},
    {"pt": "donut",          "en": "donut",          "pron": "dôunat"},
    {"pt": "biscoito",       "en": "cookie",         "pron": "kúki"},
    {"pt": "chocolate",      "en": "chocolate",      "pron": "chóklit"},
    {"pt": "bala",           "en": "candy",          "pron": "kéndi"},
    {"pt": "chiclete",       "en": "chewing gum",    "pron": "chúing gám"},
    {"pt": "gelatina",       "en": "jelly",          "pron": "djéli"},

    # Temperos/ingredientes
    {"pt": "sal",            "en": "salt",           "pron": "sólt"},
    {"pt": "pimenta",        "en": "pepper",         "pron": "péper"},
    {"pt": "açúcar",         "en": "sugar",          "pron": "shúgar"},
    {"pt": "azeite",         "en": "olive oil",      "pron": "óliv óil"},
    {"pt": "vinagre",        "en": "vinegar",        "pron": "vínegar"},
    {"pt": "molho",          "en": "sauce",          "pron": "sós"},
    {"pt": "ketchup",        "en": "ketchup",        "pron": "kétchap"},
    {"pt": "mostarda",       "en": "mustard",        "pron": "mástard"},
    {"pt": "maionese",       "en": "mayonnaise",     "pron": "meionéis"},
    {"pt": "manteiga",       "en": "butter",         "pron": "báter"},
    {"pt": "queijo",         "en": "cheese",         "pron": "chíz"},
    {"pt": "presunto",       "en": "ham",            "pron": "rém"},
    {"pt": "bacon",          "en": "bacon",          "pron": "béikon"},
    {"pt": "alface",         "en": "lettuce",        "pron": "létis"},
    {"pt": "tomate",         "en": "tomato",         "pron": "toméitou"},
    {"pt": "cebola",         "en": "onion",          "pron": "ániôn"},
    {"pt": "alho",           "en": "garlic",         "pron": "gárlik"},
    {"pt": "picles",         "en": "pickles",        "pron": "píkols"},
    {"pt": "azeitona",       "en": "olive",          "pron": "óliv"},

    # Ações
    {"pt": "pedir",          "en": "to order",       "pron": "tu órder"},
    {"pt": "reservar",       "en": "to reserve",     "pron": "tu rizérv"},
    {"pt": "servir",         "en": "to serve",       "pron": "tu sérv"},
    {"pt": "provar",         "en": "to taste",       "pron": "tu téist"},
    {"pt": "comer",          "en": "to eat",         "pron": "tu ít"},
    {"pt": "beber",          "en": "to drink",       "pron": "tu drínk"},
    {"pt": "pagar",          "en": "to pay",         "pron": "tu péi"},
    {"pt": "dividir a conta","en": "to split the bill","pron": "tu splít de bíl"},
    {"pt": "levar para casa","en": "to take away",   "pron": "tu téik auéi"},

    # Frases
    {"pt": "eu quero...",       "en": "I want...",        "pron": "ái uónt"},
    {"pt": "eu gostaria de...", "en": "I would like...",  "pron": "ái uúd láik"},
    {"pt": "para mim...",       "en": "for me...",        "pron": "fór mi"},
    {"pt": "me vê...",          "en": "can I have...",    "pron": "kén ái rév"},
    {"pt": "uma mesa para dois","en": "a table for two",  "pron": "e téibol fór tú"},
    {"pt": "o cardápio, por favor","en": "the menu, please","pron": "de ményu plíz"},
    {"pt": "a conta, por favor","en": "the bill, please", "pron": "de bíl plíz"},
    {"pt": "sem gelo",          "en": "no ice",           "pron": "nôu áis"},
    {"pt": "com gelo",          "en": "with ice",         "pron": "uíth áis"},
    {"pt": "sem açúcar",        "en": "no sugar",         "pron": "nôu shúgar"},
    {"pt": "bem passado",       "en": "well done",        "pron": "uél dán"},
    {"pt": "mal passado",       "en": "rare",             "pron": "rér"},
    {"pt": "ao ponto",          "en": "medium",           "pron": "mídium"},
    {"pt": "vegetariano",       "en": "vegetarian",       "pron": "vedjetérion"},
    {"pt": "sem carne",         "en": "no meat",          "pron": "nôu mít"},
    {"pt": "para viagem",       "en": "to go",            "pron": "tu gôu"},
    {"pt": "para levar",        "en": "takeaway",         "pron": "téikauéi"},
    {"pt": "está delicioso",    "en": "it's delicious",   "pron": "its dilíshas"},
    {"pt": "está muito bom",    "en": "it's very good",   "pron": "its véri gúd"},
    {"pt": "estou satisfeito",  "en": "I'm full",         "pron": "áim fúl"},
    {"pt": "bom apetite",       "en": "enjoy your meal",  "pron": "endjói iór míl"},
    {"pt": "saúde!",            "en": "cheers!",          "pron": "chírs"},
    {"pt": "você recomenda algo?","en": "do you recommend something?","pron": "du iu rekuménd sámthing"},
    {"pt": "qual o prato do dia?","en": "what's the dish of the day?","pron": "uóts de dísh óv de déi"},
    {"pt": "pode trazer mais água?","en": "can you bring more water?","pron": "kén iu bríng mór uóter"},
    {"pt": "está incluso o serviço?","en": "is service included?","pron": "is sérvis inklúdid"},
    {"pt": "posso pagar com cartão?","en": "can I pay with card?","pron": "kén ái péi uíth kárd"},
    {"pt": "tem opção sem lactose?","en": "is there a lactose-free option?","pron": "is dér e léktous frí ópshon"},
    {"pt": "tem opção vegana?", "en": "is there a vegan option?","pron": "is dér e vígan ópshon"},
    {"pt": "tem opção sem glúten?","en": "is there a gluten-free option?","pron": "is dér e glúten frí ópshon"},
    {"pt": "pode esquentar?",   "en": "can you heat it up?","pron": "kén iu rít it áp"},
    {"pt": "está frio",         "en": "it's cold",        "pron": "its kôuld"},
    {"pt": "está muito salgado","en": "it's too salty",   "pron": "its tú sól ti"},
    {"pt": "está sem sal",      "en": "it's bland",       "pron": "its blénd"},
    {"pt": "gostaria de reservar uma mesa","en": "I'd like to reserve a table","pron": "áid láik tu rizérv e téibol"},
    {"pt": "para quantas pessoas?","en": "for how many people?","pron": "fór rá máni pípou"},
    {"pt": "quanto tempo de espera?","en": "how long is the wait?","pron": "ráu long is de uéit"},
    {"pt": "pode dividir a conta?","en": "can we split the bill?","pron": "kén uí splít de bíl"},
    {"pt": "aceita vale-refeição?","en": "do you accept meal vouchers?","pron": "du iu aksépt míl váuchers"},
]

# ============ 🏙️ LUGARES NA CIDADE (150) ============
lugares = [
    # Comércio
    {"pt": "loja",           "en": "store",          "pron": "stór"},
    {"pt": "supermercado",   "en": "supermarket",    "pron": "súpermárkit"},
    {"pt": "mercado",        "en": "market",         "pron": "márkit"},
    {"pt": "shopping",       "en": "mall",           "pron": "mól"},
    {"pt": "livraria",       "en": "bookstore",      "pron": "búkstor"},
    {"pt": "farmácia",       "en": "pharmacy",       "pron": "fármasi"},
    {"pt": "padaria",        "en": "bakery",         "pron": "béikeri"},
    {"pt": "açougue",        "en": "butcher shop",   "pron": "búcher shóp"},
    {"pt": "floricultura",   "en": "flower shop",    "pron": "fláuer shóp"},
    {"pt": "sapataria",      "en": "shoe store",     "pron": "shú stór"},
    {"pt": "banca de jornal","en": "newsstand",      "pron": "niússténd"},
    {"pt": "loja de roupas", "en": "clothing store", "pron": "klôudhing stór"},
    {"pt": "joalheria",      "en": "jewelry store",  "pron": "djúelri stór"},
    {"pt": "papelaria",      "en": "stationery store","pron": "stéishoneri stór"},
    {"pt": "loja de brinquedos","en": "toy store",   "pron": "tói stór"},
    {"pt": "loja de eletrônicos","en": "electronics store","pron": "elektróniks stór"},
    {"pt": "loja de móveis", "en": "furniture store","pron": "férnichur stór"},
    {"pt": "loja de plantas","en": "plant shop",     "pron": "plént shóp"},
    {"pt": "pet shop",       "en": "pet shop",       "pron": "pét shóp"},
    {"pt": "loja de departamento","en": "department store","pron": "dipártment stór"},

    # Serviços
    {"pt": "banco",          "en": "bank",           "pron": "bénk"},
    {"pt": "correio",        "en": "post office",    "pron": "pôust ófis"},
    {"pt": "delegacia",      "en": "police station", "pron": "polís stéishon"},
    {"pt": "hospital",       "en": "hospital",       "pron": "róspital"},
    {"pt": "clínica",        "en": "clinic",         "pron": "klínik"},
    {"pt": "consultório",    "en": "doctor's office","pron": "dóktors ófis"},
    {"pt": "dentista",       "en": "dentist's office","pron": "déntists ófis"},
    {"pt": "salão de beleza","en": "beauty salon",   "pron": "biúti sélon"},
    {"pt": "barbearia",      "en": "barber shop",    "pron": "bárber shóp"},
    {"pt": "lavanderia",     "en": "laundry",        "pron": "lóndri"},
    {"pt": "oficina",        "en": "repair shop",    "pron": "ripér shóp"},
    {"pt": "posto de gasolina","en": "gas station",  "pron": "gués stéishon"},
    {"pt": "estacionamento", "en": "parking lot",    "pron": "párking lót"},
    {"pt": "hotel",          "en": "hotel",          "pron": "routél"},
    {"pt": "pousada",        "en": "inn",            "pron": "ín"},
    {"pt": "hostel",         "en": "hostel",         "pron": "róstel"},
    {"pt": "cartório",       "en": "notary office",  "pron": "nóutari ófis"},
    {"pt": "escritório",     "en": "office",         "pron": "ófis"},
    {"pt": "coworking",      "en": "coworking space","pron": "kóu uórking spéis"},
    {"pt": "agência de viagens","en": "travel agency","pron": "trévol éidjensi"},
    {"pt": "imobiliária",    "en": "real estate agency","pron": "ríol istéit éidjensi"},
    {"pt": "seguradora",     "en": "insurance company","pron": "inshúrans kámpani"},
    {"pt": "advocacia",      "en": "law firm",       "pron": "ló férm"},
    {"pt": "contabilidade",  "en": "accounting firm", "pron": "akáunting férm"},

    # Educação e cultura
    {"pt": "escola",         "en": "school",         "pron": "skúl"},
    {"pt": "universidade",   "en": "university",     "pron": "iunivérsiti"},
    {"pt": "faculdade",      "en": "college",        "pron": "kólidj"},
    {"pt": "biblioteca",     "en": "library",        "pron": "láibreri"},
    {"pt": "museu",          "en": "museum",         "pron": "miuzíum"},
    {"pt": "teatro",         "en": "theater",        "pron": "thíater"},
    {"pt": "cinema",         "en": "cinema",         "pron": "sínema"},
    {"pt": "galeria de arte","en": "art gallery",    "pron": "árt gélari"},
    {"pt": "centro cultural","en": "cultural center","pron": "kálchural sénter"},
    {"pt": "auditório",      "en": "auditorium",     "pron": "óditórium"},
    {"pt": "casa de shows",  "en": "concert hall",   "pron": "kónsert ról"},

    # Lazer
    {"pt": "parque",         "en": "park",           "pron": "párk"},
    {"pt": "praça",          "en": "square",         "pron": "skué r"},
    {"pt": "zoológico",      "en": "zoo",            "pron": "zú"},
    {"pt": "praia",          "en": "beach",          "pron": "bích"},
    {"pt": "piscina",        "en": "pool",           "pron": "púl"},
    {"pt": "academia",       "en": "gym",            "pron": "djím"},
    {"pt": "estádio",        "en": "stadium",        "pron": "stéidium"},
    {"pt": "quadra",         "en": "court",          "pron": "kórt"},
    {"pt": "campo de futebol","en": "soccer field",  "pron": "sóker fíld"},
    {"pt": "parque de diversões","en": "amusement park","pron": "amiúzment párk"},
    {"pt": "circo",          "en": "circus",         "pron": "sérkas"},
    {"pt": "aquário",        "en": "aquarium",       "pron": "akuérium"},
    {"pt": "bowling",        "en": "bowling",        "pron": "bôuling"},
    {"pt": "restaurante",    "en": "restaurant",     "pron": "réstorant"},
    {"pt": "bar",            "en": "bar",            "pron": "bár"},
    {"pt": "café",           "en": "café",           "pron": "kaféi"},
    {"pt": "boate",          "en": "nightclub",      "pron": "náitklab"},
    {"pt": "pub",            "en": "pub",            "pron": "páb"},
    {"pt": "karaokê",        "en": "karaoke",        "pron": "kariôuki"},
    {"pt": "spa",            "en": "spa",            "pron": "spá"},

    # Religiosos
    {"pt": "igreja",         "en": "church",         "pron": "chérch"},
    {"pt": "templo",         "en": "temple",         "pron": "témpol"},
    {"pt": "mesquita",       "en": "mosque",         "pron": "mósk"},
    {"pt": "sinagoga",       "en": "synagogue",      "pron": "sínagog"},
    {"pt": "catedral",       "en": "cathedral",      "pron": "kathídral"},
    {"pt": "capela",         "en": "chapel",         "pron": "chépel"},
    {"pt": "cemitério",      "en": "cemetery",       "pron": "sémetéri"},

    # Estrutura urbana
    {"pt": "prédio",         "en": "building",       "pron": "bílding"},
    {"pt": "casa",           "en": "house",          "pron": "ráus"},
    {"pt": "apartamento",    "en": "apartment",      "pron": "apártment"},
    {"pt": "rua",            "en": "street",         "pron": "strít"},
    {"pt": "avenida",        "en": "avenue",         "pron": "évenu"},
    {"pt": "praça central",  "en": "town square",    "pron": "táun skué r"},
    {"pt": "ponte",          "en": "bridge",         "pron": "brídj"},
    {"pt": "rio",            "en": "river",          "pron": "ríver"},
    {"pt": "centro",         "en": "downtown",       "pron": "dáuntáun"},
    {"pt": "bairro",         "en": "neighborhood",   "pron": "néiborhud"},
    {"pt": "cidade",         "en": "city",           "pron": "síti"},
    {"pt": "vila",           "en": "village",        "pron": "vílej"},
    {"pt": "subúrbio",       "en": "suburb",         "pron": "sábérb"},
    {"pt": "arranha-céu",    "en": "skyscraper",     "pron": "skáiskreipor"},
    {"pt": "praça de alimentação","en": "food court","pron": "fúd kórt"},
    {"pt": "calçadão",       "en": "promenade",      "pron": "promenád"},
    {"pt": "viaduto",        "en": "overpass",       "pron": "ôuverpés"},
    {"pt": "túnel",          "en": "tunnel",         "pron": "tánel"},
    {"pt": "beco",           "en": "alley",          "pron": "éli"},
    {"pt": "largo",          "en": "plaza",          "pron": "pláza"},
    {"pt": "rotatória",      "en": "roundabout",     "pron": "ráundabáut"},
    {"pt": "cruzamento",     "en": "intersection",   "pron": "intersékshon"},
    {"pt": "esquina",        "en": "corner",         "pron": "kórner"},
    {"pt": "calçada",        "en": "sidewalk",       "pron": "sáiduók"},
    {"pt": "faixa de pedestre","en": "crosswalk",    "pron": "krósuók"},
    {"pt": "semáforo",       "en": "traffic light",  "pron": "tréfik láit"},
    {"pt": "lixeira pública","en": "trash can",      "pron": "trésh kén"},
    {"pt": "banco de praça", "en": "bench",          "pron": "bénch"},
    {"pt": "fonte",          "en": "fountain",       "pron": "fáunten"},
    {"pt": "estátua",        "en": "statue",         "pron": "stétchu"},
    {"pt": "monumento",      "en": "monument",       "pron": "móniument"},

    # Serviços públicos
    {"pt": "prefeitura",     "en": "city hall",      "pron": "síti ról"},
    {"pt": "fórum",          "en": "courthouse",     "pron": "kórtráus"},
    {"pt": "posto de saúde", "en": "health center",  "pron": "rélth sénter"},
    {"pt": "UPA",            "en": "emergency care", "pron": "imérdjensi kér"},
    {"pt": "bombeiros",      "en": "fire station",   "pron": "fáier stéishon"},
    {"pt": "exército",       "en": "army",           "pron": "ármi"},
    {"pt": "consulado",      "en": "consulate",      "pron": "kónsulat"},
    {"pt": "embaixada",      "en": "embassy",        "pron": "émbesi"},
    {"pt": "aeroporto",      "en": "airport",        "pron": "érport"},
    {"pt": "rodoviária",     "en": "bus station",    "pron": "bás stéishon"},
    {"pt": "estação de trem","en": "train station",  "pron": "tréin stéishon"},
    {"pt": "estação de metrô","en": "subway station","pron": "sábuei stéishon"},
    {"pt": "porto",          "en": "port",           "pron": "pórt"},

    # Pontos turísticos
    {"pt": "ponto turístico","en": "tourist spot",   "pron": "túrist spót"},
    {"pt": "mirante",        "en": "viewpoint",      "pron": "viúpoint"},
    {"pt": "parque nacional","en": "national park",  "pron": "néshonal párk"},
    {"pt": "cachoeira",      "en": "waterfall",      "pron": "uóterfól"},
    {"pt": "montanha",       "en": "mountain",       "pron": "máunten"},
    {"pt": "ilha",           "en": "island",         "pron": "áiland"},
    {"pt": "farol",          "en": "lighthouse",     "pron": "láitr áus"},
    {"pt": "ruínas",         "en": "ruins",          "pron": "rúins"},
    {"pt": "castelo",        "en": "castle",         "pron": "késol"},
    {"pt": "palácio",        "en": "palace",         "pron": "pélis"},

    # Frases
    {"pt": "onde fica?",         "en": "where is it?",       "pron": "uér is it"},
    {"pt": "como chego lá?",     "en": "how do I get there?", "pron": "ráu du ái guét dér"},
    {"pt": "é longe?",           "en": "is it far?",          "pron": "is it fár"},
    {"pt": "é perto?",           "en": "is it near?",         "pron": "is it nír"},
    {"pt": "tem algum restaurante aqui perto?","en": "is there a restaurant nearby?","pron": "is dér e réstorant nírbai"},
    {"pt": "que bairro é esse?","en": "what neighborhood is this?","pron": "uót néiborhud is dis"},
    {"pt": "estou procurando...","en": "I'm looking for...",  "pron": "áim lúking fór"},
    {"pt": "qual o endereço?",   "en": "what's the address?", "pron": "uóts de édres"},
    {"pt": "pode me mostrar no mapa?","en": "can you show me on the map?","pron": "kén iu shôu mi ón de mép"},
    {"pt": "que horas fecha?",   "en": "what time does it close?","pron": "uót táim dáz it klôuz"},
    {"pt": "está aberto agora?","en": "is it open now?",     "pron": "is it ôupen náu"},
    {"pt": "que dia fecha?",     "en": "what day does it close?","pron": "uót déi dáz it klôuz"},
    {"pt": "precisa de reserva?","en": "do I need a reservation?","pron": "du ái níd e rezervéishon"},
    {"pt": "tem estacionamento?","en": "is there parking?",  "pron": "is dér párking"},
    {"pt": "tem wi-fi?",         "en": "is there wi-fi?",    "pron": "is dér uáifái"},
    {"pt": "aceita pets?",       "en": "are pets allowed?",  "pron": "ár péts aláud"},
]

# ============ 📅 DIAS E MESES (150) ============
datas = [
    # Dias da semana
    {"pt": "segunda-feira",  "en": "Monday",         "pron": "mándei"},
    {"pt": "terça-feira",    "en": "Tuesday",        "pron": "tiúsdei"},
    {"pt": "quarta-feira",   "en": "Wednesday",      "pron": "uénsdei"},
    {"pt": "quinta-feira",   "en": "Thursday",       "pron": "thérsdei"},
    {"pt": "sexta-feira",    "en": "Friday",         "pron": "fráidei"},
    {"pt": "sábado",         "en": "Saturday",       "pron": "séteredéi"},
    {"pt": "domingo",        "en": "Sunday",         "pron": "sándei"},
    {"pt": "fim de semana",  "en": "weekend",        "pron": "uíkend"},
    {"pt": "dia útil",       "en": "weekday",        "pron": "uíkdei"},
    {"pt": "feriado",        "en": "holiday",        "pron": "rólidei"},

    # Meses
    {"pt": "janeiro",        "en": "January",        "pron": "djéniueri"},
    {"pt": "fevereiro",      "en": "February",       "pron": "fébrueri"},
    {"pt": "março",          "en": "March",          "pron": "márch"},
    {"pt": "abril",          "en": "April",          "pron": "éipril"},
    {"pt": "maio",           "en": "May",            "pron": "méi"},
    {"pt": "junho",          "en": "June",           "pron": "djún"},
    {"pt": "julho",          "en": "July",           "pron": "djulái"},
    {"pt": "agosto",         "en": "August",         "pron": "ógost"},
    {"pt": "setembro",       "en": "September",      "pron": "septémber"},
    {"pt": "outubro",        "en": "October",        "pron": "októuber"},
    {"pt": "novembro",       "en": "November",       "pron": "novémber"},
    {"pt": "dezembro",       "en": "December",       "pron": "disémber"},

    # Estações
    {"pt": "primavera",      "en": "spring",         "pron": "spríng"},
    {"pt": "verão",          "en": "summer",         "pron": "sámer"},
    {"pt": "outono",         "en": "autumn",         "pron": "ótom"},
    {"pt": "inverno",        "en": "winter",         "pron": "uínter"},

    # Períodos
    {"pt": "hoje",           "en": "today",          "pron": "tudéi"},
    {"pt": "amanhã",         "en": "tomorrow",       "pron": "tumórou"},
    {"pt": "ontem",          "en": "yesterday",      "pron": "iéstérdéi"},
    {"pt": "anteontem",      "en": "day before yesterday","pron": "déi bifór iéstérdéi"},
    {"pt": "depois de amanhã","en": "day after tomorrow","pron": "déi éfter tumórou"},
    {"pt": "agora",          "en": "now",            "pron": "náu"},
    {"pt": "depois",         "en": "later",          "pron": "léiter"},
    {"pt": "mais tarde",     "en": "later on",       "pron": "léiter ón"},
    {"pt": "cedo",           "en": "early",          "pron": "érli"},
    {"pt": "tarde",          "en": "late",           "pron": "léit"},
    {"pt": "manhã",          "en": "morning",        "pron": "mórning"},
    {"pt": "tarde (período)", "en": "afternoon",     "pron": "áfternun"},
    {"pt": "noite",          "en": "night",          "pron": "náit"},
    {"pt": "madrugada",      "en": "dawn",           "pron": "dón"},
    {"pt": "meio-dia",       "en": "noon",           "pron": "nún"},
    {"pt": "meia-noite",     "en": "midnight",       "pron": "mídnáit"},
    {"pt": "esta noite",     "en": "tonight",        "pron": "tunáit"},
    {"pt": "esta manhã",     "en": "this morning",   "pron": "dis mórning"},
    {"pt": "esta tarde",     "en": "this afternoon", "pron": "dis áfternun"},

    # Divisões de tempo
    {"pt": "dia",            "en": "day",            "pron": "déi"},
    {"pt": "semana",         "en": "week",           "pron": "uík"},
    {"pt": "quinzena",       "en": "fortnight",      "pron": "fórtnáit"},
    {"pt": "mês",            "en": "month",          "pron": "mánth"},
    {"pt": "bimestre",       "en": "two months",     "pron": "tú mánths"},
    {"pt": "trimestre",      "en": "quarter",        "pron": "kuórter"},
    {"pt": "semestre",       "en": "semester",       "pron": "siméster"},
    {"pt": "ano",            "en": "year",           "pron": "íer"},
    {"pt": "década",         "en": "decade",         "pron": "dékeid"},
    {"pt": "século",         "en": "century",        "pron": "sénchuri"},
    {"pt": "milênio",        "en": "millennium",     "pron": "milénium"},
    {"pt": "hora",           "en": "hour",           "pron": "áuer"},
    {"pt": "minuto",         "en": "minute",         "pron": "mínit"},
    {"pt": "segundo",        "en": "second",         "pron": "sékond"},
    {"pt": "instante",       "en": "instant",        "pron": "ínstant"},
    {"pt": "momento",        "en": "moment",         "pron": "môument"},
    {"pt": "passado",        "en": "past",           "pron": "pést"},
    {"pt": "presente",       "en": "present",        "pron": "prézant"},
    {"pt": "futuro",         "en": "future",         "pron": "fiúchur"},

    # Calendário
    {"pt": "calendário",     "en": "calendar",       "pron": "kélendar"},
    {"pt": "data",           "en": "date",           "pron": "déit"},
    {"pt": "aniversário",    "en": "birthday",       "pron": "bérthdéi"},
    {"pt": "ano novo",       "en": "new year",       "pron": "niú íer"},
    {"pt": "natal",          "en": "Christmas",      "pron": "krísmass"},
    {"pt": "páscoa",         "en": "Easter",         "pron": "íster"},
    {"pt": "carnaval",       "en": "carnival",       "pron": "kárnivol"},
    {"pt": "dia das mães",   "en": "Mother's Day",   "pron": "máders déi"},
    {"pt": "dia dos pais",   "en": "Father's Day",   "pron": "fáders déi"},
    {"pt": "dia dos namorados","en": "Valentine's Day","pron": "vélentains déi"},
    {"pt": "halloween",      "en": "Halloween",      "pron": "rélouín"},
    {"pt": "ação de graças", "en": "Thanksgiving",   "pron": "thénksguíving"},
    {"pt": "feriado nacional","en": "national holiday","pron": "néshonal rólidei"},
    {"pt": "feriado religioso","en": "religious holiday","pron": "rilídjas rólidei"},

    # Números ordinais
    {"pt": "primeiro",       "en": "first",          "pron": "férst"},
    {"pt": "segundo",        "en": "second",         "pron": "sékond"},
    {"pt": "terceiro",       "en": "third",          "pron": "thérd"},
    {"pt": "quarto",         "en": "fourth",         "pron": "fórth"},
    {"pt": "quinto",         "en": "fifth",          "pron": "fífth"},
    {"pt": "sexto",          "en": "sixth",          "pron": "síksth"},
    {"pt": "sétimo",         "en": "seventh",        "pron": "séventh"},
    {"pt": "oitavo",         "en": "eighth",         "pron": "éith"},
    {"pt": "nono",           "en": "ninth",          "pron": "náinth"},
    {"pt": "décimo",         "en": "tenth",          "pron": "ténth"},

    # Frequência
    {"pt": "sempre",         "en": "always",         "pron": "ólueis"},
    {"pt": "nunca",          "en": "never",          "pron": "néver"},
    {"pt": "às vezes",       "en": "sometimes",      "pron": "sámtáims"},
    {"pt": "frequentemente", "en": "often",          "pron": "ófen"},
    {"pt": "raramente",      "en": "rarely",         "pron": "rérli"},
    {"pt": "todos os dias",  "en": "every day",      "pron": "évri déi"},
    {"pt": "toda semana",    "en": "every week",     "pron": "évri uík"},
    {"pt": "todo mês",       "en": "every month",    "pron": "évri mánth"},
    {"pt": "todo ano",       "en": "every year",     "pron": "évri íer"},
    {"pt": "de vez em quando","en": "once in a while","pron": "uáns in e uáil"},
    {"pt": "diariamente",    "en": "daily",          "pron": "déili"},
    {"pt": "semanalmente",   "en": "weekly",         "pron": "uíkli"},
    {"pt": "mensalmente",    "en": "monthly",        "pron": "mánthli"},
    {"pt": "anualmente",     "en": "yearly",         "pron": "íerli"},
    {"pt": "de novo",        "en": "again",          "pron": "aguén"},

    # Frases
    {"pt": "que dia é hoje?",     "en": "what day is it today?","pron": "uót déi is it tudéi"},
    {"pt": "hoje é segunda",      "en": "today is Monday",     "pron": "tudéi is mándei"},
    {"pt": "que horas são?",      "en": "what time is it?",    "pron": "uót táim is it"},
    {"pt": "que dia é amanhã?",   "en": "what day is tomorrow?","pron": "uót déi is tumórou"},
    {"pt": "nos vemos amanhã",    "en": "see you tomorrow",    "pron": "sí iu tumórou"},
    {"pt": "nos vemos na segunda","en": "see you on Monday",   "pron": "sí iu ón mándei"},
    {"pt": "que semana longa!",   "en": "what a long week!",   "pron": "uót e long uík"},
    {"pt": "boa semana!",         "en": "have a good week!",   "pron": "rév e gúd uík"},
    {"pt": "bom fim de semana!",  "en": "have a nice weekend!","pron": "rév e náis uíkend"},
    {"pt": "até amanhã",          "en": "until tomorrow",      "pron": "antíl tumórou"},
    {"pt": "que horas você pode?","en": "what time can you?",  "pron": "uót táim kén iu"},
    {"pt": "estou atrasado",      "en": "I'm late",            "pron": "áim léit"},
    {"pt": "cheguei cedo",        "en": "I arrived early",     "pron": "ái aráivd érli"},
    {"pt": "que horas começa?",   "en": "what time does it start?","pron": "uót táim dáz it stárt"},
    {"pt": "quanto tempo dura?",  "en": "how long does it last?","pron": "ráu long dáz it lést"},
    {"pt": "daqui a pouco",       "en": "in a bit",            "pron": "in e bít"},
    {"pt": "mais cedo",           "en": "earlier",             "pron": "érlier"},
    {"pt": "mais tarde",          "en": "later",               "pron": "léiter"},
    {"pt": "nos próximos dias",   "en": "in the next days",    "pron": "in de nékst déis"},
    {"pt": "que dia cai o feriado?","en": "what day is the holiday?","pron": "uót déi is de rólidei"},
]

# ============ ESCREVER ============
modulos = {
    "verbos":      verbos,
    "perguntas":   perguntas,
    "emocoes":     emocoes,
    "dinheiro":    dinheiro,
    "restaurante": restaurante,
    "lugares":     lugares,
    "datas":       datas,
}

for nome, dados in modulos.items():
    caminho = PASTA / f"{nome}.json"
    with open(caminho, "w", encoding="utf-8") as f:
        json.dump(dados, f, ensure_ascii=False, indent=2)
    print(f"OK: {nome}.json ({len(dados)} itens)")

print()
print("=" * 50)
print("Lote 2 BR (Intermediario expandido) preenchido!")
print("Reinicie o Streamlit pra ver o conteudo.")
print("=" * 50)