import json
from pathlib import Path

BASE = Path(__file__).parent
PASTA = BASE / "dados" / "russo"

animais = [
    {"pt": "cachorro",           "ru": "собака",        "pron": "sabáka"},
    {"pt": "gato",               "ru": "кошка",         "pron": "kóshka"},
    {"pt": "pássaro",            "ru": "птица",         "pron": "ptítsa"},
    {"pt": "peixe",              "ru": "рыба",          "pron": "ríba"},
    {"pt": "hamster",            "ru": "хомяк",         "pron": "khamyák"},
    {"pt": "coelho",             "ru": "кролик",        "pron": "królik"},
    {"pt": "papagaio",           "ru": "попугай",       "pron": "papugái"},
    {"pt": "tartaruga",          "ru": "черепаха",      "pron": "chiripákha"},
    {"pt": "porquinho-da-índia", "ru": "морская свинка","pron": "morskáya svínka"},
    {"pt": "cavalo",             "ru": "лошадь",        "pron": "lóshad"},
    {"pt": "vaca",               "ru": "корова",        "pron": "karóva"},
    {"pt": "boi",                "ru": "бык",           "pron": "bik"},
    {"pt": "bezerro",            "ru": "телёнок",       "pron": "tilyónak"},
    {"pt": "porco",              "ru": "свинья",        "pron": "svin'yá"},
    {"pt": "ovelha",             "ru": "овца",          "pron": "aftsá"},
    {"pt": "cordeiro",           "ru": "ягнёнок",       "pron": "yagnyónak"},
    {"pt": "cabra",              "ru": "коза",          "pron": "kazá"},
    {"pt": "galinha",            "ru": "курица",        "pron": "kúritsa"},
    {"pt": "galo",               "ru": "петух",         "pron": "pitúkh"},
    {"pt": "pintinho",           "ru": "цыплёнок",      "pron": "tsiplyónak"},
    {"pt": "pato",               "ru": "утка",          "pron": "útka"},
    {"pt": "ganso",              "ru": "гусь",          "pron": "gus"},
    {"pt": "peru",               "ru": "индейка",       "pron": "indéika"},
    {"pt": "burro",              "ru": "осёл",          "pron": "asyól"},
    {"pt": "mula",               "ru": "мул",           "pron": "mul"},
    {"pt": "leão",               "ru": "лев",           "pron": "lev"},
    {"pt": "leoa",               "ru": "львица",        "pron": "l'vítsa"},
    {"pt": "tigre",              "ru": "тигр",          "pron": "tigr"},
    {"pt": "elefante",           "ru": "слон",          "pron": "slon"},
    {"pt": "macaco",             "ru": "обезьяна",      "pron": "abiz'yána"},
    {"pt": "gorila",             "ru": "горилла",       "pron": "garíla"},
    {"pt": "urso",               "ru": "медведь",       "pron": "midvéd"},
    {"pt": "lobo",               "ru": "волк",          "pron": "volk"},
    {"pt": "raposa",             "ru": "лиса",          "pron": "lisá"},
    {"pt": "cervo",              "ru": "олень",         "pron": "alén"},
    {"pt": "esquilo",            "ru": "белка",         "pron": "bélka"},
    {"pt": "morcego",            "ru": "летучая мышь",  "pron": "litúchaya mish"},
    {"pt": "rato",               "ru": "мышь",          "pron": "mish"},
    {"pt": "ratazana",           "ru": "крыса",         "pron": "krísa"},
    {"pt": "coala",              "ru": "коала",         "pron": "koála"},
    {"pt": "panda",              "ru": "панда",         "pron": "pánda"},
    {"pt": "girafa",             "ru": "жираф",         "pron": "jiráf"},
    {"pt": "zebra",              "ru": "зебра",         "pron": "zébra"},
    {"pt": "rinoceronte",        "ru": "носорог",       "pron": "nasaróg"},
    {"pt": "hipopótamo",         "ru": "бегемот",       "pron": "bigimót"},
    {"pt": "camelo",             "ru": "верблюд",       "pron": "virblúd"},
    {"pt": "lontra",             "ru": "выдра",         "pron": "vídra"},
    {"pt": "foca",               "ru": "тюлень",        "pron": "tyulén"},
    {"pt": "baleia",             "ru": "кит",           "pron": "kit"},
    {"pt": "golfinho",           "ru": "дельфин",       "pron": "dil'fín"},
    {"pt": "tubarão",            "ru": "акула",         "pron": "akúla"},
    {"pt": "cobra",              "ru": "змея",          "pron": "zmiyá"},
    {"pt": "lagarto",            "ru": "ящерица",       "pron": "yásheritsa"},
    {"pt": "jacaré",             "ru": "аллигатор",     "pron": "aligátor"},
    {"pt": "crocodilo",          "ru": "крокодил",      "pron": "krakadíl"},
    {"pt": "sapo",               "ru": "жаба",          "pron": "zhába"},
    {"pt": "rã",                 "ru": "лягушка",       "pron": "ligúshka"},
    {"pt": "camaleão",           "ru": "хамелеон",      "pron": "khamileón"},
    {"pt": "águia",              "ru": "орёл",          "pron": "aryól"},
    {"pt": "coruja",             "ru": "сова",          "pron": "savá"},
    {"pt": "falção",             "ru": "сокол",         "pron": "sókal"},
    {"pt": "pombo",              "ru": "голубь",        "pron": "gólub"},
    {"pt": "gaivota",            "ru": "чайка",         "pron": "cháika"},
    {"pt": "pinguim",            "ru": "пингвин",       "pron": "pingvín"},
    {"pt": "avestruz",           "ru": "страус",        "pron": "stráus"},
    {"pt": "flamingo",           "ru": "фламинго",      "pron": "flamínga"},
    {"pt": "tucano",             "ru": "тукан",         "pron": "tukán"},
    {"pt": "beija-flor",         "ru": "колибри",       "pron": "kalíbri"},
    {"pt": "aranha",             "ru": "паук",          "pron": "paúk"},
    {"pt": "abelha",             "ru": "пчела",         "pron": "pchilá"},
    {"pt": "borboleta",          "ru": "бабочка",       "pron": "bábichka"},
    {"pt": "formiga",            "ru": "муравей",       "pron": "muravéi"},
    {"pt": "mosquito",           "ru": "комар",         "pron": "kamár"},
    {"pt": "mosca",              "ru": "муха",          "pron": "múkha"},
    {"pt": "barata",             "ru": "таракан",       "pron": "tarakán"},
    {"pt": "besouro",            "ru": "жук",           "pron": "zhuk"},
    {"pt": "grilo",              "ru": "сверчок",       "pron": "svirchók"},
    {"pt": "escorpião",          "ru": "скорпион",      "pron": "skarpión"},
    {"pt": "caracol",            "ru": "улитка",        "pron": "ulítka"},
    {"pt": "minhoca",            "ru": "червяк",        "pron": "chirvyák"},
    {"pt": "lagarta",            "ru": "гусеница",      "pron": "gúsenitsa"},
    {"pt": "o cachorro late",    "ru": "собака лает",   "pron": "sabáka láet"},
    {"pt": "o gato mia",         "ru": "кошка мяукает", "pron": "kóshka myaúkaet"},
    {"pt": "a vaca muge",        "ru": "корова мычит",  "pron": "karóva michít"},
    {"pt": "o cavalo relincha",  "ru": "лошадь ржёт",   "pron": "lóshad rzhot"},
    {"pt": "o galo canta",       "ru": "петух поёт",    "pron": "pitúkh payót"},
    {"pt": "o pássaro canta",    "ru": "птица поёт",    "pron": "ptítsa payót"},
    {"pt": "o lobo uiva",        "ru": "волк воет",     "pron": "volk vóet"},
    {"pt": "a abelha zumbe",     "ru": "пчела жужжит",  "pron": "pchilá zhuzhít"},
    {"pt": "eu tenho um cachorro","ru": "у меня есть собака","pron": "u minyá yest sabáka"},
    {"pt": "eu gosto de gatos",  "ru": "я люблю кошек", "pron": "ya lyublyú kóshek"},
    {"pt": "tenho medo de cobra","ru": "я боюсь змей",  "pron": "ya bayús zmei"},
    {"pt": "que animal é esse?", "ru": "что это за животное?","pron": "shto éta za zhivótnae"},
    {"pt": "é perigoso?",        "ru": "это опасно?",   "pron": "éta apásna"},
    {"pt": "é de estimação",     "ru": "это домашнее животное","pron": "éta damáshneye zhivótnae"},
    {"pt": "animal selvagem",    "ru": "дикое животное","pron": "díkaye zhivótnae"},
    {"pt": "no zoológico",       "ru": "в зоопарке",    "pron": "v zaapárke"}
]

caminho = PASTA / "animais.json"
with open(caminho, "w", encoding="utf-8") as f:
    json.dump(animais, f, ensure_ascii=False, indent=2)

print(f"OK: {caminho}")
print(f"Total: {len(animais)} cards")